### ISSUE TITLE
Assertion failed when calling GetBodyCreationSettings

### ISSUE THREAD

**Issue by Joshua-Ashton** [jrouwe/JoltPhysics#100]
Found this invalid assertion when writing code for serializing object state:

When calling `GetBodyCreationSettings`, an assertion can trigger if an object has `mMotionProperties != nullptr` (ie. was created as Dynamic) but is currently set as motion type `Static`.

**Comment by jrouwe** [comment]
Thanks, I fixed the assert in cb2bc4f67d93772c6dc47893efb37cd28dba1625
