### ISSUE TITLE
Include path rooting

### ISSUE THREAD

**Issue by JSandusky** [jrouwe/JoltPhysics#101]
All includes are using the directives route `#include <...>` the problem is ... do you really think anyone consuming this library doesn't have a `#include <Math/float4.h>` to conflict with yours?

It would be convenient to either make the paths relative or at least change things around so that it's all `#include <Jolt/...>` for the non-std lib includes.

It was a relatively minor task to find replace all `#include <` with `#include <Jolt/` and then fixup the stdlib includes, but it's a change that shouldn't have been necessary in the first place.

A trite problem, but one so obvious that if it is missed ... what else has been missed in the library? (figurative there, it looks quite excellent so far aside from header conflict hell, bloody love the positional motors)

**Comment by jrouwe** [comment]
Thanks for the report. I'll take a look what the best way to solve this is.

**Comment by tksuoran** [comment]
+1 for `#include <Jolt/...`

**Comment by jrouwe** [comment]
#106 is on its way.

**Comment by jrouwe** [comment]
#106 is merged.
