### ISSUE TITLE
Automatic transmission

### ISSUE THREAD

**Issue by bigidea-kz** [jrouwe/JoltPhysics#1043]
Hello! 
Sorry, I'm studying Jolt Physics and couldn't understand why in the VehicleConstraintTest example, the car's automatic transmission doesn't shift beyond 1? I tried to find information about this in the documentation but couldn't find anything either.

**Comment by jrouwe** [comment]
It does shift beyond 1, if I press the accelerator in VehicleConstraintTest it shifts gears normally (activate this debug view by presing C):

![image](https://github.com/jrouwe/JoltPhysics/assets/1621693/9e1cfd26-7099-4e6b-b310-06712255fd2b)

**Comment by bigidea-kz** [comment]
Thank you. Yes, I realized that. I understand why I thought so, because there wasn't enough space for acceleration)
