### ISSUE TITLE
Rolling and/or spinning friction?

### ISSUE THREAD

**Issue by tksuoran** [jrouwe/JoltPhysics#105]
I am only getting started to learn Jolt. I don't seem to be able to find rolling or spinning friction in Jolt Physics. The other physics library I've used has rolling friction to stop round shapes (spheres, cylinders, capsules) from rolling forever. Spinning friction has comment `torsional friction around contact normal`.

Is it the case that Jolt Physics does not support rolling / spinning friction? Is there no friction applied in case of round shapes rolling? What would be the best approach to deal with this?

**Comment by jrouwe** [comment]
We just use angular damping to stop objects from rolling forever.

**Comment by tksuoran** [comment]
Thanks.
