### ISSUE TITLE
Compile error on Sample project

### ISSUE THREAD

**Issue by ChivenZhang** [jrouwe/JoltPhysics#1068]
I put the source code on my computer and it compiled failed in the end.
This is my cpu info
![image](https://github.com/jrouwe/JoltPhysics/assets/48938612/07026efd-d7b4-47b6-9ce8-fbfcd7fa0e95)

This is my compile environment
![image](https://github.com/jrouwe/JoltPhysics/assets/48938612/5fb92a0e-859a-4230-9fb4-89829099ca83)

This is the compiler (msvc 2022)'s report
![image](https://github.com/jrouwe/JoltPhysics/assets/48938612/dbafb7d9-5963-4cea-81d5-86b5907d062a)

**Comment by jrouwe** [comment]
It looks like you're using a preview version of MSVC and it has a problem in the header files that ship with it.

I don't support preview versions of MSVC but you can work around this by not making the warnings fatal by setting the cmake option `ENABLE_ALL_WARNINGS=NO` (or by not using a preview version of MSVC).

**Comment by ChivenZhang** [comment]
I test sample project on another computer, It compiled successfully with same configuration in vs2022.
This is config from vs2022
![image](https://github.com/jrouwe/JoltPhysics/assets/48938612/80ff640d-2e85-4234-b44f-048a4dcb326a)
This is my another computer's info
![image](https://github.com/jrouwe/JoltPhysics/assets/48938612/86694bed-0b3a-4443-bd9e-5c0ca14d02a2)

**Comment by ChivenZhang** [comment]
I have asked my colleague for help, he said my original one not support simd instructions according to compilation error info.
![image](https://github.com/jrouwe/JoltPhysics/assets/48938612/898c12c1-36f4-4bd6-aa0d-545e27629b87)

**Comment by ChivenZhang** [comment]
> It looks like you're using a preview version of MSVC and it has a problem in the header files that ship with it.
> 
> I don't support preview versions of MSVC but you can work around this by not making the warnings fatal by setting the cmake option `ENABLE_ALL_WARNINGS=NO` (or by not using a preview version of MSVC).

ok, I resolved it. Thanks.

**Comment by jrouwe** [comment]
Note that I reported the issue to Microsoft [here](https://developercommunity.visualstudio.com/t/Including-immintrinh-in-MSVC-17100-Pr/10648138?)
