### ISSUE TITLE
Jolt.h inclusion indirectly disables warnings in project code

### ISSUE THREAD

**Issue by ifiddynine** [jrouwe/JoltPhysics#107]
First of all, Jolt is amazing. We switched over from PhysX recently and it's ❤. Thank you for this initiative!

Now to the issue, Jolt/Core/Core.h leaks disabled / ignored warnings into user code: https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Core/Core.h#L25 We found this out by noticing some expected warnings weren't treated as errors anymore after switching to Jolt.

We're working around this on our end, but I'm not sure what the preferred fix for the project would be. One way is changing to pragma push / pop, but that requires adding an "end" header to include after all of Jolt includes in user code.

The ideal change would likely be to only ignore these warnings where they occur instead of globally, using push / pop in the relevant functions.

**Comment by jrouwe** [comment]
Hello,

I was already wondering when someone would ask :)

With #108 the pragmas should no longer leave the Jolt headers.

Regards,

Jorrit.

**Comment by ifiddynine** [comment]
Heyo.

Awesome. That was quick haha, thank you very much!

**Comment by jrouwe** [comment]
Not everything passed the compiler unfortunately. MSVC is weird with warnings. Fixing it now.

**Comment by jrouwe** [comment]
Changes merged into master.
