### ISSUE TITLE
Is it possible to cast sphere ?

### ISSUE THREAD

**Issue by ChivenZhang** [jrouwe/JoltPhysics#1070]
I am wrapping jolt physics into my project according to [unity api](https://docs.unity3d.com/ScriptReference/Physics.html) doc. It's turns out that there's no way to do sphere-cast. I want to know wether it is possible to do that. Thansk.
This is api from unity doc:
![image](https://github.com/jrouwe/JoltPhysics/assets/48938612/e8ff931f-5f3e-4f69-94d3-ed335ec753aa)

This is api from jolt:
![image](https://github.com/jrouwe/JoltPhysics/assets/48938612/ef63dc17-81ae-435a-99a5-19fa051f4949)

**Comment by DocAce** [comment]
Yes, it's possible. Use GetNarrowPhaseQuery().CastShape() and pass in a sphere shape.

**Comment by ChivenZhang** [comment]
Yeah, I just found it in the sample project by using api "CollideShape". Ok, thansk.
