### ISSUE TITLE
Assert hit on a scene without constraints w/ `JPH::TempAllocatorMalloc`.

### ISSUE THREAD

**Issue by skaarj1989** [jrouwe/JoltPhysics#1102]
![image](https://github.com/jrouwe/JoltPhysics/assets/34756939/7368d767-410c-4829-b57b-7b49c11aefb7)
https://github.com/jrouwe/JoltPhysics/blob/56adf54375d4393be7752acd796e1ca3ea3f5474/Jolt/Core/Memory.cpp#L41

Triggered from:
https://github.com/jrouwe/JoltPhysics/blob/56adf54375d4393be7752acd796e1ca3ea3f5474/Jolt/Physics/PhysicsSystem.cpp#L281

**Comment by jrouwe** [comment]
Sorry about that. I'm not using `TempAllocatorMalloc` myself because the simulation runs slower than with `TempAllocatorImpl` so I didn't spot it.
