### ISSUE TITLE
Add more documentation about penetration axis vs GetSurfaceNormal

### ISSUE THREAD

**Issue by Joshua-Ashton** [jrouwe/JoltPhysics#111]
One of the big Jolt gotchas that we hit was the fact that the documentation to get the normal states to use `GetSurfaceNormal` with the contact point, but that only ever returns the normals of a face, it does not include the edges.

We spent many many hours debugging our player code to find out that what we actually wanted was `-(rotation * mPenetrationAxis).Normalized()` because we wanted either the normal of the closest face or edge.

Probably makes sense to add some documentation about the differences here, we spent so so so many hours playing with collision tolerances, penetration tolerance and all sorts, until I had an OHHHH THAT WILL ONLY DO FACES AND NOT EDGES moment when comparing normal logs on edges with the old physics system.

**Comment by jrouwe** [comment]
Ah I see. Yes GetSurfaceNormal is only supposed to be used in conjunction with CastRay. In that case you can't really hit an edge or a vertex so it always returns a face normal. I had assumed that it would be obvious that CollideShape and CastShape returned the normal directly but maybe mPenetrationAxis is not the best name for it :)

**Comment by jrouwe** [comment]
See 573be49e0fb90e6d356f12010ef350cc9d81336d
