### ISSUE TITLE
Sample CharacterTest.cpp

### ISSUE THREAD

**Issue by Snouf-ID** [jrouwe/JoltPhysics#1139]
In the sample "CharacterTest.cpp", when the character climbs onto a surface, and you release the movement key, he jumps suddenly. This is not expected behavior. Although it is just a sample, I think that for good practice, we must find a way without this problem.

You can see the bug : https://youtu.be/dTlBwNgZ2Bc

I think this is due to:

```c++
		// Update velocity
		Vec3 current_velocity = mCharacter->GetLinearVelocity();
		Vec3 desired_velocity = sCharacterSpeed * movement_direction;
		desired_velocity.SetY(current_velocity.GetY());
		Vec3 new_velocity = 0.75f * current_velocity + 0.25f * desired_velocity;
```

with **SetY**

Thank (and thank you for your samples which helps a lot)

**Comment by jrouwe** [comment]
I fixed the issue. I really recommend looking at `CharacterVirtual` since it is superior for player movement in almost every aspect.
