### ISSUE TITLE
Jolt doesn't compile on Windows UWP

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#115]
Just a heads up, Jolt doesn't compile on UWP. Not a big deal for me, I'll probably go without Jolt there for the time being.

The only thing that seems to not work there is in TickCounter.cpp. RegOpenKeyExA, RegQueryValueExA and RegCloseKey are not available in UWP. Everything else looks like it's compiling just fine.

**Comment by jankrassnigg** [comment]
We are using this toolchain file for UWP:
https://github.com/ezEngine/ezEngine/blob/dev/Code/BuildSystem/CMake/toolchain-winstore.cmake

That system version is the Windows SDK version to use, not sure whether 10.0 is sufficient.

That error doesn't ring a bell, however, you have to have UWP support installed in Visual Studio:

![grafik](https://user-images.githubusercontent.com/6001174/161936992-6c28b6df-2f95-4782-8be7-708dd7790489.png)

And yes, QueryPerformanceCounter and QueryPerformanceFrequency are available on UWP, that's what we use too.

We detect UWP like this:
https://github.com/ezEngine/ezEngine/blob/9d744017a6476d092c27070d9fcf5385ef841b2c/Code/Engine/Foundation/Basics/Platform/Win/Platform_win.h#L25

**Comment by jrouwe** [comment]
Installing UWP did the trick. Check out #118.

**Comment by jrouwe** [comment]
Change merged to master.
