### ISSUE TITLE
`-mfpmath=sse` is not supported by Emscripten

### ISSUE THREAD

**Issue by tetious** [jrouwe/JoltPhysics#1173]
Hi!

The change in this commit to enable sse with 32 bit builds seems to have broken building with Emscripten:
https://github.com/godot-jolt/jolt/commit/ebccdcbfae6b60e37480aa203d0781d26e437fbc

It throws: `error: unknown FP unit 'sse'`

I'm not sure if this is the correct path, but I can workaround by excluding it like this:
```CMAKE
if (NOT MSVC AND NOT EMSCRIPTEN)
	target_compile_options(Jolt PUBLIC -mfpmath=sse)
endif()
```

Perhaps there is a better way? I could file a PR to make this change, if you like.

**Comment by jrouwe** [comment]
Sorry about that. I get an error on all the other instruction set flags too, so I opted to bypass the entire code block.

**Comment by tetious** [comment]
Awesome! Thank you!

**Comment by mihe** [comment]
I'm a bit confused by this.

Shouldn't Jolt be adding the `-msimd128` flag itself instead, as well as any `-msse*` flags, based on the relevant CMake options? From what I can tell from [Emscripten's documentation](https://emscripten.org/docs/porting/simd.html#compiling-simd-code-targeting-x86-sse-instruction-sets) it still supports all these flags just fine, albeit with some gaps/emulation in the instructions themselves by the looks of it.

Clearly `mfpmath=sse` isn't supported though, judging by the error here, but seeing as how the user is forced to append the rest of them through something like `CMAKE_CXX_FLAGS` anyway I don't quite see the point in omitting them from Jolt altogether.

I'm also curious about the specific mention of `-msse4.2` here:

https://github.com/jrouwe/JoltPhysics/blob/6e0b867a246731d69e7535440aff436e54dc99bf/Jolt/Jolt.cmake#L623

Was SSE 4.2 just brought up as an example, or is there some limitation with Jolt and Emscripten that prevents targeting SSE2?

(I realize SSE 4.2 has pretty much 100% coverage these days, but Godot is still hanging on to SSE2 for now.)

**Comment by jrouwe** [comment]
> Shouldn't Jolt be adding the -msimd128 flag itself instead, as well as any -msse* flags, based on the relevant CMake options?

Yes it should. I've just submitted a change that adds a cmake option `USE_WASM_SIMD` which will add the needed flags.

> Was SSE 4.2 just brought up as an example, or is there some limitation with Jolt and Emscripten that prevents targeting SSE2?

Emscripten just translates the SSE/AVX instructions to WASM SIMD instructions. The reason why I didn't pick AVX is that Jolt uses 256 bit SIMD instructions when AVX is enabled, which is not supported by emscripten. I picked the next highest which is SSE 4.2. I don't think it matters which SSE version you pick as it all gets converted to WASM instructions and the browser is responsible for translating them to native (SSE / NEON) instructions based on the CPU architecture.

It may be that rewriting Jolt to use the WASM intrinsics gives better performance, but having the SSE instructions automatically convert to WASM instructions was a lot less work.

**Comment by mihe** [comment]
> Yes it should. I've just submitted a change that adds a cmake option `USE_WASM_SIMD` which will add the needed flags.

Great, thank you! Now there's just the dilemma of whether to actually enable it or not I guess. 😅

> I don't think it matters which SSE version you pick as it all gets converted to WASM instructions and the browser is responsible for translating them to native (SSE / NEON) instructions based on the CPU architecture.

I'm a bit surprised that the minimum hardware requirements for WASM SIMD isn't explicitly mentioned anywhere for any of the major browsers (that I could find at least). I had to dig through [the V8 source code](https://github.com/v8/v8/blob/810a6a367985abe28c3117a4920a442339203538/src/codegen/x64/assembler-x64.cc#L79-L85) to find that it's SSE4.1 for Chromium-based browsers. The one SSE4.2 instruction that's mappable to WASM SIMD (`_mm_cmpgt_epi64`) seems to have an SSE3 fallback in V8, as far as I can tell, so I assume they aim for everything to run on the minimum instruction set.

**Comment by Faless** [comment]
> EDIT: I see now that the [browser coverage](https://caniuse.com/?search=WebAssembly%20SIMD) isn't great for WebAssembly SIMD in general, but that's beside the point I guess.

The coverage is more or less in line with what Godot supports, the only browser lagging a bit behind is (unsurprisingly) Safari, which requires a quite recent version (but given you should always keep your browser updated, that's okay)
