### ISSUE TITLE
Serialized arrays are not compatible between 32 and 64 bit systems

### ISSUE THREAD

**Issue by attilaz** [jrouwe/JoltPhysics#1177]
https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Core/StreamIn.h#L38
https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Core/StreamIn.h#L63
https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Core/StreamIn.h#L78

These size_type bytes sizes are different on 32 and 64 bit systems. 
So a serialized object saved with 64 bits cannot be properly loaded on a 32bit system.

**Comment by jrouwe** [comment]
Thanks for the report. I'll fix this. Note that this will take a while since I'm on holiday.
