### ISSUE TITLE
VS2022_CL build fails with warning C4514 

### ISSUE THREAD

**Issue by diharaw** [jrouwe/JoltPhysics#1179]
Generating the visual studio solution using cmake_vs2022_cl.bat with Windows 10 SDK 10.0.22000.0 and building results in warning C4514:

`1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\immintrin.h(105,13): error C2220: the following warning is treated as an error
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\immintrin.h(105,13): warning C4514: '__check_isa_support': unreferenced inline function has been removed
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\immintrin.h(118,1): warning C4514: '__check_isa_avx10_512': unreferenced inline function has been removed
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\immintrin.h(125,13): warning C4514: '__check_arch_support': unreferenced inline function has been removed`

Had to use /wd4514 to get around it.

**Comment by jrouwe** [comment]
Can you check if you have 04ef2e1940dc2f32b843fd772e761af103bdb377? (This is not yet included in the latest release)

**Comment by diharaw** [comment]
Crap, my bad. I added the submodule again and it seemed like it was using an older cached commit which didn't have those fixes, sorry about that! Closing now! :)
