### ISSUE TITLE
FixedConstraint doesn't expose local frames

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#119]
I just started using the local space frames for joints, works nicely :)

I noticed that the fixed constraint does not expose any attachment frame, although internally it does have those values, of course.
I think it can be useful to be able to specify these frames, for cases where you want to dynamically link to objects and need them to snap together. Currently the constraint would just fix them in place, but that may not be sufficient for some game play scenarios.

Another option that I see is to use a different constraint type, e.g. a 6-dof constraint and configure it down to a fixed constraint.

Also another small thing I noticed, for which I don't want to create another ticket: For PhysicsSystem::GetBodyInterface(NoLock) there are no const variants. Would be nice to have them, because BodyInterface does have a couple of useful const functions.

**Comment by jrouwe** [comment]
const version for GetBodyInterface has been added.

W.r.t. the Fixed constraint: I did not expose an attachment frame on purpose there as the bodies are always fixed relative to each other, so you should be setting their positions anyway to make them match (if you place the bodies in a very different position than how they're supposed to be attached then it can take pretty long before the constraint is fully stabilized - sometimes it will never fully reach the 'fixed' position). It wouldn't be really hard to support supplying a reference frame, but I'm curious why it isn't possible to place the bodies in the right position?

**Comment by jankrassnigg** [comment]
Oh you mean just call SetPosition on them and then create the constraint? I guess that's a possibility, too, though I would expect that that can create other problems, like having the objects penetrate things that they shouldn't be able to. That's what the constraint would "fix" for you, by pushing things out of the way a bit more gently (I guess).

This isn't a super important request and I don't have a concrete use case at hand, mainly pointing out that it could be useful to someone and that it would be a bit more consistent to have this in the interface.

**Comment by jrouwe** [comment]
Yes, that's what I meant. But I can see your use case. Let me know if this becomes urgent.

**Comment by jrouwe** [comment]
Implemented in #166.

**Comment by jrouwe** [comment]
Be aware that this breaks the interface of FixedConstraint! You need to call SetPoint(body1, body2) now.
