### ISSUE TITLE
getters for attributes of tapered shapes (enhancement request)

### ISSUE THREAD

**Issue by stephengold** [jrouwe/JoltPhysics#1247]
`TaperedCapsuleShape` and `TaperedCylinderShape` have private attributes `mTopRadius`, `mBottomRadius`, `mConvexRadius` but no getters for those attributes. It would be convenient to have public getters for those attributes---and also for the half height of the tapered portion.

**Comment by jrouwe** [comment]
Sorry about that, I've added them.

**Comment by stephengold** [comment]
I see you added getters for `TaperedCylinderShape`. Thanks! How about `TaperedCapsuleShape` too?

**Comment by jrouwe** [comment]
Done

**Comment by stephengold** [comment]
Thanks again.
