### ISSUE TITLE
Issues deriving from Jph classes such as Shape 

### ISSUE THREAD

**Issue by tksuoran** [jrouwe/JoltPhysics#1253]
I have extended Jolt shapes with one additional custom shape, an empty shape, for use with some constraints.
The implementation has looked like this:
```C++
class EmptyShapeSettings final : public JPH::ShapeSettings{ ... };
class EmptyShape final : public JPH::Shape {...};
```
This used to work for a while, but now I run into couple of problems:

1. JPH custom RTTI macros assume they are used from inside JPH namespace. This means that classes using these macros must be inside JPH namespace. I could work with that.
2. Some compilers - at least gcc 14.1.0 - fail to link `EmptyShapeSettings` and `EmptyShape` because those are in my code, and my code needs to have standard C++ RTTI on, and these derived classes end up depending on base class having standard C++ RTTI.

```
[build] /usr/bin/ld: src/erhe/physics/liberhe_physics.a(jolt_collision_shape.cpp.o):(.rodata._ZTIN3JPH10EmptyShapeE[_ZTIN3JPH10EmptyShapeE]+0x10): undefined reference to `typeinfo for JPH::Shape'
[build] /usr/bin/ld: src/erhe/physics/liberhe_physics.a(jolt_collision_shape.cpp.o):(.rodata._ZTIN3JPH18EmptyShapeSettingsE[_ZTIN3JPH18EmptyShapeSettingsE]+0x10): undefined reference to `typeinfo for JPH::ShapeSettings'
```
I can think of the following options:

1. Add build configuration option to Jolt to build it with standard C++ RTTI on - purely in order to help interoperate with code that has RTTI on. I did not find such option in Jolt Cmake files
2. Jolt adds natively EmptyShape (it has no volume, it does not collide with anything). At least I needed it, so maybe it might be useful for someone else too.
3. Users (me) put such JPH extensions to an additional library which has RTTI disabled. Cumbersome, but might work
4. Users (me) find and remove all dependencies on standard C++ RTTI and disable it for their code. This does not feel like an attractive option to me.

Please advice. Thank you!

**Comment by mihe** [comment]
> 1. Add build configuration option to Jolt to build it with standard C++ RTTI on

This is already a CMake build option, called [`CPP_RTTI_ENABLED`](https://github.com/jrouwe/JoltPhysics/blob/d9cdf60ef40e0e450d4eeeea61d4588e01e65778/Build/CMakeLists.txt#L40-L42), which is disabled by default. Enabling it should resolve the linker error you're seeing.

**Comment by tksuoran** [comment]
Awesome, thanks!
