### ISSUE TITLE
TriangleShape::GetMassProperties expects static body but MustBeStatic is false

### ISSUE THREAD

**Issue by lukas-toenne** [jrouwe/JoltPhysics#1259]
The Triangle shape returns `false` for `MustBeStatic`, it is a moveable shape. But the `GetMassProperties` function always returns zero-mass default `MassProperties`:

https://github.com/jrouwe/JoltPhysics/blob/f95ad217f2c2797081cbc33b6d3463dd0ef65f84/Jolt/Physics/Collision/Shape/TriangleShape.cpp#L186

This triggers an assert in `UpdateCenterOfMassInternal` when changing to a triangle shape, because of the zero mass computed for a triangle shape. I'm not sure what the mass should be since it's a zero-volume shape and density is meaningless. Perhaps the convex radius should be used as a "minimum thickness" but i don't know if that radius is generally included for volume calculation.

**Comment by jrouwe** [comment]
The comment is not entirely correct. Technically you can have a dynamic triangle shape, but you need to provide the mass and inertia yourself (as it indeed cannot be calculated automatically). You can see this working if you change the `TriangleShapeTest` to:

```
void TriangleShapeTest::Initialize()
{
	CreateFloor();

	RefConst<TriangleShape> triangle_shape = new TriangleShape(Vec3(-10, 0, 0), Vec3(10, 0, -10), Vec3(0, 0, 10), 0.01f);
	BodyCreationSettings bcs(triangle_shape, RVec3(0, 1, 0), Quat::sIdentity(), EMotionType::Dynamic, Layers::MOVING);
	bcs.mOverrideMassProperties = EOverrideMassProperties::MassAndInertiaProvided;
	bcs.mMassPropertiesOverride.SetMassAndInertiaOfSolidBox(Vec3::sReplicate(10.0f), 1000.0f);
	mBodyInterface->CreateAndAddBody(bcs, EActivation::Activate);
}
```

Doing this is not very useful though as the triangle is single sided, so if it falls on the other side it sinks through the floor. The reason why it is this way is that it behaves in the same way as a `MeshShape` with only a single triangle. If you make the mesh shape closed, you can get a stable simulation as you can see in `DynamicMeshTest`.
