### ISSUE TITLE
Freeing a batch of objects with non-trivial destructors in FixedSizeFreeList results in an infinite loop.

### ISSUE THREAD

**Issue by randomuserhi** [jrouwe/JoltPhysics#1267]
Creating a `FixedSizeFreeList` of an item with a non-trivial destructor causes [this](https://github.com/jrouwe/JoltPhysics/blob/778cbb2d5ba418df99be5b7ef48431a0480240a7/Jolt/Core/FixedSizeFreeList.inl#L138) while loop to run forever:
```cpp
do
{
    ObjectStorage &storage = GetStorage(object_idx);
    storage.mObject.~Object();
    object_idx = storage.mNextFreeObject.load(memory_order_relaxed);
}
while (object_idx != cInvalidObjectIndex);
```

This is because `FixedSizeFreeList<T>::AddObjectToBatch` never sets the last item in the batch linked list to `cInvalidObjectIndex`. [reference](https://github.com/jrouwe/JoltPhysics/blob/778cbb2d5ba418df99be5b7ef48431a0480240a7/Jolt/Core/FixedSizeFreeList.inl#L109)

Either the last object in the batch needs to have `mNextFreeObject` set to `cInvalidObjectIndex` or the while loop in `FixedSizeFreeList<T>::DestructObjectBatch` needs to check the index is not equal to the batch's last index, also ensuring to do the last item (Simply changing the loop to `while (object_idx != ioBatch.mLastObjectIndex)` will skip the last item). Using `ioBatch.size` is another potential fix:
For example, replacing the snippet [here](https://github.com/jrouwe/JoltPhysics/blob/778cbb2d5ba418df99be5b7ef48431a0480240a7/Jolt/Core/FixedSizeFreeList.inl#L129) with:
```cpp
// Call destructors
if constexpr (!is_trivially_destructible<Object>())
{
    uint32 object_idx = ioBatch.mFirstObjectIndex;
    for (uint32 count = ioBatch.mNumObjects; count != 0; --count)
    {
        ObjectStorage &storage = GetStorage(object_idx);
        storage.mObject.~Object();
        object_idx = storage.mNextFreeObject.load(memory_order_relaxed);
    }
}
```

**Comment by jrouwe** [comment]
Thanks for reporting! It seems that Jolt is not using that code path. Note that I see FixedSizeFreeList as an internal type and didn't expect anyone to use it. What are you using it for?

**Comment by randomuserhi** [comment]
I'm actually not using it, but instead reading through your implementation as a learning exercise and just happened to stumble upon it by pure chance!
