### ISSUE TITLE
Jolt/Physics/SoftBody/SoftBodyUpdateContext.h is not copied when installed

### ISSUE THREAD

**Issue by shiena** [jrouwe/JoltPhysics#1270]
Probably because it is not defined in JOLT_PHYSICS_SRC_FILES in Jolt.cmake.
https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Jolt.cmake#L364-L374

**Comment by jrouwe** [comment]
Thanks! It was indeed missing.
