### ISSUE TITLE
can't invoke VehicleConstraint::OnStep() directly

### ISSUE THREAD

**Issue by stephengold** [jrouwe/JoltPhysics#1289]
```c++
    VehicleConstraint * const pConstraint
            = reinterpret_cast<VehicleConstraint *> (constraintVa);
    const PhysicsStepListenerContext *pContext
            = reinterpret_cast<PhysicsStepListenerContext *> (contextVa);
    pConstraint->OnStep(*pContext);

```

```console
/home/sgold/NetBeansProjects/jolt-jni/src/main/native/glue/v/VehicleConstraint.cpp: In function ‘void Java_com_github_stephengold_joltjni_VehicleConstraint_onStep(JNIEnv*, jclass, jlong, jlong)’:
/home/sgold/NetBeansProjects/jolt-jni/src/main/native/glue/v/VehicleConstraint.cpp:119:24: error: ‘virtual void JPH::VehicleConstraint::OnStep(const JPH::PhysicsStepListenerContext&)’ is private within this context
  119 |     pConstraint->OnStep(*pContext);
      |     ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from /home/sgold/NetBeansProjects/jolt-jni/src/main/native/glue/v/VehicleConstraint.cpp:28:
/home/sgold/NetBeansProjects/jolt-jni/src/main/native/Jolt/Physics/Vehicle/VehicleConstraint.h:199:49: note: declared private here
  199 |         virtual void                            OnStep(const PhysicsStepListenerContext &inContext) override;
      |                                                 ^~~~~~
```

Please make the `OnStep()` method public.

**Comment by jrouwe** [comment]
Why do you want to call this function? The intention is that you register the constraint as a step listener. This ensures it will get called at the right time.

**Comment by stephengold** [comment]
The situation is that I'm writing Java bindings for Jolt Physics. In order for the `VehicleConstraint` class on the Java side to implement the `PhysicsStepListener` interface, it must define a `public onStep()` method that invokes the C++ `onStep()` method.

In effect, I'm adding a layer of code (on top of the C++ `VehicleConstraint`) that intercepts `onStep()` calls and passes them to the C++ class. But I'm stuck because the C++ method is private.

**Comment by jrouwe** [comment]
Ok, in that case, can you use the same trick I'm using in JoltPhysics.js:

```
virtual void			OnStep(const PhysicsStepListenerContext &inContext) override
{
	PhysicsStepListener *instance = mInstance;
	instance->OnStep(inContext);
}
```

(cast to base class, then call OnStep)?

See: https://github.com/jrouwe/JoltPhysics.js/blob/9efb1ea362cc0b890e2a280c09527458560d16d1/JoltJS.h#L627-L631

**Comment by stephengold** [comment]
That trick seems to work in my case also. Thanks for your help.
