### ISSUE TITLE
Caller-controlled worker threads

### ISSUE THREAD

**Issue by sherief** [jrouwe/JoltPhysics#129]
Would it be possible to modify Jolt to, optionally, allow the API caller to manage the worker threads? If the caller already has a thread pool it would be advantageous to call `JobSystem.RunForThread(curThreadIdx);` and avoid a context switch.

**Comment by jrouwe** [comment]
Hello,

I don't understand the request. JobSystem is a virtual class that you can implement in any way you like. You can make it run on your own thread pool (and in fact we do). Can you explain what you cannot do with the interface?

**Comment by sherief** [comment]
PEBKAC on my side, the interface is perfect.
