### ISSUE TITLE
There is a missing header file when installing with ENABLE_OBJECT_STREAM turned off

### ISSUE THREAD

**Issue by shiena** [jrouwe/JoltPhysics#1293]
For example, `Jolt/Core/RTTI.h` includes `Jolt/ObjectStream/SerializableAttribute.h` but is not copied during installation.
So if I include RTTI.h in my code, it will not build.
The same goes for `Jolt/ObjectStream/SerializableObject.h` which is included by `Jolt/Core/LinearCurve.h`.

**Comment by jrouwe** [comment]
Thanks for reporting. As far as I can see SerializableObject.h was already installed, but there were several files missing indeed.
