### ISSUE TITLE
Make CapsuleShapeSettings class members public

### ISSUE THREAD

**Issue by Skroopa** [jrouwe/JoltPhysics#1297]
For consistency with other *ShapeSettings classes I would suggest to make `CapsuleShapeSettings` class members `public` as well:
https://github.com/jrouwe/JoltPhysics/blob/0a7d2501b33e1251101392d2be403c551ce5f963/Jolt/Physics/Collision/Shape/CapsuleShape.h#L13

**Comment by jrouwe** [comment]
They are public, the `JPH_DECLARE_SERIALIZABLE_VIRTUAL` macro does that (I agree that that is maybe not very obvious).
