### ISSUE TITLE
Raycast always returning true

### ISSUE THREAD

**Issue by TheSlugInTub** [jrouwe/JoltPhysics#1299]
Hello, I am trying to do a raycast towards the ground with a `NarrowPhaseQuery` to act as a ground check for the player, and this is how I'm doing it:
```cpp
float capsuleRadius = 1.0f;
float capsuleHeight = 2.0f;
float rayOffset = 4.0;
float rayLength = 5.0f;

JPH::Vec3 rayStart = playerPosition + JPH::Vec3(0, -capsuleHeight / 2 + rayOffset, 0);
JPH::Vec3 rayEnd = rayStart + JPH::Vec3(0, -rayLength, 0);
JPH::RRayCast ray(rayStart, rayEnd - rayStart);

// Create a result object to store the raycast hit data
JPH::RayCastResult rayCastResult;

const JPH::NarrowPhaseQuery& query = physicsSystem.GetNarrowPhaseQuery();

JPH::BroadPhaseLayerFilter layerFilter;
JPH::ObjectLayerFilter objectLayerFilter;

bool hit = query.CastRay(ray, rayCastResult, layerFilter, objectLayerFilter);

// Check if we have hit the ground and if so, jump if we press space
if (Input::GetKeyDown(Key::Space) && hit)
{
    // bleh bleh
}
```
But `hit` always returns true in this. I've debug printed the `rayStart` and `rayEnd` values and they seem to be just about fine, with `rayEnd`'s y value being lower than `rayStart`, and also if I set the `rayOffset` value higher than 4.3, it always returns false, any lower and it always returns true. I've messed around with the `rayLength` and it had no effect.
Even if I move the player a lot, away from the ground or near it, it still just returns either true or false.

**Comment by jrouwe** [comment]
It looks like you're passing in the default ObjectLayerFilter which will collide with all bodies. Could it be that you're hitting the player itself? Check rayCastResult.mBodyID to see what you're hitting.

**Comment by TheSlugInTub** [comment]
I checked it and the ray was indeed colliding with the player, so I set the offset a bit higher for the ray to not originate within the player collider, and it just returns an invalid ID, even though bodies are below the player, either the ray will only hit the player or just return an invalid ID.

**Comment by TheSlugInTub** [comment]
I just had to set the `rayOffset` to negative for whatever reason, thanks for the help though!
