### ISSUE TITLE
Constructor init idiom incompatible with not using exceptions

### ISSUE THREAD

**Issue by sherief** [jrouwe/JoltPhysics#131]
A lot of classes, like JobSystemThreadPool, are initialized via parameters passed to their constructor. This prohibits, for example, creating one as a member of a stack object then initializing it after reading values from a config file etc. The other, bigger problem I ran into was that JobSystemThreadPool allocates memory for barriers in its constructor - but there's no way to report failure from a constructor without exceptions. Memory allocation isn't the issue here, I know you can ensure no OOM etc but the bigger picture of not being able to report failures from classes with complex constructors is fatal.

I think it would be better to move towards having explicit .Init() / .Teardown() functions to enable usage of the library in exception-free build environments.

**Comment by jrouwe** [comment]
The JobSystemThreadPool class is really meant as an example, I'm expecting every project to want to roll their own implementation sitting on top of their own thread pool / job scheduler. I can take a look at that particular class though. Any more classes?

**Comment by jrouwe** [comment]
Fixed in #140
