### ISSUE TITLE
ClosestPoint::GetClosestPointOnTriangle inconsistent use of swapped inputs

### ISSUE THREAD

**Issue by atlv24** [jrouwe/JoltPhysics#1318]
`inA` and `inC` are conditionally swapped
https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Geometry/ClosestPoint.h#L176

yet later unswapped `inA` and `inC` are used
https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Geometry/ClosestPoint.h#L200

is this a bug or oversight? it only affects the degenerate case, so it may have been overlooked.

**Comment by jrouwe** [comment]
The function needs to return `outSet`, which specifies which 'feature' of the triangle is closest. The function starts by assuming C is closest and sets `outSet = 0b100`. Then A is checked and if it is closer `outSet = 0b001`, then B is checked and if it is closest `outSet = 0b010`. If it would use the swapped A/C vertices, then it would be harder to determine what `outSet` should be. 

The only reason for swapping A/C is that it produces a more accurate triangle normal and that is needed to determine if the triangle is degenerate (and it is used again in the non-degenerate code path).
