### ISSUE TITLE
[Feature request] add mUserData to VehicleController and VehicleControllerSettings

### ISSUE THREAD

**Issue by stephengold** [jrouwe/JoltPhysics#1320]
It would help if the `VehicleController` and `VehicleControllerSettings` classes included a `mUserData` field

similar to those found in the `BodyCreationSettings`, `CharacterVirtual`, `Constraint`, `ConstraintSettings`, `IndexedTriangle`, `Shape`, `ShapeSettings`, `SoftBodyCreationSettings`, and `Triangle` classes.

**Comment by jrouwe** [comment]
Not that I'm against adding the user data but: `VehicleConstraint` has user data. Can't you use `VehicleController::mConstraint.GetUserData()`? (this member is protected, but you can access it from any of the virtuals of the class)

**Comment by stephengold** [comment]
Thanks for that suggestion.
I pursued it. However, I need to read the user data from a static context, where `VehicleController::mConstraint` isn't accessible.

**Comment by jrouwe** [comment]
I made it accessible: https://github.com/jrouwe/JoltPhysics/commit/2d7176a2d2d908fb886f05c4a3ff93642f806c76

**Comment by jrouwe** [comment]
I'm going to close this issue, if this doesn't solve your issue let me know.
