### ISSUE TITLE
Can we get total_volume, submerged_volume returned from Body::ApplyBuoyancyImpulse?

### ISSUE THREAD

**Issue by Ono-Sendai** [jrouwe/JoltPhysics#1322]
I have some boat physics, that uses submerged_volume to decide how much friction and aerodynamic lift force to apply to the boat.
Since that is computed in ApplyBuoyancyImpulse, which is called for the boat, can Jolt be changed to return that value (as an out-arg or whatever)?
I have a local patch that does it, would be nice to get it upstream though.

E.g. https://github.com/jrouwe/JoltPhysics/commit/31d71ba3e999af0d583d988ac7da4685a2d46c45

**Comment by jrouwe** [comment]
Sure, I can add that.

**Comment by Ono-Sendai** [comment]
Awesome, thank you.
