### ISSUE TITLE
Android device overheats and slows down after 5 mins

### ISSUE THREAD

**Issue by marspixels** [jrouwe/JoltPhysics#1338]
Hi! I'm integrating a physics engine into my Android game. First I started with bullet but now I'm switching to Jolt

In bullet I have 100 compoundShapes and a heightFieldShape, it runs at 60Hz and update() function takes around **6ms-7ms**

In jolt I have 100 staticCompoundShapes and a heightFieldShape. It runs at 60Hz and the Update() function takes around **2ms-3ms** with only one thread. That's amazing, but after 5 minutes the Android device starts to overheat and the Update() function takes around **15ms-17ms**. It seems that Android activates thermal throttling or something

Although bullet is slower, during the simulation the Android device is cold even for 15 min, and the update() function keeps at 6ms-7ms

In both engines the compoundShapes have the ccd on and sleeping deactivated. Bullet has 10 solver iterations (default config) and Jolt has 10 velocity + 2 position iterations (default config) but disabled deterministic simulation. Both simulations are compiled and run independently

Finally I tried to compile jolt with -O2 and -O1 (rather than -O3) and added this flag "-fno-tree-vectorize". In addition, I added this line `std::this_thread::sleep_for(std::chrono::milliseconds(2));` after Update() function to sleep the thread. But nothing of these changes work at all, after 5 minutes the device starts to overheat

Can I configurate Jolt to priorice energy efficiency over speed? I think that this configuration could benefit phones and tablets

**Comment by jrouwe** [comment]
Are you using `JobSystemSingleThreaded` to limit Jolt to a single thread? If so, there should not be any spinloops or the like.

I don't think changing the commandline flags will help.

What I don't understand from your question is if you're running the physics update every 2 ms or if you're running it at 60Hz but that it only takes 2 ms. If you're running at 60Hz, then what are you doing with the 4 ms that you now got extra? Is that time spent sleeping (otherwise it's not really a fair comparison)?

One thing that I can think off that would make Jolt very CPU wasteful is if you misconfigured your broadphase layers so that it needs to constantly rebuild large broadphase trees. Make sure you at least have a layer that contains all the static stuff and one that contains stuff that can move.

**Comment by marspixels** [comment]
Thank you for your reply

I was using `jobSystem = new JPH::JobSystemThreadPool (JPH::cMaxPhysicsJobs, JPH::cMaxPhysicsBarriers, 1);`, but after your comment I am using `jobSystem = new JPH::JobSystemSingleThreaded(JPH::cMaxPhysicsJobs);` and the simulation is slower than before. But the device stills overheat after 5 mins

I am running it at 60Hz but physics Update() only takes 2-3 ms. I'm using a Handler that calls the loop() function every 16.6667 ms. So I guess that the extra 4 ms in jolt is sleeping

I use the broadphase layers provided at [HelloWorld.cpp](https://github.com/jrouwe/JoltPhysics/blob/master/HelloWorld/HelloWorld.cpp). The heightfieldShape uses Layers::NON_MOVING and CompoundShapes use Layers::MOVING.

**Comment by marspixels** [comment]
Sorry my fault. I was doing it with debug renderer enabled (draw AABB only). For same reason it seems that debug rendered in Jolt is much more CPU demanding than Bullet despite having the same draw calls

Now I've run the simulation with debug renderer disabled, logging the 100 compoundshapes positions and after 15 mins the phone is still cold and Update() function stays at 3ms :)

**Comment by jrouwe** [comment]
Cool!

Note that doing `new JPH::JobSystemThreadPool (JPH::cMaxPhysicsJobs, JPH::cMaxPhysicsBarriers, 1);` will create 1 worker thread, so effectively you're using 2 threads to run the sim: main thread + worker thread.

**Comment by marspixels** [comment]
Thank you for the info! I figured it out that because the simulation went slower with JobSystemSingleThreaded, but it's better to confirm it
