### ISSUE TITLE
Where to call RegisterDefaultAllocator() when initializing Jolt in class.

### ISSUE THREAD

**Issue by dajack05** [jrouwe/JoltPhysics#1357]
I'm working on adding Jolt to a pet-project of mine, and I've run into an odd issue. My initial plan was to call `RegisterDefaultAllocator()` in my Physics class constructor. But doing so seems to register the allocator with that function scope, resulting in all sorts of errors when I try to add bodies later.

I don't love the idea of having to call `JPH"::RegisterDefaultAllocator()` from my main function as that should really be handled by the engine, but I'm not exactly sure where to go with this.

Any advice? How have other solved this in the past?

Thanks!
-
Daniel Jackson

**Comment by jrouwe** [comment]
The implementation of that function is:

```C++
void RegisterDefaultAllocator()
{
	Allocate = AllocateImpl;
	Reallocate = ReallocateImpl;
	Free = FreeImpl;
	AlignedAllocate = AlignedAllocateImpl;
	AlignedFree = AlignedFreeImpl;
}
```

So it's just setting some pointers. Nothing scoped about it. I think something else is going wrong.

**Comment by dajack05** [comment]
Dang. I think I figured it out... I was storing the allocator and job system thread pool in the class as member variables requiring them to be initialized before I had a chance to call `RegisterDefaultAllocator()`... I'll just use a static "Init" method and make sure that runs before the Constructor.

Sorry for wasting your time 😅 Thanks for the help!

**Comment by MasterDrake** [comment]
> Dang. I think I figured it out... I was storing the allocator and job system thread pool in the class as member variables requiring them to be initialized before I had a chance to call `RegisterDefaultAllocator()`... I'll just use a static "Init" method and make sure that runs before the Constructor.
> 
> Sorry for wasting your time 😅 Thanks for the help!

I had the same problem ahahaha
