### ISSUE TITLE
How to set partial subshapes of a body as sensors

### ISSUE THREAD

**Issue by PYramid99** [jrouwe/JoltPhysics#1395]
Hello, I am learning JoltPhysics, it is interesting, but I have some problems. 

I know that a body can be set as a sensor in JoltPhysics. However, my requirement is to set partial subshapes of a body as sensors. 

Now my practice is modify ContactSettings.mIsSensor in the ContactListener callback if needed. But I'm not sure if this is the recommended practice, is there a better suggestion?

In the following case, I add a big box collider and a small box collider to a dynamic body, the latter is inside the former. The big box collider will set ‘ContactSettings.mIsSensor = true’ when invoke 'ContactListener::OnContactAdded' and 'ContactListener::OnContactPersisted'. But I did observe some shaking.

https://github.com/user-attachments/assets/3d4ee59b-4e23-4ff4-8908-f7dbd04eb6be

In the following case, I change the small box collider to the small sphere collider. The big box collider behaves as in the previous case, but the dynamic body penetrates the plane.

https://github.com/user-attachments/assets/7d8544d9-eb3a-4739-ab8e-c3192886578b

**Comment by jrouwe** [comment]
Interesting approach. I've never needed this, but I think it is possible with the current API. You need to set `BodyCreationSettings::mUseManifoldReduction = false` in order for it to work or else the contacts of both sub shapes may be combined and you'll get a single contact callback. Note that if your shape has other sub parts, those contacts won't be combined either anymore, so this comes at a performance cost.

See: #1397

**Comment by PYramid99** [comment]
> Interesting approach. I've never needed this, but I think it is possible with the current API. You need to set `BodyCreationSettings::mUseManifoldReduction = false` in order for it to work or else the contacts of both sub shapes may be combined and you'll get a single contact callback. Note that if your shape has other sub parts, those contacts won't be combined either anymore, so this comes at a performance cost.
> 
> See: #1397

Thank you so much for your patience and help, it did work! Jolt is awesome~😆
