### ISSUE TITLE
StreamUtils::RestoreObjectArray erroneously reports stream failure if the last object in a stream is a 0-length array

### ISSUE THREAD

**Issue by jeremy-wildlight** [jrouwe/JoltPhysics#1418]
I believe there may be an issue in `StreamUtils::RestoreObjectArray` which starts with the following:

```cpp
template <class ArrayType, class ValueType>
Result<ArrayType>	RestoreObjectArray(StreamIn &inStream, IDToObjectMap<ValueType> &ioIDToObjectMap)
{
	Result<ArrayType> result;

	uint32 len;
	inStream.Read(len);
	if (inStream.IsEOF() || inStream.IsFailed())
	{
		result.SetError("Failed to read stream");
		return result;
	}
```

If `len` here is identically 0, it's possible that the stream has no additional contents and the stream EOF bit is set correctly. In this case, the code will mark an error which propagates up the chain. This can occur, for example, if serializing an individual shape without a material list and invoking `sRestoreWithChildren`. Something along the lines of:

```cpp
if (len == 0)
{
    result.Set(ArrayType{});
    return result;
}
```

would resolve things I believe, although I'm not familiar enough with the stream implementation to know if stream failure checks are needed in this case as well.

**Comment by jrouwe** [comment]
Hello,

StreamIn follows the same conventions as std::basic_ios:

https://en.cppreference.com/w/cpp/io/basic_ios/eof

The eof flag is only set if you try to read beyond the end, not if after a read you are at the end of the stream. I will add that information to the documentation.

**Comment by jeremy-wildlight** [comment]
Aha, that explains it thanks. I mistakenly assumed `EOF` here meant "at end" instead of being a bit set as a side-effect on read.
