### ISSUE TITLE
Custom friction/restitution

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#143]
I know that I can pass in custom friction and restitution values in the contact report. However, I found that on ContactConstraintManager there is also a function that is used to combine these values for two bodies, that looks like it might be a nicer fit. However, it looks like all this is internal and there doesn't seem to be a way to actuall get access to ContactConstraintManager ?

It also already uses a certain way to combine the values and now I'm wondering, whether it might do unnecessary double work to combine the values, when I then override them later in the contact report.

Maybe this callback could be exposed ?

**Comment by jrouwe** [comment]
You mean PhysicsSystem::SetCombineFriction / PhysicsSystem::SetCombineRestitution? Or do you want to get this function?

**Comment by jankrassnigg** [comment]
That's weird, I checked for such functions and somehow did not see them!

However, looking at the interface, these don't give me the sub-shape ID of the contact point, so I can't use them to implement per material values. Would that be possible to pass through, or are the sub shapes not known at that point in the simulation?

**Comment by jrouwe** [comment]
The sub shape ID's are indeed available and it's a trivial change (see #144), note though that when you have manifold reduction on (PhysicsSettings::mUseManifoldReduction) you will receive one of the sub shape IDs in case multiple manifolds have been merged into one.

**Comment by jankrassnigg** [comment]
Awesome, thanks for the change!
I guess that for my use cases that caveat is no problem.

**Comment by jrouwe** [comment]
Merged #144
