### ISSUE TITLE
Bodies can still go through other bodies with linear cast if velocity is applied before every simulation

### ISSUE THREAD

**Issue by Joshua-Ashton** [jrouwe/JoltPhysics#150]
Not super sure what's going on here.

If I have a body and set it's velocity before every simulation, eventually it goes through the world.

I'm using LinearCast, but have also tried increasing substeps to 4 + setting the LinearCastThreshold to 0.

**Comment by jrouwe** [comment]
I can't reproduce this. I tried changing the BigVsSmallTest test like this:

```
void BigVsSmallTest::Initialize()
{
	// Create a big triangle
	TriangleList triangles;
	triangles.push_back(Triangle(Float3(-100, 0, 0), Float3(0, 0, 100), Float3(100, 0, -100)));
	Body &triangle = *mBodyInterface->CreateBody(BodyCreationSettings(new MeshShapeSettings(triangles), Vec3::sZero(), Quat::sIdentity(), EMotionType::Static, Layers::NON_MOVING));
	mBodyInterface->AddBody(triangle.GetID(), EActivation::DontActivate);
				
	// A small box
	BodyCreationSettings bs(new BoxShape(Vec3(0.1f, 0.1f, 0.1f)), Vec3(0, 1.0f, 0), Quat::sRotation(Vec3::sAxisX(), 0.25f * JPH_PI), EMotionType::Dynamic, Layers::MOVING);
	bs.mMotionQuality = EMotionQuality::LinearCast;
	Body &body = *mBodyInterface->CreateBody(bs);
	body.SetAllowSleeping(false);
	mBodyInterface->AddBody(body.GetID(), EActivation::Activate);
	mBodyID = body.GetID();
}

void BigVsSmallTest::PrePhysicsUpdate(const PreUpdateParams &inParams)
{
	mBodyInterface->SetLinearVelocity(mBodyID, Vec3(0, -100, 0));
}
```

Adding to the header:

```
BodyID			mBodyID;
```

But the cube doesn't fall through the triangle. Can you modify the example to show the failure case (I don't know what kind of shapes are colliding and how they're oriented)?

**Comment by Joshua-Ashton** [comment]
I will try to make an example case soon, yes.

**Comment by Joshua-Ashton** [comment]
Looks like it only ends up happening because we call `SetInverseMass` with a very large mass (so small inverse mass) before.

**Comment by Joshua-Ashton** [comment]
Yeah, looks like it's because of our SetInverseMass call, using SetMassProperties like so fixes it:

```cpp
void JoltPhysicsObject::SetMass( float mass )
{
    mass = Clamp( mass, 0.0f, VPHYSICS_MAX_MASS );

    m_flCachedMass = mass;
    m_flCachedInvMass = mass ? 1.0f / mass : 0.0f;

    if ( !IsStatic() )
    {
        JPH::MotionProperties* pMotionProperties = m_pBody->GetMotionProperties();

        // Josh: This is what we used to do and it was giving VERY whacky results
        // when moving objects around after calling SetMass.
        // pMotionProperties->SetInverseMass( m_flCachedInvMass );
        // This method below seems to work properly because it deals with all of the inertia crap.
        JPH::MassProperties massProperties = m_pBody->GetShape()->GetMassProperties();
        massProperties.ScaleToMass( mass );
        massProperties.mInertia( 3, 3 ) = 1.0f;
        pMotionProperties->SetMassProperties( massProperties );

        CalculateBuoyancy();
    }
}
```

Perhaps there should be some documentation about this, or am I missing something?..

**Comment by jrouwe** [comment]
If you were only calling SetInverseMass and not SetInverseInertia then things go out of sync indeed. The inertia tensor is dependent on the mass, if they become too different then I can imagine things starting to fail. So you were only setting SetInverseMass? (if so I'll add some documentation)

**Comment by jankrassnigg** [comment]
Thanks for posting that sample code, I do something similar in a component for grabbing objects and was not aware that I need to also adjust the inertia thing.

**Comment by jrouwe** [comment]
Ok, I'll update the documentation.

**Comment by Joshua-Ashton** [comment]
Thanks!

**Comment by jrouwe** [comment]
Documentation updated.
