### ISSUE TITLE
Fixed constraints really wobbly

### ISSUE THREAD

**Issue by Joshua-Ashton** [jrouwe/JoltPhysics#151]
Having a body of low mass, fixed to a body of much higher mass creates a really wobbly 'weld', especially rotation-wise.

Any idea how to improve this? I could maybe use a constraint with more DOF and fix their axes...

**Comment by jrouwe** [comment]
Can you try #154?

**Comment by Joshua-Ashton** [comment]
Yeah! That helps a LOT. I no longer see the droopiness when something is fixed.

Building cars and stuff of out hundreds of FixedConstraints is actually stable and doesn't just turn into a mess of stuff that flips out now. Woo hoo!

**Comment by Joshua-Ashton** [comment]
Well, if I am veeery aggressive with it that still happens, but it is much better

**Comment by jrouwe** [comment]
Merged #154. 

Note that there will still be issues when the whole construction rests onto the light body. The light body will not be powerful enough to push away the heavy body (see HeavyOnLightTest). The only way around it is by increasing the iteration count a lot (PhysicsSettings::mNumVelocitySteps, mNumPositionSteps). I would recommend cheating with the masses a bit to redistribute the total mass more equally.
