### ISSUE TITLE
Character: Expose overlap check

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#152]
As discussed here:
https://github.com/jrouwe/JoltPhysics/issues/88#issuecomment-1107633113

Would be nice, if I could ask the (Virtual)Character whether it could safely be teleported somewhere.

**Comment by jrouwe** [comment]
This is just making Character::CheckCollision public right?

**Comment by jankrassnigg** [comment]
> So would be cool, if the character had a CheckOverlap(position, optional new shape) function, where I can either pass in a new shape, or nullptr and then it just takes the current shape to check for overlaps at that location.

It would be useful to be able to use a different shape than the current, so that one can check for different stances.

**Comment by jankrassnigg** [comment]
Looks good. Don't worry about the time, though, I know how it is to work on stuff in spare time only.

**Comment by jrouwe** [comment]
#155 was merged.
