### ISSUE TITLE
Serialize whole PhysicsSystem + shapes + constraints?

### ISSUE THREAD

**Issue by Joshua-Ashton** [jrouwe/JoltPhysics#163]
Hello!

I was interested in being able to dump the game's physics system and add a loader to the Samples to be able to play around with it there. It's also useful for viewing in the viewer.

Same goes for being able to report some issues with constraint stability in some instances, I wanted to dump my phys env so I could easily demonstrate how it's stable to start, then after playing around with it enough it will go crazy and fly all over. (There's lots of constrained convex objects interacting.)

There's a few paths I have tried for doing something like this, one was calling SaveState on PhysicsEnvironment, this doesn't seem to save the shapes that I can tell.

The other path is using the PhysicsScene, but this suffers from not replicating constraints as I have to convert it to use the the BodyCreationInfo.

Am I missing something?

**Comment by Joshua-Ashton** [comment]
Additionally, I also tried to implement save/restore today and ran into an issue where constraints seem really annoying to do.

Bodies were really easy, I could just get their creation settings with the helper then serialize that, and then restore the created body -- with constraints, such as the DistanceConstraint class, I do not see a function to get something like that.

**Comment by jrouwe** [comment]
This is indeed not properly supported at the moment. 

The closest thing that exists is PhysicsScene (see e.g. LoadSaveBinaryTest). 

You can query all bodies in the PhysicsSystem and convert them back to BodyCreationSettings and save them in binary using PhysicsScene::SaveBinaryState. The PhysicsScene doesn't support any constraints at the moment though. This would not be hard to add (just add a vector<ConstraintSetup> to PhysicsScene where class ConstraintSetup { Ref<TwoBodyConstraintSettings>, body 1 index in PhysicsScene::mBodies, body 2 index }). Then we would indeed need a function to do GetConstraintSettings on a Constraint. ConstraintSettings already has a SaveBinaryState function that can be used in PhysicsScene::SaveBinaryState.

Finally, everything could come together in a utility function PhysicsScene::FromPhysicsSystem(PhysicsSystem *) to create the scene.

Note that not everything is converted from Body to BodyCreationSettings (e.g. linear/angular velocity should be added to it).

Saving using ObjectStream (text format) would be possible too, but a bit harder as GetBodyCreationSettings doesn't convert a Shape into ShapeSettings, so ObjectStream won't serialize it. That means Shape would need to have a GetShapeSettings function if we want these snapshots to survive multiple library versions.

**Comment by Joshua-Ashton** [comment]
> Note that not everything is converted from Body to BodyCreationSettings (e.g. linear/angular velocity should be added to it).

Yeah, I make the body from the serialized creation settings then also restore the body's state

**Comment by jrouwe** [comment]
I'm adding the linear/angular velocity to the BodyCreationSettings right now. The other things are also quite easy but will take me a bit of time.

**Comment by Joshua-Ashton** [comment]
No worries, let me know if you need help with anything :)

**Comment by jrouwe** [comment]
Typed (most of) it in: #165. It's not really well tested yet and I did not implement all constraints.

**Comment by Joshua-Ashton** [comment]
> I'm adding the linear/angular velocity to the BodyCreationSettings right now. The other things are also quite easy but will take me a bit of time.

Should also add mEnabled to constraint creation settings

**Comment by Joshua-Ashton** [comment]
Looks like the new constraint stuff works! Woohoo!

I will test dumping a scene and loading it in the Samples thingy tomorrow.

(Disregard NaN assert in video after, I did not restore the player controller yet)
https://user-images.githubusercontent.com/21316711/168496666-cfd6d06a-d92b-47bb-a5d6-50bc3692b19e.mp4

Let me know when 6DOF is in and I can test it with ragdolls too.

**Comment by Joshua-Ashton** [comment]
Hmm, didn't have luck saving/reloading from the file. The world body loaded, but the constrained bodies were just not present for some reason.

Here is my stuff for modifying it for load: https://github.com/Joshua-Ashton/JoltPhysics/tree/test2

The dump is here.

https://share.froggi.es/db7f5dee3a27

**Comment by jrouwe** [comment]
There were several bugs in the code that I wrote yesterday. I fixed them (and also implemented getting the constraint settings for the 6DOF constraint). The PR has been merged into master. Hopefully your scene will save properly now.

There's a couple of constraints that are left to do, most importantly the FixedConstraint. I first need to support local space constraint setup as per #119 before I can fix this. Same goes for PathConstraint.

B.t.w. are you capturing the snapshots on 32 bit and playing them back on 64 bit? (I think it should work, but there could be some mismatch)

**Comment by Joshua-Ashton** [comment]
No these were both 64-bit but it was mostly fixed constraints. I perused over but missed that they weren't serialized yet.

Strange that all the bodies were missing entirely though... will try again later

**Comment by jrouwe** [comment]
#166 fixes serialization of the fixed constraint.

Be aware that this breaks the interface of FixedConstraint! You need to call SetPoint(body1, body2) now.

**Comment by jrouwe** [comment]
Closing this since we have moved on to #170
