### ISSUE TITLE
IsNormalized functions have very low tolerance

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#172]
I'm pretty much always using debug builds and often I get asserts that some vector or quaternion isn't normalized, even though it is, just not within the very strict tolerance.

By now I'm therefore normalizing a lot of input data to Jolt, even though it wouldn't be necessary, just to get within the precision range that Jolt expects. Though I have also seen these asserts fire WITHIN Jolt, with a particular simulation state, though those are very hard to reproduce.

With SSE unfortunately precision is very quickly pretty bad and various compiler optimizations (and different compiler versions) can make this very painful. I've run into this problem with many projects over the years and by now I'd argue that checking for precise unit-length is not such a great idea. An epsilon of 0.1 will catch all input data that is clearly not normalized at all, which is definitely a bug, but an epsilon of 0.0001 is mostly just procuding false negatives.

**Comment by jrouwe** [comment]
We have these asserts on in both our debug and release builds and for us they almost never trigger, so I'm surprised this is an issue for you. I think we normalize quaternions for the rotation of bodies before passing them on to Jolt, but other than that I don't think we do anything special. For quaternions, you really want them to be as close to normalized as possible as the error in the simulation starts to accumulate fast if you don't.

Do you have more concrete examples of where things go wrong?

**Comment by jankrassnigg** [comment]
Well "almost never" - yes. But still "sometimes" :D

> I think we normalize quaternions for the rotation of bodies before passing them on to Jolt

That is also what I am now doing. I have a couple of cases where I didn't expect that I need to do this, for example I have a rope component that concatenates multiple bodies. For that multiple rotations are done in sequence and each quaternion is normalized, and the result is still normalized, but apparently it sometimes is outside the accepted error. But ok, not such a big deal to normalize again.

For the internal error, I think I encountered this once or twice now and I have no way to reproduce it. I think it is related to updating Jolt with a higher (or varying) timestep. Usually I don't update with fixed 60 FPS, but with something that can fall back to larger timesteps, if there is a particularly large delay. Jolt generally doesn't like that (not unexpectedly) but it also seems to increase the chance that this assert triggers internally.

**Comment by jrouwe** [comment]
I would not recommend updating with < 60 FPS, the simulation becomes really erratic at that point. In any case, I'm going to close this ticket unless there's anything else you want me to look at?
