### ISSUE TITLE
Xcode 14 beta 6 (iOS build) strange memory alignment issue in MutexArray

### ISSUE THREAD

**Issue by JohnTM** [jrouwe/JoltPhysics#224]
Hi

I'm trying to switch our engine's physics from Bullet to Jolt. I'm just testing a basic build with the `PhysicsSystem` class and I'm already getting some assertion failures. Based on values in memory I think there's some kind of strange alignment issue, since half of a `MutexArray::mMutexStorage` pointer is being overwritten by `0xbebebebe`

This happens inside of `BodyManager::Init` within `mBodyMutexes:Init`

I've tried turning off the custom allocator but this didn't seem to do anything

Clang version:
```
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: arm64-apple-darwin21.5.0
```
Screenshot in Xcode debugger:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/1672937/188349011-42b2a24a-eac7-4a87-a494-4eeab79f17e8.png">

**Comment by JohnTM** [comment]
I'm totally stumped by this since another thing that seems to be happening is that the contents of the `PhysicsSystem` instance changes depending on where I which part of the callstack I'm looking in:
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/1672937/188352713-1db2df7b-019f-4c1a-a0ae-8781d0989956.png">
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/1672937/188352734-bddde7b8-6b4f-41ed-b1cd-28b86c1be36b.png">

Outside the `PhysicsSystem:Init()` call, everything looks fine. Once inside, various pointers are messed up. But stepping back out again its fine and vice-versa (see `mActiveBodies`)

**Comment by jrouwe** [comment]
Hello,

This typically happens if you are compiling the calling code with different defines than Jolt. E.g. in a debug build Jolt uses _DEBUG, JPH_PROFILE_ENABLED and JPH_DEBUG_RENDERER. If the calling code doesn't have the same defines, the class size changes according to where you are on the callstack and you get weird crashes.

Regards,

Jorrit.

**Comment by JohnTM** [comment]
@jrouwe That makes perfect sense. For some reason I assumed it'd simply fail to compile if in that case. I'll set the main project to use the same defines and see if that fixes it. Thanks!

**Comment by JohnTM** [comment]
@jrouwe That fixed it, thanks!
