### ISSUE TITLE
Sensors and Kinematic Bodies

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#238]
This issue is similar to #130 but it happens for kinematic objects.

When a kinematic object overlaps with a sensor, at first I do get a contact report. As long as nothing else in the scene happens, it then continues to proplerly report those contacts:

https://user-images.githubusercontent.com/6001174/192524224-f8cc0edc-b26e-478d-b185-a9640362d858.mp4

However, if anything else generates contacts in the scene, even outside the sensor, the behavior becomes erratic. Basically the contacts may get removed and added for a short while, but then the sensor completely stops reporting those contacts.

https://user-images.githubusercontent.com/6001174/192524529-3ace64e2-b0ea-4262-86a8-e12602cdb4fb.mp4

The video only captured a simpler result, but in practice I have seen the result flicker on and off for half a second or so, before it settles on not reporting contacts any further.

Thing is, I wouldn't have been surprised, if sensors wouldn't report ANY contacts with kinematic objects ever. But IF Jolt is supposed to do so, then I would expect it to do it the same way as for dynamic objects.

My sensor uses motion type kinematic.

**Comment by jrouwe** [comment]
I could reproduce it. Whether or not the contact was reported depended on the order in which the kinematic body and sensor were activated (and the 3rd body would affect that order if it went to sleep).

#240 should fix it, it was introduced by my fix for #130.
