### ISSUE TITLE
Creating SphereShapeSettings on heap fails

### ISSUE THREAD

**Issue by niansa** [jrouwe/JoltPhysics#244]
Hey!

I am trying to create a SphereShapeSettings object on heap:

    auto x = new SphereShapeSettings(1.0f);

It just causes a segmentation fault. Same thing works just fine on stack:

    SphereShapeSettings x(1.0f);

My compiler is GCC 12.2.0 - Debian Sid.

Thanks for the hard work of creating this physics engine

Tuxifan

**Comment by jankrassnigg** [comment]
This happens if you haven't set a custom allocator. Easiest fix is to compile Jolt with JPH_DISABLE_CUSTOM_ALLOCATOR. Other option is to set the custom allocator hook.

See this file: https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Core/Memory.h

**Comment by niansa** [comment]
Using `::new SphereShapeSettings` seems to be working just fine

**Comment by niansa** [comment]
Where do I set `JPH_DISABLE_CUSTOM_ALLOCATOR`? Do I just `#define` it in every file I include Jolt? There doesn't seem to be a cmake option.

**Comment by niansa** [comment]
I fixed it, `RegisterDefaultAllocator()` was simply called too late.
