### ISSUE TITLE
using namespace std;

### ISSUE THREAD

**Issue by deltars** [jrouwe/JoltPhysics#245]
Many thanks for this wonderful physics library.

In Core.h, there is the line:

using namespace std;

Unfortunately, Core.h is included by all header files and so this line will be in any project that includes Jolt. This is typically a big problem for any project that doesn't otherwise use the std namespace, because it modifies the project that is including Jolt. It can be difficult to use the std namespace in your project when also using other libraries. This means that any project that defines a type with a name that conflicts with the std namespace (such as "byte") then the project will not build.

Typically, libraries avoid modifying the global state from their header includes, such as using namespaces, setting pragmas, etc. The using namespace directive is generally recommended not ever to be used in header files for this reason.

Would it be possible to remove the "using namespace"?

Many thanks

**Comment by jrouwe** [comment]
Hello,

The 'using namespace std' is contained in the namespace JPH, so the std symbols should not leak outside of the header file.

Jorrit.

**Comment by deltars** [comment]
Thank you Jorrit, you are correct. This is not an issue so you can delete.

**Comment by rcane** [comment]
> The 'using namespace std' is contained in the namespace JPH, so the std symbols should not leak outside of the header file.

Although this is correct, having all `std` symbols imported like this has another (usually unwanted) side effect. Try this in a cpp file:
```
class vector
{
};

#include "Jolt/Jolt.h"
```
This will get us an "ambiguous symbol" error because the `vector` class is now clashing with the one from `std::` imported into the `JPH` namespace. This example can be fixed by just moving the class declaration after the Jolt include, but in real code it might not be that easy.

These are just my two cents as one that recently discovered Jolt (great work, by the way) and thinking of integrating it into my current PhysX-based engine.

**Comment by jrouwe** [comment]
I quickly tried removing 'using namespace std' and it means adding 'std::' to hundreds of locations (and I don't like the verbosity it introduces). If this is just theoretical instead of an actual issue that you're running into then I would prefer to keep things the way they are.

**Comment by deltars** [comment]
After reviewing rcanes comment, i think this is could be an issue.

The using namespace doesn't persist after including Jolt. However, as pointed out, it means either you include Jolt before anything else, or otherwise risk errors inside jolt because of a previous declaration.

This was indeed my issue as I had previously included Microsofts wonderful RpcNdr.h which declares "byte".

So just include Jolt first? Well, this works great until another library takes the same attitude and then they are not compatible with each other. So, probably better practice to add std:: but ultimately its up to the maintainers to know if its worth it.

I will re-open and leave for someone else to decide.

**Comment by tksuoran** [comment]
Would it work, instead of putting using namespace into namespace scope, to put using namespace into smaller scopes like class or function?

**Comment by jrouwe** [comment]
Fixed in #308
