### ISSUE TITLE
SubShapeIDPair in OnContactRemoved is invalid

### ISSUE THREAD

**Issue by yangfengzzz** [jrouwe/JoltPhysics#249]
I found the SubShapeIDPair in callback OnContactRemoved is invalid.

You can use HelloWorld to test it. After making the floor tilt a bit, the ball will roll off, the SubShapeIDPair in callback OnContactRemoved will return two bodyID but they are all invalid

**Comment by jrouwe** [comment]
I guess this was an issue on your side?
