### ISSUE TITLE
How to create .dll for Jolt Library?

### ISSUE THREAD

**Issue by zz2108828** [jrouwe/JoltPhysics#314]
I'm trying to generate the Jolt dll file in cmake,but I encountered some problems.
I replace STATIC with SHARED in add_library statement (in the Jolt.cmake).
`add_library(Jolt SHARED ${JOLT_PHYSICS_SRC_FILES})`

It fails to build and get the error.
```
1>CUSTOMBUILD : CMake error : Error required internal CMake variable not set, cmake may not be built correctly.
1>Missing variable is:
1>CMAKE_SHARED_LINKER_FLAGS_RELEASEASAN
1>CUSTOMBUILD : CMake error : Error required internal CMake variable not set, cmake may not be built correctly.
1>Missing variable is:
1>CMAKE_SHARED_LINKER_FLAGS_RELEASEUBSAN
1>CUSTOMBUILD : CMake error : Error required internal CMake variable not set, cmake may not be built correctly.
1>Missing variable is:
1>CMAKE_SHARED_LINKER_FLAGS_RELEASECOVERAGE
1>CUSTOMBUILD : CMake error : Error required internal CMake variable not set, cmake may not be built correctly.
1>Missing variable is:
1>CMAKE_SHARED_LINKER_FLAGS_DISTRIBUTION
```
Then I add some set("","") to aoid the error and I have the dll.
But when I use the dll to link the exe program, it tells me that the undefined symbol.

**Comment by zz2108828** [comment]
**Close reason:I find the c# bind project which provide dll generator.**

**Comment by jrouwe** [comment]
Hello,

Why do you want to use Jolt from a DLL? Jolt was made to be used as a static library and doesn't mark any functions for DLL export, so even if you were able to compile it, there is no interface.
