### ISSUE TITLE
Changing motion quality at low update frequencies results in heap corruption

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#340]
When changing the motion quality from `Discrete` to `LinearCast` while stepping `JPH::PhysicsSystem` at a frequency somewhere below 30 hz it ends up with an out-of-bounds write to `ioSubStep->mCCDBodies` in [`PhysicsSystem::JobPreIntegrateVelocity`](https://github.com/jrouwe/JoltPhysics/blob/3657dca808b267c85ce3a7971545e5e2b7ef5453/Jolt/Physics/PhysicsSystem.cpp#L1450).

If the stars align just right it will sometimes trigger the assertion in [`PhysicsSystem::JobPostIntegrateVelocity`](https://github.com/jrouwe/JoltPhysics/blob/3657dca808b267c85ce3a7971545e5e2b7ef5453/Jolt/Physics/PhysicsSystem.cpp#L1495) that checks the size of `mNumCCDBodies` against `mBodyManager.GetNumActiveCCDBodies()`, but that seems to be a rare occurrence.

Steps to reproduce:

1. Clone my branch [`motion-quality-corruption`](https://github.com/mihe/JoltPhysics/tree/motion-quality-corruption) (see diff [here](https://github.com/jrouwe/JoltPhysics/compare/master...mihe:JoltPhysics:motion-quality-corruption))
2. Build a configuration with some sort of heap debugging
    - `Debug` with MSVC seems to work for me, even with the custom allocators and whatnot
3. Run the new Samples test `ChangeMotionQualityTest` (based on `ChangeMotionTypeTest`)
4. Set the "Update Frequency (Hz)" setting to somewhere below 30 hz
    - 30 hz seems to be low enough in my project, but in Samples I have to go as low as 20 hz.
5. Unpause the test
6. Wait a short while until it switches the motion quality to `LinearCast`
7. Note access violation trying to write out-of-bounds

**Comment by jrouwe** [comment]
Funny how that works: I never considered that anyone would want to change the motion quality on the fly but made it possible to do so by accident. What happens is that I cache the number of active bodies that have quality LinearCast in BodyManager::mNumActiveCCDBodies but that's not correct if you change a quality type while the body is active. As a quick workaround you can deactivate the body before changing it but I will implement a proper fix.

**Comment by jrouwe** [comment]
Fix is in #342

**Comment by jrouwe** [comment]
B.t.w. super cool that you're developing a godot extension! What version godot is this for? (4 supposedly rewrote everything physics related)

**Comment by jrouwe** [comment]
Thanks for the info, and yes, please let me know if you run into issues. I'm happy to help!
