### ISSUE TITLE
clang-cl builds fail with warning/error about missing parameter

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#345]
If you build `Distribution` using `cmake_vs2022_clang.bat` you currently get a couple of warnings (as errors) in the style of:

```
Jolt/Physics/Collision/ManifoldBetweenTwoFaces.h(16): error : parameter 'inCenterOfMass' not found in the function declaration [-Werror,-Wdocumentation]
```

This is a bit of a false positive, since the parameter `inCenterOfMass` is there, but it's being left out because of the `#ifdef JPH_DEBUG_RENDERER`.

Apparently [`/Wall`](https://github.com/jrouwe/JoltPhysics/blob/bc6d4e100b1873825620b3c55f6a79f9c616fc39/Build/CMakeLists.txt#L68) in MSVC/clang-cl translates to `-Weverything` in Clang, which is different from `-Wall` in GCC/Clang, which, despite the name, does not enable all warnings.

`-Weverything` includes `-Wdocumentation`, which is what's enabling this warning.

It might be worth pointing out that GitHub Actions includes the LLVM component of Visual Studio, so it's possible to have it run as part of the CI.

**Comment by jrouwe** [comment]
Should be fixed in c2f97c1aaf44307d19fd9517603f33a49b25c2ec. Never thought I would be conditionally compiling comments :)

**Comment by jrouwe** [comment]
Hmmm, I don't think that's a big deal. I would like to keep that documentation warning on as it helps prevent the doxygen build failing because that doesn't run until a PR is merged (I'm adding the MSVC clang builds as we speak).

**Comment by jrouwe** [comment]
I just tried that, but that generates a ton of extra warnings (about e.g. padding being added), so I don't think ```/Wall``` is the same as ```-Weverything```. Besides, clang doesn't recommend using it: https://clang.llvm.org/docs/UsersManual.html#diagnostics-enable-everything.
