### ISSUE TITLE
No way of locking body movement axis like `PxRigidDynamicLockFlag`?

### ISSUE THREAD

**Issue by peter1745** [jrouwe/JoltPhysics#359]
Hello! I'm just wondering if there's a way of locking translation and rotation of a body to a given axis, in the same way that PhysX does with `PxRigidDynamicLockFlag`?
Looked around a bit in the code and found nothing that would indicate it, but since I might've missed something (maybe a constraint?) I figured I'd ask here.

If that's not currently a feature is it something that might get supported in the future?

**Comment by jrouwe** [comment]
@mihe is correct. I want to add that most people that seem to be interested in this want to make a 2D simulation. If this is your case then please read: https://github.com/jrouwe/JoltPhysics/discussions/180.

**Comment by peter1745** [comment]
@mihe Thanks, I'll see about getting that working!

@jrouwe Not looking for 2D in this case, but thanks for the link anyway!

**Comment by peter1745** [comment]
@mihe @jrouwe Hey just wanted to check, is it possible for me to constrain a body to itself in order to achieve this? Or should I have a central static body that I constrain the dynamic body to?

**Comment by peter1745** [comment]
@jrouwe so I've managed to get this to sort of work with this code:
```cpp
JPH::SixDOFConstraintSettings constraintSettings;
constraintSettings.mSpace = JPH::EConstraintSpace::LocalToBodyCOM;

if ((m_LockedAxes & EActorAxis::TranslationX) != 0)
	constraintSettings.MakeFixedAxis(JPH::SixDOFConstraintSettings::TranslationX);

if ((m_LockedAxes & EActorAxis::TranslationY) != 0)
	constraintSettings.MakeFixedAxis(JPH::SixDOFConstraintSettings::TranslationY);

if ((m_LockedAxes & EActorAxis::TranslationZ) != 0)
	constraintSettings.MakeFixedAxis(JPH::SixDOFConstraintSettings::TranslationZ);

if ((m_LockedAxes & EActorAxis::RotationX) != 0)
	constraintSettings.MakeFixedAxis(JPH::SixDOFConstraintSettings::RotationX);

if ((m_LockedAxes & EActorAxis::RotationY) != 0)
	constraintSettings.MakeFixedAxis(JPH::SixDOFConstraintSettings::RotationY);

if ((m_LockedAxes & EActorAxis::RotationZ) != 0)
	constraintSettings.MakeFixedAxis(JPH::SixDOFConstraintSettings::RotationZ);

m_AxisLockConstraint = (JPH::SixDOFConstraint*)constraintSettings.Create(JPH::Body::sFixedToWorld, body);

JoltScene::GetJoltSystem().AddConstraint(m_AxisLockConstraint);
```
The only issue I'm running into is that if the body I'm trying to constrain is offset from the world origin (or I guess the position of JPH::Body::sFixedToWorld) the body will be snapped back to that position.
Is there a way around this while still using `JPH::Body::sFixedToWorld` or would I have to create a new static body at the position of the body I want to constrain in order to achieve this?

**Comment by jrouwe** [comment]
If you set ```constraintSettings.mSpace = JPH::EConstraintSpace::LocalToBodyCOM;``` you should also fill in ```constraintSettings.mPosition1``` and ```constraintSettings.mPosition2```. By default these are zero, so now you're attaching the center of mass of ```body``` to the origin. If you set ```constraintSettings.mPosition1 = body.GetCenterOfMassPosition();``` then it should work (assuming you've already set ```body``` to its initial position).

**Comment by peter1745** [comment]
> If you set `constraintSettings.mSpace = JPH::EConstraintSpace::LocalToBodyCOM;` you should also fill in `constraintSettings.mPosition1` and `constraintSettings.mPosition2`. By default these are zero, so now you're attaching the center of mass of `body` to the origin. If you set `constraintSettings.mPosition1 = body.GetCenterOfMassPosition();` then it should work (assuming you've already set `body` to its initial position).

Alright I'll give that a try, really appreciate all the help with this issue, from both you and @mihe, really loving Jolt by the way!

**Comment by peter1745** [comment]
Is there a way to achieve the same behavior for rotation? I've been playing around with `mAxisX1` and `mAxisY1`, and I can get close but it ends up behaving strangely at times.
Sorry for the constant questions, I've still relatively new to manually configuring joints, and since I'm coming from PhysX where this is done differently I'm sort of out of my depth here 😅

**Comment by jrouwe** [comment]
Sorry, my previous solution did indeed not handle rotation locking. I'm assuming you want to lock the body using the world space X, Y and Z axis (and not the local body space axis)? I think the simplest solution then would be to remove: ```constraintSettings.mSpace = JPH::EConstraintSpace::LocalToBodyCOM``` (meaning you will configure the constraint in world space) and then doing ```constraintSettings.mPosition1 = constraintSettings.mPosition2 = body.GetCenterOfMassPosition();```

**Comment by peter1745** [comment]
Yup that works perfectly, thank you so much for all the help, I really appreciate it!
