### ISSUE TITLE
MeshShapeSettings::Sanitize() is slow (quadratic complexity)

### ISSUE THREAD

**Issue by Ono-Sendai** [jrouwe/JoltPhysics#365]
I have a mesh where MeshShapeSettings::Sanitize() is running extremely slowly.
The problem is std::vector::erase is linear time on the number of items following the item to be erased, and t is much smaller than mIndexedTriangles.size().

You could just copy the valid triangles to a new array, instead of erasing the invalid ones.

(Also std::unordered_set is pretty slow, there are faster hash tables around)

**Comment by jrouwe** [comment]
I was assuming that duplicate/degenerate triangles were an exception case so that it didn't really matter. Do you have many degenerate/duplicate triangles?

I think a simple fix could be to move the last triangle into position t and then pop the last element. The triangles will be reordered later anyway. (I will try that out)

**Comment by jrouwe** [comment]
Does #367 fix it? (I'm aware that there are faster hash sets but I'm trying not to pull in third party libraries)

**Comment by Ono-Sendai** [comment]
Yes that is a big improvement, thank you.

Previously:
LoadModelTask: loading mesh with URL 'Valhalla_gltf_10539081704724699996_lod1_bmesh_11504516953187057336.bmesh'.
JPH::MeshShapeSettings took 61.3003 s

with patch:
LoadModelTask: loading mesh with URL 'Valhalla_gltf_10539081704724699996_lod1_bmesh_11504516953187057336.bmesh'.
JPH::MeshShapeSettings took 0.0494 s


As for the mesh:
mIndexedTriangles = { size=438934 }
After Sanitize():
mIndexedTriangles = { size=286588 }

**Comment by jrouwe** [comment]
Ok, thanks for confirming!
