### ISSUE TITLE
Memory Leak Detection Triggering

### ISSUE THREAD

**Issue by BobbyAnguelov** [jrouwe/JoltPhysics#454]
Hi, 

I'm currently integrating Jolt into my hobby engine (so prepare for a bunch of issues 😅) and jolt is currently triggering my memory leak detection.

You currently have the "RegisterTypes" function which is registering types with the factory and creating a default physics material but since you don't provide a "UnregisterTypes" function, you only clean up the created material instance at program exit via the static reference destruction. This now occurs after the shutdown of my allocator and so I detect a leak. 

Could you provide a "UnregisterTypes" function that could do the following (and anything else needed) and so clean everything up at a user specified time.

```cpp
JPH::PhysicsMaterial::sDefault = nullptr;
JPH::Factory::sInstance->Clear();
```

**Comment by jrouwe** [comment]
Sure, no problem. But I think that what you're doing is correct (I don't think there are any other allocations).

**Comment by BobbyAnguelov** [comment]
For now yes, but perhaps in the future as the lib evolves things might change and it will be easier on users to not have to manually go in and figure out what they need to clean up if something does change. Having a symmetrical API is generally easier for integrating libs, as from the user's side, they shouldn't need to care what the RegisterTypes function is internally doing and how it might change between versions.
