### ISSUE TITLE
Unable to use existing dispatch functions for custom convex shapes

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#467]
As mentioned briefly in #465 I'm attempting to implement Godot's [`SeparationRayShape3D`](https://docs.godotengine.org/en/4.0/classes/class_separationrayshape3d.html) as a custom convex shape, and while the "collide shape function" of this custom shape is implemented as just a `CastRay` call on the other shape, I was hoping to utilize the existing `sCastConvexVs...` functions for the "cast shape function" part of it, since I don't really know how else to implement it. These are however all `private` and are only registered by default for `sConvexSubShapeTypes` which doesn't include any of the user types.

I would have made a PR, but I wasn't sure what the preferred approach would be, since I guess it could be solved in multiple ways. Either by just making them `public`, or by allowing the ability to fetch the `CollideShape` and `CastShape` functions from `CollisionDispatch`, or perhaps by reserving some user types as convex user types, allowing them to be included in `sConvexSubShapeTypes`.

**Comment by jrouwe** [comment]
Interesting shape... What is the cast shape supposed to do in this case? Cast a line segment through the world? 

I guess you were planning to implement a new type of ConvexShape that just returns the 2 points of the line segment in the Support::GetSupport function and 0 as convex radius?

In that case I would prefer to add UserConvex1 .. 8 in EShapeSubType and add them to sAllSubShapeTypes, sConvexSubShapeTypes and sSubShapeTypeNames.

**Comment by jrouwe** [comment]
(I can add that if you want or you can send me a PR)

**Comment by mihe** [comment]
> Interesting shape... What is the cast shape supposed to do in this case? Cast a line segment through the world?

Basically, yeah. As far as I can tell, it's meant to serve as a lightweight shape for certain types of character controllers. A bit unorthodox perhaps, but so is a lot of stuff in Godot. :)

> I guess you were planning to implement a new type of ConvexShape that just returns the 2 points of the line segment in the Support::GetSupport function and 0 as convex radius?

Yes, exactly. Much like [their Bullet implementation](https://github.com/godotengine/godot/blob/1a4ef34d501c63dd20d067e35590e28bd712c98a/modules/bullet/btRayShape.cpp#L69-L75) of it, I figured I would have `GetSupport` return either the end or start of the ray depending on the direction. As for the convex radius, I did indeed just leave that at 0 for now and simply ignored `ConvexShape::ESupportMode` in `GetSupportFunction`, which I wasn't entirely sure was correct, but I'll assume it is then.

> I can add that if you want or you can send me a PR

I'd be happy to make a PR. Expect one soon. :)

**Comment by jrouwe** [comment]
Thanks for the PR!

>  I figured I would have GetSupport return either the end or start of the ray depending on the direction. As for the convex radius, I did indeed just leave that at 0 for now and simply ignored ConvexShape::ESupportMode in GetSupportFunction, which I wasn't entirely sure was correct, but I'll assume it is then.

Yes that's correct.

Jorrit.
