### ISSUE TITLE
VS2022 - Clang build error "The CXX compiler identification is unknown"

### ISSUE THREAD

**Issue by Veloctor** [jrouwe/JoltPhysics#480]
![image](https://user-images.githubusercontent.com/55224044/227747438-127ea0c3-9e23-4fef-9f6a-ef753cd7a44a.png)

![image](https://user-images.githubusercontent.com/55224044/227747403-48bed3ff-9ba3-4278-ac7f-b3cbb649b1cd.png)
I'm not sure I have "C++ Clang-cl for v143+ build tools (x64/x86)" component, these are all things about clang in the installer, and I do have v143 x64/x86 build tool (latest) component.
So I'm not very sure I have no operation mistake, but now I have no idea about this

[CMakeOutput.log](https://github.com/jrouwe/JoltPhysics/files/11070444/CMakeOutput.log)
(I'm not sure if this is useful)

**Comment by Veloctor** [comment]
I found a ugly workaround after a lot of tries:
in developer powershell, run command 
> vcpkg integrate remove

to remove vcpkg integration.
Then, in the build bat script, add a parameter for cmake command: 

> -DCMAKE_CXX_COMPILER={your Clang CL compiler}

to specify the C++ compiler for cmake.
For example, I edited Build\cmake_vs2022_clang_double.bat the cmake command to this:

> cmake -S . -B VS2022_Clang_Double -G "Visual Studio 17 2022" -A x64 -T ClangCL -DCMAKE_CXX_COMPILER="G:\\Visual Studio 2022\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe" -DDOUBLE_PRECISION=YES %*

This used a absolute path to my clang-cl.exe, so it's not automated, seems a little ugly. Maybe there's some way to reference the VS2022 relative path, but I'm not familiar with Cmake, and the problem is solved for me, so I leave this generalization improvement to the author.

**Comment by jrouwe** [comment]
Hello,

I have exactly the same installed as you:

![image](https://user-images.githubusercontent.com/1621693/227768505-305ff7c9-e5e8-4d4d-854b-6f66e446882a.png)

It looks like you're using the 'cmake' version that comes with MSVC while I downloaded cmake from cmake.org, so I have:

```
cmake --version
cmake version 3.26.1
```

But I just tried creating the project using MSVC's cmake.exe and that works fine for me too. I've been using vcpkg too, so I really have no idea what's different for you. Perhaps you can try downloading cmake from cmake.org?

**Comment by Veloctor** [comment]
> But I just tried creating the project using MSVC's cmake.exe and that works fine for me too. I've been using vcpkg too, so I really have no idea what's different for you. Perhaps you can try downloading cmake from cmake.org?

I tried that, build successful without workaround. That's strange, what's the difference?

**Comment by Veloctor** [comment]
Hi @jrouwe , I did not resolve this problem compeletely. I `vcpkg integrate install` again, and the problem appeared again, even with the cmake.org official cmake. 6 hours ago, I did not reintegrate vcpkg, so the workaround still exists, and actually 

> -DCMAKE_CXX_COMPILER={your Clang CL compiler}

doesn't make sense. I removed vcpkg integrate again, and uninstalled the official cmake, then use the VS cmake, the build still works. I'm sorry I didn't find the root of the problem yesterday. Fortunately, this project does not use vcpkg, and I searched along this clue, then found this: https://github.com/microsoft/vcpkg/issues/15623 so maybe it's a bug of vcpkg. I'm a little curious about why you can do it with vcpkg, but it's not that important now.
