### ISSUE TITLE
Constrained body pass through other bodies without affecting them

### ISSUE THREAD

**Issue by SirLynix** [jrouwe/JoltPhysics#486]
Hi!

I'm currently trying to integrate Jolt into my [engine](https://github.com/NazaraEngine/NazaraEngine) and comparing it to Bullet Physics. Jolt is quite faster but I'm having weird results when trying to smash a grabbed body (constrained by a PointConstraint to the world and moving its first point).

Here's what I get with Bullet Physics:

https://user-images.githubusercontent.com/3002461/228820218-a8782784-88f5-496f-8e61-a452160c1f96.mp4

which is quite what I was expecting.

And now with Jolt:

https://user-images.githubusercontent.com/3002461/228820455-14fcb7ff-acdb-4c07-81f9-1347044a5c71.mp4

Body is moving through walls (box colliders) as if there was nothing, which is understandable as there's a big force vs a relatively thing object (same happens with Bullet, although with more effort).

However when I move the body into the pool, bodies don't really care, it just passes through them. (although they are active).

In both Bullet & Jolt simulations, step size is fixed to 1/30 with only one collision step (substep) allowed.

I'm probably missing something in Jolt setup.

Although there's quite a lot of it, here's the code (please understand it's a big WIP 😅 ) of the [example](https://github.com/NazaraEngine/NazaraEngine/blob/joltphysics/examples/PhysicsPlayground/main.cpp) and the [Jolt binding classes](https://github.com/NazaraEngine/NazaraEngine/tree/joltphysics/src/Nazara/JoltPhysics3D), in case it's required.

**Comment by jrouwe** [comment]
I haven't looked at your code yet but I'm guessing this is the same as:

https://github.com/jrouwe/JoltPhysics/discussions/268

**Comment by SirLynix** [comment]
It looks very similar to that discussion Indeed, thank you for the quick answer!

**Comment by SirLynix** [comment]
Side question, wouldn't it be interesting to be able to change the attachment points on a DistanceConstraint at runtime, as it's the case for PointConstraint?

**Comment by SirLynix** [comment]
I finally managed to take the time to implement this using a distance constraint (to a kinematic body moving with the mouse), here's the result:
https://user-images.githubusercontent.com/3002461/229996349-c012d2f2-282d-416e-b089-282beea8331e.mp4

Thank you for your help and for this awesome piece of product, Jolt may not be the easiest physics engine I've ever used (but its doc helped a lot) but I can tell it's already a very good library.

I have an un-related question, am I right to think that body locking is only useful either when accessing bodies from multiple threads (outside of a physics step) or when a physics step is currently running (so inside Jolt callbacks)?

And so that it's safe to keep and use a JPH::Body pointer (or use a no-lock body interface) as long as I use it on a single thread and outside of Jolt callbacks?

**Comment by jrouwe** [comment]
> Jolt may not be the easiest physics engine I've ever used (but its doc helped a lot) but I can tell it's already a very good library.

If you have problems that you ran in to that should have been documented or APIs that are unintuitive then let me know. I'm so used to the thing now that I cannot see strange quirks anymore.

> I have an un-related question, am I right to think that body locking is only useful either when accessing bodies from multiple threads (outside of a physics step) or when a physics step is currently running (so inside Jolt callbacks)?

When you access bodies from a single thread you don't need locking, but only if you're not accessing the physics system while its stepping.

Inside the physics step all bodies are locked, so locking a body inside a callback is likely to result in a deadlock. I looked through all listeners and I think they all specified what you can and cannot do (I just submitted 1 comment where it was missing). Let me know if it is not clear for any of the callbacks.

> And so that it's safe to keep and use a JPH::Body pointer (or use a no-lock body interface) as long as I use it on a single thread and outside of Jolt callbacks?

Correct

**Comment by SirLynix** [comment]
https://nazara.digitalpulse.software/demo/PhysicsPlayground.html

Got it working 😁 (and quickly compiled to web using emscripten)

**Comment by jrouwe** [comment]
Very cool!
