### ISSUE TITLE
Elongated capsules and cylinders behave strangely

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#487]
Something strange is going with capsules and cylinders when under the influence of some angular velocity.

If you replace `CapsuleShapeTest::Initialize` with this:

```cpp
void CapsuleShapeTest::Initialize() 
{
	CreateFloor();
		
	BodyCreationSettings capsule(new CapsuleShape(10.0f, 1.0f), RVec3(0, 11, -10), Quat::sEulerAngles(Vec3(0, 0, DegreesToRadians(10))), EMotionType::Dynamic, Layers::MOVING);
	capsule.mAngularVelocity = Vec3(0, JPH_PI, 0);

	BodyCreationSettings cylinder(new CylinderShape(10.0f, 1.0f), RVec3(0, 11, 10), Quat::sEulerAngles(Vec3(0, 0, DegreesToRadians(10))), EMotionType::Dynamic, Layers::MOVING);
	cylinder.mAngularVelocity = Vec3(0, JPH_PI, 0);

	mBodyInterface->CreateAndAddBody(capsule, EActivation::Activate);
	mBodyInterface->CreateAndAddBody(cylinder, EActivation::Activate);
}
```

You get something that looks like this:

https://user-images.githubusercontent.com/4884246/228952091-b1d36120-83ee-45c2-b30c-ba336e47a924.mp4

I feel like the test is simple enough that there's not much room for me to screw things up, but I'd be curious to hear your thoughts.

Any idea what might be causing it?

**Comment by jrouwe** [comment]
It does look a bit weird. What does it look like in Godot physics?

**Comment by mihe** [comment]
Well, that's what I get for messing with the test after comparing the two.

I had originally compared the two with different (much smaller) dimensions and no initial angular velocity, and instead just let the fall itself impart some angular velocity on them, and in that particular case Godot Physics would just fall down without much fuzz, but it does seem like Godot Physics exhibits similar behavior when using the same parameters as the test I pasted earlier.

Here's what that looks like:

https://user-images.githubusercontent.com/4884246/228958574-d5eb6db9-3420-4640-b4da-d77048c7356f.mp4

That certainly looks very strange either way, but I guess I'll just chalk it up to game physics being an approximation of, or perhaps I'm the one becoming out-of-touch with reality. :)

What do you think, could the planets have aligned and caused the same bug in two separate engines, or is it just how it's meant to behave?

**Comment by mihe** [comment]
I decided to fire up Unity (PhysX) as well. I'm not very well-versed with their editor, but here's my attempt anyway:

https://user-images.githubusercontent.com/4884246/228967248-77d82b16-f27e-4f37-91cd-d1175838e277.mp4

While the bobbing up and down isn't as pronounced there it obviously has the same sort of desire to stay somewhat upright, which I guess must be some sort of gyroscopic effect?

Anyway, clearly Jolt is not an outlier with regards to this, so I'll go ahead and close this.

Apologies for the noise.
