### ISSUE TITLE
Materials, restitution, friction

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#49]
I'm a bit surprised to see that restitution and friction are set on bodies. I was expecting those to be material parameters or at least to be per shape. As far as I can see, materials are purely a way to attach (shared) user data to shapes.

In our engine we have materials that define the behavior of surfaces, e.g. which sounds and particle effects to use for interactions, and we also edit restitution and friction there, since it makes sense. This way we create e.g. "ice" and "stone" materials and define all their physical behavior once (rendering properties are defined somewhere else, so that physical properties can be shared across many materials).
That means I can build a compound object with one shape made of ice and one shape made of stone. With PhysX those shapes would also slide and bounce accordingly, in Jolt I would currently need to somehow give the whole body one restitution and friction value.

Granted, this is a rare use case and I can understand that from a performance and memory perspective you neither want to store these values per shape, nor want to do another memory fetch into the material for every contact. Still, wanted to point out that this is a bit unexpected and that the name "PhysicsMaterial" conveys something more to me than being just for custom data.

**Comment by jrouwe** [comment]
Hello,

You're right that out of the box Jolt doesn't support friction and restitution per shape / triangle for performance reasons, but you can easily implement this without modifying Jolt.

You can create your own ContactListener and override OnContactAdded and OnContactPersisted. Both functions provide you with 2 bodies, a contact manifold (which contains 2 sub shape IDs) and an output parameter of type ContactSettings.

The bodies contain a pointer to the shape and you can call Shape::GetMaterial(sub shape id) to get to the material of both contact points. Cast this to your custom material type that contains a friction and restitution and combine them from both bodies (see ContactConstraintManager mCombineFriction/Restitution). Finally output the results in the ContactSettings struct. On input this will contain the combined settings from the body and you're free to override it.

I will create an example for this as I think there will be more people interested in this.

Regards,

Jorrit.
