### ISSUE TITLE
Shifting center of mass of a body (adding sub shapes to mutable compound) moves attached constraint pivot

### ISSUE THREAD

**Issue by attilaz** [jrouwe/JoltPhysics#492]
We have a body with a mutable compound shape which is connected to another body with hinge joint, for example a door. When we add or remove a sub shape to the compound it shifts its COM. The attached constraint position is also shifted since it's in Body COM space.  So the door moves and its not in correct position anymore.

Can You help with this issue? How should we update the constraint positions?

**Comment by jrouwe** [comment]
If you are using a mutable compound shape, you can also choose not to shift the COM (by simply not calling AdjustCenterOfMass). If you do adjust the center of mass then currently the only way to update the constraint is to delete it and re-create it. It would be possible to create a function similar to BodyInterface::NotifyShapeChanged to adjust the constraint but I never encountered this situation so far so that's why it doesn't exist.

**Comment by attilaz** [comment]
Hello, thank you for your answer. 
Our use case is a car's chassis which is a mutable compound shape. When we add or remove parts, for example a bumper or a wing it's added or removed from the mutable compound which need to shift the car's COM. When we have the doors open and flapping (using a hinge joint), the doors pivot shifts on chassis shape change.
Recreating the joint seems more complicated and may lose joint's current state. 
We made a workaround by adding a function to TwoBodyConstraint that shifts the joint's pivot based on chassis' COM change, so joint pivot stays in same place in COM relative space.

**Comment by jrouwe** [comment]
Did you create a fork with this new code? (I'd like to take a look an possibly merge it / implement something similar)

**Comment by attilaz** [comment]
We have only added a function to TwoBodyConstraints to shift mLocalSpacePosition1 and mLocalSpacePosition2 by a vector. 
Our game logic calls this on car part assembly after calculating COM change of vehicle. This keeps the joint pivot in place relative to Body space no matter where the COM goes.

**Comment by jrouwe** [comment]
I've added an official way to do this.

**Comment by attilaz** [comment]
Thank you.
