### ISSUE TITLE
Prefer `aligned_alloc` over `std::aligned_alloc` in `Memory.cpp`

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [jrouwe/JoltPhysics#514]
Mostly just what it says on the tin.

I have encountered quite a few scenarios where `aligned_alloc` will be defined where `std::aligned_alloc` isn't. Older versions of macOS, Switchbrew's C++ environment and Android f.e.

Given that removing the `std::` doesn't actually change anything behaviour-wise it would be nice if this could be changed.

Thanks!

**Comment by jrouwe** [comment]
Hello, I'm not against this, but std:: aligned_alloc is part of the C++17 standaard and with the exception of Android (which apparently ignores the compiler option to switch to C++17 for older ndk versions and already has a separate code path in Jolt). Are you sure you're compiling for C++17? (There are more C++17 features used in Jolt). I can't find any evidence online that it is not implemented for certain C++17 conformant compilers.

**Comment by jrouwe** [comment]
Which version of clang are you using in both cases? And are you sure you're using ```-std=c++17```? I need to go back to clang 6 in [godbolt](https://godbolt.org/z/eW3nEWeKz) in order for std::aligned_alloc not to exist (which is an ancient compiler from 2018).

B.t.w. I'm not able to properly test changes for the next 2 weeks, so I can't change it right now.

**Comment by Th3T3chn0G1t** [comment]
I mean the compiler version doesn't matter it's a stdlib feature, provided that the compiler defines a sufficiently recent `__cplusplus`. But nonetheless it's clang-12 or clang-15 for the macOS situation and Switchbrew respectively.

The issue is moreover Apple's staggered libcxx releases/downstreaming meaning older versions lacking an upgrade path can end up with partial implementations from whenever support ended.

**Comment by jrouwe** [comment]
Ok, I'll change it, but as said I cannot properly test changes right now.

**Comment by Th3T3chn0G1t** [comment]
Coolio - thanks and sorry for the inconvenience!
