### ISSUE TITLE
Contact modification

### ISSUE THREAD

**Issue by bvigario** [jrouwe/JoltPhysics#516]
Is it possible to modify contact data such as impulses and contact normals? The idea is to simulate a conveyor belt.

**Comment by jrouwe** [comment]
See also #531

**Comment by SirLynix** [comment]
I second this feature request, it would be great to be able to have more control on contacts.

**Comment by fredUmlaut** [comment]
Contact modification would be a great addition.

Perhaps contacts could even contain an 'external velocity' field.
That would apply the 'external' velocity from a moving platform to a body that rests on it, but WITHOUT adding inertia.

This would solve many game play issues where you don't want external velocities to add up on 
non kinematic bodies (imagine stuff riding on a train etc.) but just move them around in a non physical way.

**Comment by jrouwe** [comment]
Got a prototype working...

https://github.com/jrouwe/JoltPhysics/assets/1621693/08a7df9c-ad80-421c-9b8a-b2858457b7c2

(friction of boxes goes from 1 to 0 from left to right)

This is what the code that does it looks like:

```
void ConveyorBeltTest::OnContactAdded(const Body &inBody1, const Body &inBody2, const ContactManifold &inManifold, ContactSettings &ioSettings)
{
	// Body 1 should always be the belt because we create it before the other bodies so their ID will be lower
	BodyIDVector::const_iterator iterator = std::find(mBelts.begin(), mBelts.end(), inBody1.GetID());
	if (iterator != mBelts.end())
	{
		// Get the tangents of the contact manifold
		Vec3 tangent1, tangent2;
		inManifold.GetTangents(tangent1, tangent2);

		// Take the tangents to local space relative to body 1
		Quat world_to_body1 = inBody1.GetRotation().Conjugated();
		tangent1 = world_to_body1 * tangent1;
		tangent2 = world_to_body1 * tangent2;

		// We always move the body along our Z axis
		const Vec3 cLocalSpaceVelocity(0, 0, 10.0f);
		ioSettings.mTangentFrictionBias1 = tangent1.Dot(cLocalSpaceVelocity);
		ioSettings.mTangentFrictionBias2 = tangent2.Dot(cLocalSpaceVelocity);
	}
}
```
