### ISSUE TITLE
Calculating depenetration normal and depth for meshes

### ISSUE THREAD

**Issue by BobbyAnguelov** [jrouwe/JoltPhysics#529]
![image](https://github.com/jrouwe/JoltPhysics/assets/10767490/4726304e-8a81-47bb-ac23-9db52579de2c)

I'm having a fair amount of trouble trying to get a valid depenetration axis/normal from jolt when it comes to colliding with meshes. 

In the above screenshot, jolt seems to behave as expected against a box collision but as soon as you try to cast against a mesh it doesnt seem to be able to resolve initial overlaps.

I was wondering if it's not related to the depth of the initial penetration since this kinda seems to work: 
![image](https://github.com/jrouwe/JoltPhysics/assets/10767490/635764c8-dfd9-4b66-bfad-e3a313308894)

But then if you go a tiny bit deeper then it breaks again:

![image](https://github.com/jrouwe/JoltPhysics/assets/10767490/82ca3298-c0b3-4508-b995-90f2a32534bc)

Doing the same thing with PhysX behaves as expected, though it is necessary to run a subsequent geometry query once the initial overlap is detected to calculate the depenetration. I don't see any equivalent API in Jolt.

Is this expected to work? If so what might I be doing wrong?

**Comment by jrouwe** [comment]
Hello,

I need a bit more context. What am I looking at? What do the various colors mean?

Is your example using CharacterVirtual or are you doing a collision test and if so what test and how do you 'resolve' your collision?

(and if it doens't take too much time, can you illusutrate your problem in the Samples app or perhaps just a code snippet of what you're doing?)

**Comment by BobbyAnguelov** [comment]
Sorry, here's more detail.

The red shape is the starting position of a basic shapecast with a capsule shape:

`NarrowPhaseQuery const& NPQ = m_pWorldState->m_physicsSystem.GetNarrowPhaseQuery();
        NPQ.CastShape( shapeCast, scs, Vec3::sZero(), collector, Jolt::BroadPhaseLayerFilter( rules ), Jolt::ObjectLayerFilter( rules ), Jolt::BodyFilter( rules ) );`
        
The white shape is the result of applying the "depenetration" distance along the penetration returned by the closest hit:

`-inResult.mPenetrationAxis.Normalized() * inResult.mPenetrationDepth`

The cast collector simply keeps the closest hit and updates the early out fraction.

`virtual void AddHit( ShapeCastResult const& inResult ) override
        {
            FillHitDetailsToResults( inResult, m_results.m_hits.empty() ? m_results.m_hits.emplace_back() : m_results.m_hits.front() );
            UpdateEarlyOutFraction( inResult.mFraction );
        }`

This is the most basic cast query, there's absolutely nothing fancy going on. I've added a video to show the results of the sweep against a box collision and against a mesh, the mesh has some detailed geo but is generally a relatively simple mesh.

https://github.com/jrouwe/JoltPhysics/assets/10767490/3f553391-b2d0-4fe8-b156-82cc2d60318f

**Comment by jrouwe** [comment]
What settings are you using in your variable ```scs```? Do you have ```scs.mReturnDeepestPoint = true``` (if not Jolt does not try to get the deepest point when the shape intersects at fraction = 0). 

You say you are sorting on closest hit, how are you doing this? If you sort on mFraction then you won't get the correct result as in this example all your hits will return mFraction = 0 so you will not sort on the deepest hit. You need to sort on ```inResult.GetEarlyOutFraction()``` instead.

There are two other settings that affect normal calculation ```mActiveEdgeMode``` and ```mUseShrunkenShapeAndConvexRadius``` but I would suggest looking at the two things above first.

**Comment by BobbyAnguelov** [comment]
I was already using the mReturnDeepestPoint set to true. I changed the sort to use this:

```cpp
virtual void AddHit( ShapeCastResult const& inResult ) override
{
    if ( inResult.GetEarlyOutFraction() < GetEarlyOutFraction() )
    {
       FillHitDetailsToResults( inResult, m_results.m_hits.empty() ? m_results.m_hits.emplace_back() : m_results.m_hits.front() );
       UpdateEarlyOutFraction( inResult.GetEarlyOutFraction() );
    }
}
```

There's no difference in the end result. It's still behaving exactly the same as before.

I tried setting the active edge mode to "CollideWithAll" with no luck. Also tried enabling "mUseShrunkenShapeAndConvexRadius" which also had no effect.

Would you like the mesh for that crate so you can try it on your end?

**Comment by jrouwe** [comment]
Yes please!

**Comment by BobbyAnguelov** [comment]
Actually looking at the code, something is not clear to me:

Is penetration depth a distance or a fraction? You are returning it as the "early out fraction" in a couple of places but the comment implies that it's a distance: "Penetration depth (move shape 2 by this distance to resolve the collision)"

Here's the zipped FBX for the crate:
[SM_Prop_Crate_Large_01.zip](https://github.com/jrouwe/JoltPhysics/files/11472347/SM_Prop_Crate_Large_01.zip)

**Comment by jrouwe** [comment]
> Is penetration depth a distance or a fraction

ShapeCastResult::mPenetrationDepth is a distance in meters
ShapeCastResult::mFraction is a fraction along the sweep when there is collision (should be 0 in your case)

The early out fraction doesn't have any physical meaning, it's only used for sorting. The way I'm using it for the early out fraction is that <0, 1] means the shape did not intersect initially so there is a valid fraction to move. [-INF, 0> indicates that there was an intersection at fraction = 0 and I'm using -penetration_depth to make sure that the deepest hit has the lowest value (so would be sorted first if you sort on early out fraction).

**Comment by jrouwe** [comment]
I can reproduce the issue (won't have time for a fix today). The workaround fix would be to, as soon as you detect that there is a collision at fraction = 0, abort the cast (call ```ForceEarlyOut()```) and then do a follow up ```CollideShape``` call to get a proper mPenetrationDepth and mPenetrationAxis and shift the capsule by ```-mPenetrationDepth * mPenetrationAxis.Normalized()``` to move it out of collision.

**Comment by BobbyAnguelov** [comment]
So I tried your workaround but it doesn't seem to work consistently. It occasionally results in the correct depenetration axis and depth but it's unfortunately also just as often wrong as it is right. See the video before, the white shape (the result of the depenetration often ends up making the penetration worse).

https://github.com/jrouwe/JoltPhysics/assets/10767490/ef100bf1-d36c-48f8-b12e-adef380c6bff

Just to verify I'm doing the right thing as you suggested:

1. If a hit in the cast hit collector has a fraction of 0 - "inResult.GetEarlyOutFraction() == 0.0f" then call "ForceEarlyOut" and return
2. Then call "CollideShape" with the same shape and the COM transform being the same as the start of the cast operation
3. Find the deepest penetration depth and use that penetration axis and depth to resolve the overlap

If that's the correct set of operations, this is the result I get...

**Comment by jrouwe** [comment]
Hello,

I found a bug in the early out logic of CastShape that led to not finding the deepest hit. I need to come up with a proper solution so it will take a bit more time.

> If a hit in the cast hit collector has a fraction of 0 - "inResult.GetEarlyOutFraction() == 0.0f"

This should be inResult.mFraction == 0.0f as the early out fraction can become negative (I don't think it will really affect the output in your video though).

> I get like 40ish collide results - should I be concatenating them in some way

You get 1 collision result per triangle that collides (unless you early out). The penetration depth will be for that triangle as well. You can come up with a case where just taking the deepest penetration will not actually move you out of the entire object, e.g. imagine a capsule with a triangle on both sides. The triangle on the left is slightly embedded, the triangle on the right a bit more. The deepest penetrating triangle would be the right one and moving the shape to the left to get out of the right triangle will push you into the left triangle. I don't think you can solve this problem for an arbitrary mesh shape, I think you need some heuristics. For closed / convex-ish meshes  moving along the deepest penetration works reasonably well.

I can't fully judge from your video, but it appears that the white capsule is not actually penetrating the box. It is just jumping around as the triangle that provides the biggest penetration changes.

**Comment by BobbyAnguelov** [comment]
>This should be inResult.mFraction == 0.0f 

I tried both, didn't see to make any difference in the output.

> but it appears that the white capsule is not actually penetrating the box

It is fully penetrating the box, I swung the camera around to try to highlight that issue but I agree with the depth test disabled for the debug drawing it's hard to tell.

It would be interesting to compare to what physics does with their geometry queries, in my experience they've been able to reliably solve this problem for arbitrary mesh shapes. 

I think for now I'll just wait for a fix to the cast. Thanks!

**Comment by jrouwe** [comment]
I just submitted #534 to fix the early out bug.

Before it looked like this:

https://github.com/jrouwe/JoltPhysics/assets/1621693/8c6e6c57-ba4a-4159-8549-4561048b6e91

And now it looks like this:

https://github.com/jrouwe/JoltPhysics/assets/1621693/54d4885c-f989-4630-9878-e126a0a6d1e7

This is the code I'm using for this demo (just copy it over the existing files):

[MeshShapeTest.zip](https://github.com/jrouwe/JoltPhysics/files/11507383/MeshShapeTest.zip)

If you embed the capsule deeper into the crate then moving back along deepest penetration is not guaranteed to get you out of collision for the reasons described above. I'll create a follow up post with more info on that.

**Comment by BobbyAnguelov** [comment]
Thanks! 

I looked a bit more into what Physx is doing and it's an iterative solver thats used to calculate the depenetration against meshes. That explains the accuracy they have for that scenario. I realize that the way I'm working with physics, I'm kinda abusing that mechanism for certain things.

**Comment by BobbyAnguelov** [comment]
Yeh, it's all good thanks!
