### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by amerkoleci** [jrouwe/JoltPhysics#53]
Hi,
I just integrated Jolt in my game engine (https://github.com/amerkoleci/alimer), currently my CI build using linux fails, I saw that MSVC and CLang 10.0 is only supported, any plans for GCC? Emscripten?

Keep up the good job and thanks for all hard job.

**Comment by jrouwe** [comment]
Thank you!

I'm not planning to support emscripten (I'm not really interested in web games), but I can take a look at gcc (should be quite simple to support that and it may catch a coding error or two that clang doesn't).

**Comment by jrouwe** [comment]
Support for emscripten was added a couple of weeks ago, this project uses it: https://github.com/jrouwe/JoltPhysics.js

**Comment by amerkoleci** [comment]
Nice job, as always, thank you!
