### ISSUE TITLE
WASM: Memory access out of bounds when enabling double precision

### ISSUE THREAD

**Issue by Myrindd** [jrouwe/JoltPhysics#542]
I am trying to compile the Jolt as a shared library for WASM using emscripten. This works fine unless I enable double precision in cmakelist, which causes a "memory access out of bounds" error when creating a body using BodyInterface. This also happens for helloworld.h.
I have created an issue in the JoltPhysics.js repository as well ([link](https://github.com/jrouwe/JoltPhysics.js/issues/10)).

**Comment by jrouwe** [comment]
Let's not create duplicate tickets pls.
