### ISSUE TITLE
Build Error on Linux

### ISSUE THREAD

**Issue by daniilpetrov** [jrouwe/JoltPhysics#557]
I cannot compile the library for Linux, the following error appears:
«uint64» was not declared in this scope; did you mean «uint»
64 bit OS: Manjaro Linux

**Comment by jrouwe** [comment]
It would help if you pasted the full error including file and line numbers, but I'm guessing that this is triggered by compiling one of your own cpp files and forgetting to #include <Jolt/Jolt.h> before any other Jolt include. All of the cpp files in Jolt itself include Jolt.h which includes Core.h which defines uint64.

**Comment by daniilpetrov** [comment]
I enclose the full compiler output: [Building JoltPhysics-3.0.1 on Manjaro Linux.txt](https://github.com/jrouwe/JoltPhysics/files/11669230/Building.JoltPhysics-3.0.1.on.Manjaro.Linux.txt)

**Comment by jrouwe** [comment]
I think I see what the issue is, can you try out #558?

**Comment by daniilpetrov** [comment]
Yes, thank you, it helped!
