### ISSUE TITLE
A friction issue

### ISSUE THREAD

**Issue by Pierre-Terdiman** [jrouwe/JoltPhysics#56]
Any idea why the object "slides" and doesn't move with Jolt? Increasing the friction didn't work. Do you know if there is a solver parameter somewhere that I can tweak maybe?

https://www.youtube.com/watch?v=kOtn1sdNxuw

I know it's not an easy scene to repro so if you don't immediately know what the problem is I'll try to finish my PEEL integration and put all that on Github.

**Comment by jrouwe** [comment]
The function to combine friction can be overridden with PhysicsSystem::SetCombineFriction. The default function is sqrt(friction1 * friction2). Maybe one of the objects has friction 0 and you have a different combining function?

**Comment by Pierre-Terdiman** [comment]
That was it, thanks.
