### ISSUE TITLE
Compound shapes made up of spheres don't always collide at all

### ISSUE THREAD

**Issue by hhyyrylainen** [jrouwe/JoltPhysics#568]
I'm comparing Jolt with Godot 3 physics, and I created a test to try out Jolt. I made various different test combinations and in one I noticed quite a large problem. When creating static compound shapes with spheres as the sub-shapes, a ton of the physics bodies phase through each other:

![2023-06-12_10 55 18 2424](https://github.com/jrouwe/JoltPhysics/assets/3796411/19ce4d09-69d4-48be-b26d-bd3f199b426a)

The same problem doesn't exist when using Godot physics (which is Bullet I believe), or when switching Jolt over to convex hulls:

![2023-06-12_11 00 53 6839](https://github.com/jrouwe/JoltPhysics/assets/3796411/4b5e9ce0-08ff-4adc-9eda-e3245e0d0a05)

I noticed also a slightly less serious problem which is that the compound shapes experience a lot less slowing down; with the same impulse force each frame they move *much* faster.

I'm not sure if I'm doing something incorrectly or if this is a bug / unsupported use. I'll anyway need to use compound shapes to attach some extra parts to the convex shape (to detect if specific parts of game objects collide with each other for gameplay purposes) even if I take that approach.

This is my code for compound shapes:
```c++
JPH::RefConst<JPH::Shape> ShapeCreator::CreateMicrobeShapeSpheres(
    JVecF3* points, uint32_t pointCount, float density, float scale, const JPH::PhysicsMaterial* material /*= nullptr*/)
{
    const auto sphereShape = SimpleShapes::CreateSphere(1 * scale, density, material);

    JPH::StaticCompoundShapeSettings settings;

    const auto rotation = JPH::Quat::sIdentity();

    for (uint32_t i = 0; i < pointCount; ++i)
    {
        const auto& sourcePoint = points[i];

        settings.AddShape(
            {sourcePoint.X * scale, sourcePoint.Y * scale, sourcePoint.Z * scale}, rotation, sphereShape.GetPtr(), 0);
    }

    return settings.Create().Get();
}
```

And this is the convex shape:
```c++
JPH::RefConst<JPH::Shape> ShapeCreator::CreateMicrobeShapeConvex(JVecF3* points, uint32_t pointCount, float density,
    float scale, float thickness /*= 0.2f*/, const JPH::PhysicsMaterial* material /*= nullptr*/)
{
    auto settings = JPH::ConvexHullShapeSettings();
    settings.mMaxConvexRadius = JPH::cDefaultConvexRadius;

    auto& pointTarget = settings.mPoints;
    pointTarget.reserve(pointCount * 2);

    if (scale != 1)
    {
        for (uint32_t i = 0; i < pointCount; ++i)
        {
            const auto& sourcePoint = points[i];

            const auto scaledX = sourcePoint.X * scale;
            const auto scaledY = sourcePoint.Y * scale;
            const auto scaledZ = sourcePoint.Z * scale;

            pointTarget.emplace_back(scaledX, scaledY, scaledZ);
            pointTarget.emplace_back(scaledX, scaledY + thickness, scaledZ);
        }
    }
    else
    {
        for (uint32_t i = 0; i < pointCount; ++i)
        {
            const auto& sourcePoint = points[i];

            pointTarget.emplace_back(sourcePoint.X, sourcePoint.Y, sourcePoint.Z);
            pointTarget.emplace_back(sourcePoint.X, sourcePoint.Y + thickness, sourcePoint.Z);
        }
    }

    if (material != nullptr)
        settings.mMaterial = material;

    settings.SetDensity(density);

    return settings.Create().Get();
}
```

**Comment by hhyyrylainen** [comment]
Thanks for the fast response.

> So my guess is that you have a lot of contact points. These go into a fixed size buffer and if you run out of that buffer then Jolt starts ignoring contacts which means the objects will penetate. If this is the case PhysicsSystem::Update will return an error code, so that's something you can check. You can easily increase the buffer size in the PhysicsSystem::Init call.

This was actually the initial impression of one of my team members as well that this might be the case. I tried multiplying the body pairs and constraint amounts by 100:

```
    const uint maxBodyPairs = 65536 * 100;
    const uint maxContactConstraints = 20480 * 100;
```
I think that did something as I had to also multiply the temp allocator memory to keep things from crashing. However it did not help with this problem. I had already also put in code to print any error codes returned by `PhysicsSystem::Update` and I did not see any of those prints. I just now tested with a debugger and I also couldn't see any cases when the update would have returned an error code even when objects were clearly phasing through each other.

> If this is not the case then please make a snapshot using code similar to SamplesApp::TakeSnapshot and verify that you can load it in the sample app and that it shows the same behavior by starting the LoadSnapshotTest. If you attach this file then please also let me know exactly which version of Jolt you're running with (git commit hash or date).

I'll try to create a snapshot. I read in the documentation that the samples app is Windows only? Is this still the case? If so I won't be able to really test that the snapshot has the problem, I'll only be able to save a snapshot.

> For the 2nd question: The spheres partially overlap, the mass and inertia of the compound is calculated by simply adding all masses together, ignoring any overlaps. This probably means that your compound of spheres is heavier than the convex hull which means it will respond less to impulses.

I think I saw the opposite, i.e. the convex hulls move slower with the same impulse value.
But I realize now that that is likely the effect of different total mass for the shapes, I was still thinking with the bullet approach where you are allowed to specify the mass of objects directly so I thought that the mass would be the same for the objects. But that is unlikely to be the case as their volume is different even though I use the same density value (resulting in different total mass). This is very unlikely to be any kind of problem for real gameplay code. So that's one mystery solved.

> Also I see a bug in your code: If you create a hull using only the center of each sphere and the center + (0, r, 0), you're ignoring a large part of the volume of the sphere. Slightly better would be to use center - (r, 0, 0), center - (0, r, 0), center - (0, 0, r), center + (r, 0, 0), center + (0, r, 0), center + (0, 0, r) but then you're still missing a lot of the surface of the sphere. This bug will also make the shape a lot lighter.

Very good observation. I realized this when making the testing code but I decided not to do anything about this for simplicity. And it also turned out that the convex expansion factor actually resulted in really close physics shape compared to the visually rendered spheres. Well at least when considering the 2D plane. I'm testing this for the first part of the game I'm working on which plays in 2D (but is rendered in 3D). 

I added a constraint to try to hold things at Y=0. I got the code for that from [TwoDFunnelTest.cpp](https://github.com/jrouwe/JoltPhysics/pull/378/files#diff-3d890f5812929e2af26045c8bff78ad2e1861dfe9ed15d084c5c385f24029345) (with slight tweak mentioned in another issue). Could that cause issues? Unrelated to the problem at hand, I noticed that for some reason that axis lock is not absolute. The bodies still drift around the y-axis a bit and to counteract that I tried to add code that forces bodies back to Y=0 if they drift more than 0.05. When compared to Bullet (through Godot) it has an absolute axis lock (there's 0 drift on the Y-axis when axis lock is enabled).

For real gameplay visuals there exists a point shrink wrapping algorithm in our codebase to create the visuals for wrapping around the points, which I can also use to feed into the convex shape generation. I didn't do that yet as it would have complicated the test code and the default convex hull generation seems to not wrap very tightly around the points anyway.

**Comment by hhyyrylainen** [comment]
I think I was able to create the snapshot correctly. Just in case I just didn't manage to get a frame where the physics problem occurred I took two snapshots:
[snapshots.zip](https://github.com/jrouwe/JoltPhysics/files/11732772/snapshots.zip)

These were created with Jolt version ad9cd403cc032bf56442803616d1081788df9d96 (Sat Jun 10 14:51:40 2023 +0200)

**Comment by hhyyrylainen** [comment]
Okay so I just noticed I had a missing `!` in my code (I noticed thanks to investigating getting debug rendering working), turns out that I had the bodies be created the opposite way of what I intended. So when thinking I was making convex shapes I actually got sphere shapes and vice-versa. I'll report back once I fully investigate the situation again, but it might be that things are phasing through *when convex* which could mean that my convex shapes are too small / thin and as such they can pass slightly above or below each other (due to the Y-axis lock not being absolute).

**Comment by jrouwe** [comment]
Ok, I'm going to close this ticket in the mean time. If there is still an issue comment on it and I will re-open.

Note that I've also done some work to support 2d simulations in the past which is located here: https://github.com/jrouwe/JoltPhysics/tree/feature/2d_sim

I'm not planning to merge this as is as I'm not happy with the API yet but you could try if this fixes your issue.

**Comment by hhyyrylainen** [comment]
That's fine, thanks for your time in helping out with this. I think my problem was actually caused by the axis locking not fully working and me having too thin convex bodies.

I'll post my follow up problem with the axis lock not fully working in: https://github.com/jrouwe/JoltPhysics/discussions/180
