### ISSUE TITLE
web demo with wasm ?

### ISSUE THREAD

**Issue by kapouer** [jrouwe/JoltPhysics#57]
Sorry to ask, because i know it's not easy to achieve, but it would surely be a hell of a demo.

**Comment by jrouwe** [comment]
Sorry, this is not something I'm planning to do at the moment. I want to create high end video games, supporting or even maintaining WASM would cost me too much time.

**Comment by jrouwe** [comment]
A preliminary version of this is now available here: https://github.com/jrouwe/JoltPhysics.js
