### ISSUE TITLE
Error compiling project under Linux headers Jolt Physics

### ISSUE THREAD

**Issue by daniilpetrov** [jrouwe/JoltPhysics#576]
Added compiled libraries and some Jolt Physics header files to his project, Windows project is compiled without problems, and Linux compiler in **Shape.h** file after the line "**enum class EShapeType : uint8**" gives the error:

```
expected identifier before numeric constant
expected «}» before numeric constant
to match this «{»
expected unqualified-id before numeric constant
```

With the next line "**enum class EShapeSubType : uint8**" the following errors appear:

```
найдено «:» во вложенном спецификаторе имени, ожидалось «::»
«EShapeSubType» не был декларирован
expected unqualified-id before «{» token
```

And then the error is repeated many times:

`«EShapeSubType» не является именем типа`

**Comment by jrouwe** [comment]
Can you attach the full compiler output again?

**Comment by daniilpetrov** [comment]
Yes, of course: [Build log.txt](https://github.com/jrouwe/JoltPhysics/files/11775865/Build.log.txt)

**Comment by jrouwe** [comment]
So this time it looks like it is coming from your own ActionManager.cpp which is including Shape.h:

```
In file included from /run/media/johndoe/Works/Native-Engine/Engine-Sources/Native-Engine/stdafx.h:13,
                 from /run/media/johndoe/Works/Native-Engine/Engine-Sources/Native-Engine/ActionManager.cpp:5:
../Engine-SDK/include/Jolt/Physics/Collision/Shape/Shape.h:56:9: ошибка: expected identifier before numeric constant
   56 |         Convex,                                                 ///< Used by ConvexShape, all shapes that use the generic convex vs convex collision detection system (box, sphere, capsule, tapered capsule, cylinder, triangle)
      |         ^~~~~~
```

And I think you probably have a ```#define Convex <some number>``` somewhere (maybe from a 3rd party library?). Try doing ```#undef Convex``` before including Jolt headers.

**Comment by daniilpetrov** [comment]
Yeah, it’s in the Bullet Physics header files, I’ll look into it, but I’m not gonna close the deal until I’m sure that’s the problem.

**Comment by daniilpetrov** [comment]
Yes, it is true that my project is conflicted with Jolt and Bullet Physics, and a separate project HelloWorld compiled without problems. Thank you, I will deal with further :)
