### ISSUE TITLE
Slower sleeping of group of ragdolls

### ISSUE THREAD

**Issue by NicSavichev** [jrouwe/JoltPhysics#592]
After upgrading from rev 9cfdcf024cf1e031a733115bcf997077f709afb3 to rev ed4e4d4d90388fc2e0b8e0d351b3965ac0c1d412 my test for 100 ragdolls (group of objects, not stack) shows sleep time of 20.+ sec (instead of 14.6 sec before).
Is this expected? Or maybe some inactivation code was broken?
If it is expected (e.g. better energy checks or similar) are there some settings/tweaks to make inactivation faster?
Simulation does not have visual differences for older and newer code/

**Comment by jrouwe** [comment]
Try rolling back b40883585c503a8eb7c9eb85fa923a964f8a314f locally to see if that explains the difference. The bug caused the friction coefficient to be max sqrt(2) larger than it should have been. A larger friction could have caused the pile of ragdolls to sleep earlier.

**Comment by NicSavichev** [comment]
Yes, exactly. Reverting this change returns 14.6 sec for sim-before-sleep from 20.2 sec.
Where can I setup larger friction for bodies to get faster sleeping with latest code? 
Just increase JPH::BodyCreationSettings::mFriction when creating body?

**Comment by NicSavichev** [comment]
Got it
