### ISSUE TITLE
ObjectToBroadPhaseLayer is too inflexible

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#60]
I'm trying to get a grasp on how to set up broadphase layers, object layers and collision filtering.

Unfortunately, broadphase layers are directly linked to object layers, because you have to map from an object layer to a broadphase layer and (AFAIK) can't set the broadphaase layer of a body directly.

IMO the most flexible solution would be, if I could just set the broadphase layer of a body or shape directly. Another option would be to change the ObjectToBroadPhaseLayer type from a fixed array to a function pointer.

Here is what I am trying to achieve:

Users should be able to configure their own collision groups (up to 32 or 64 maybe). For every group they can decide with which other group those objects should collide with, so you get an NxN matrix. At runtime you need an array of size N which contains uint32 or uint64 masks that tell you which other collision group this group would collide with, so that you can make a quick bitmask check.

That is all data driven. Additionally, on the broadphase I want to have a few fixed layers:
*  Static geometry -> collides with dynamic and debris
*  Dynamic objects -> collides with static, dynamic and triggers
*  Triggers -> collides with dynamic
*  Query shapes -> collides with nothing, only for raycasts and overlap queries
*  Debris -> collides with static only

The assignment of these broadphase layers should not be up to the user, but simply depend on what kind of body is created. That means the same collision layer might be in use in different broadphase layers.

Under the restriction that I can't set the broadphase directly, I was thinking of using the 16 bit of the object layer, to store the broadphase layer index in the upper 8 bit and the collision group in the lower 8 bit. Then in my ObjectVsBroadPhaseLayerFilter I could easily extract the broadphase layer index from the object layer and check whether the two broadphase layers should interact.

However, since ObjectToBroadPhaseLayer is an array, I would need to create a huge lookup table to cover all combinations.

Finally, it would also be nice to set the object layer per shape, rather than per body, so that one can easily add details to an object that, for example, are picked up by certain raycasts, but are ignored when colliding with the world.

Told you I'd have some feedback :D Overall Jolt is really, really awesome, it's so polished for a first version, I'm quite impressed and am looking forward to seeing some of these remaining rough edges improved.

Cheers,
Jan.

**Comment by jrouwe** [comment]
The way we implemented things is that we have N object layers (100-ish), they're named like 'collide with dynamic except for humans', these layers point to a collision matrix of NxN bits. This way we can control exactly which object layer collides with which other object layers. We have a much smaller number of broad phase layers (10-ish) and map them through a simple table. I can see that if you use the object layer as a bit field that a mapping table won't be ideal. 

Is 16 bits enough to use it as a bit mask? Enlarging the amount of bits costs quite a bit of memory since we pre-allocate 'max bodies' * sizeof(QuadTree::Tracking).

Changing ObjectToBroadPhaseLayer to a function does come at a perf cost when adding/removing bodies (which is something that needs to be really fast).

**Comment by jankrassnigg** [comment]
>  we have N object layers (100-ish), they're named like 'collide with dynamic except for humans', these layers point to a collision matrix of NxN bits

That does sound like what I want, except that you use much more layers. I'm wondering whether they basically represent some of the combinations that I'm trying to automate.
E.g. in the past I had 1 collision group for the player. The way I would create a trigger that only works for the player, was to give both objects that collision group.
In Jolt currently I would have to set up two groups: "Trigger: collide with player" and "Player", just so that I can then map the trigger object into the trigger broadphase layer. However, since the engine knows what a trigger is, it could do this for you automatically and thus make it much easier to use correctly and efficiently.

I don't necessarily want to use the object layer as a bitmask. Actually at the moment I just want to use it as two 8 bit indices for [broadphase; collision group]. And 256 items for each should be enough. But even that was just an idea to work around the fact that I can't specify the broadphase layer directly, if I could do that, an 8 bit object layer would be sufficient as well (for me at least).

> Changing ObjectToBroadPhaseLayer to a function does come at a perf cost when adding/removing bodies (which is something that needs to be really fast).

Well, I'm a bit surprised if one additional function call is that much of an issue, at least considering all the other stuff around object creation (outside of Jolt) that's going on to create objects, but I have to take your word for it.

However, why not get rid of the mapping table entirely and just let users specify the broadphase layer directly in the body creation settings? Then people can use a mapping table there, or hardcode it or use a function, and it is in their hand how much performance they are willing to sacrifice. All that the physics system needs to know up front is the number of broadphase layers to allocate.

**Comment by jrouwe** [comment]
> However, why not get rid of the mapping table entirely and just let users specify the broadphase layer directly in the body creation settings? Then people can use a mapping table there, or hardcode it or use a function, and it is in their hand how much performance they are willing to sacrifice. All that the physics system needs to know up front is the number of broadphase layers to allocate.

I think storing the broad phase layer directly in the body is a good solution! I will keep the mapping table (as a virtual interface) in the physics system and calculate the broad phase layer as bodies are created / their layers change. This should avoid much of the overhead at the cost of adding 2 bytes to a body (luckily this falls into the padding so doesn't actually increase its size).

**Comment by jrouwe** [comment]
Can you take a look at #65? I think this should give the flexibility you want (I'm still testing it, but it looks like it works).

**Comment by jankrassnigg** [comment]
So you actually did turn it into an interface and just cache the lookup, so it doesn't need to be done all the time. Works for me!

**Comment by jrouwe** [comment]
Fixed in #65
