### ISSUE TITLE
Support for CCD/Linear Cast sensors?

### ISSUE THREAD

**Issue by Joshua-Ashton** [jrouwe/JoltPhysics#633]
Hello!

I would really like to use linear cast/ccd as with the chaotic things that happen in Garry's Mod and other Source titles, it can be easy for entities to fly out of the world with discrete unless the steps are turned up which impacts performance greatly.

We have been using it, but I recently found out that CCD + sensors are not supported, and this was the cause of the following issue.

https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/1

This is because ages ago I made an issue and PR about being able to force an object to a sensor in the collision callback, which we do regularly and is why this is causing an issue there.

**Comment by Joshua-Ashton** [comment]
The problem is that if I set mIsSensor = true in OnContactAdded, then there is still a collision on the CCD path

**Comment by jrouwe** [comment]
Ok, that's something I can probably fix.

**Comment by jrouwe** [comment]
I haven't tested the code, but I think https://github.com/jrouwe/JoltPhysics/pull/637 should do the trick. Can you try it out?

**Comment by Joshua-Ashton** [comment]
Thanks, I am out today but I had a friend test it and they told me it fixes the problem 🙌

**Comment by jrouwe** [comment]
Ok, thanks for testing. I've merged the change into the master branch.
