### ISSUE TITLE
Locking two bodies at the same time (joint setup)

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#64]
I am trying to create a joint between two bodies.

ConstraintSettings::Create expects two writable body references. I only have body IDs, so I'm trying to use two BodyLockWrite to lock both bodies and then create the joint. However, an assert fires, telling me that another write lock has already been taken.

In the samples I couldn't find anything similar, there the joints are always created in the same code that also creates the bodies, so it just holds pointers to those around for the needed duration.

What's the recommended way to do this?

**Comment by jrouwe** [comment]
Take a look at BodyLockMulti.h

**Comment by jankrassnigg** [comment]
Also, while I'm asking random questions, why is the A-team intro in you playlist ?? :D
https://www.youtube.com/watch?v=Cn6kEsloMdE&list=PLYXVwtOr1CBxbA50jVg2dKUQvHW_5OOom&index=17

Anyway, feel free to close this ticket, my question has been answered.

**Comment by jrouwe** [comment]
> Ah thanks, got it working. I was searching for something like this, but didn't see that there was an additional header for the multi functions. When learning a new API from searching source code and some samples, it's easy to miss things. Maybe the documentation on BodyLockRead could have a "see also BodyLockMultiRead for locking multiple bodies" comment? (don't know, just an idea)

I added this to Architecture.md.

> Also, when I used BodyLockWrite, I think it worked just fine with invalid body IDs (0xffffffff) and just returned "failed", but the Multi locks actually crash, because they do an out-of-bounds array access internally. Is that supposed to work?

That's my bad, I'll fix it.
