### ISSUE TITLE
Assertion failed on EPA algorithm stage

### ISSUE THREAD

**Issue by daniilvinn** [jrouwe/JoltPhysics#660]
Hello!

Recently I have ran into an issue which causes my application to crash. Sometimes, when collision is entered or persisted, `JPH_ASSERT(last->mClosestPointInterior);` assertion in `EPAPenetrationDepth.h`, line 352 is triggered with experession being false. I use 2 bodies: one static and another is dynamic. Both have 0 friction and restitution, combined values are calculated as in JPH's example. I move dynamic body using `BodyInterface::AddForce()`, but I had exact same issue when I had diagonal wall where my dynamic body slided on and issue was still present. I use fixed time step of 1/120, newest commit of master branch. Both bodies' shape's convex radius is 0.1f.

I can provide any information needed, the one provided above is everything I have for now.

**Comment by jrouwe** [comment]
Hello,

I've seen this assert trigger before, but I have never been able to catch it in the debugger. The assert itself is pretty harmless, so I just removed it.
