### ISSUE TITLE
Easy way to wake bodies after joint update

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#67]
Changing properties on a joint doesn't wake up actors, so might not have any effect.

The only way I've found to force an update is to do 

    PhysicsSystem->GetBodyInterface().ActivateBody(joint->GetBody2()->GetID());

Assuming that body1 is implicitly woken up as well, and may not exist, if the joint is anchored to the world.
Is there a simpler way?

Might be nice to simply have a "WakeBodies" function on the constraint class.

**Comment by jrouwe** [comment]
Fixed by #73
