### ISSUE TITLE
MotorSettings could use more in-depth documentation

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#70]
All physics engines I've worked with (PhysX, Bullet, Havok) expose some values that require some deep understanding of how physics solvers work (which I totally don't have). Surprisingly, the documentation for these values is always very shallow, I guess because the people writing the docs are also missing that deep understanding - your chance to be better! ;-)

I'm currently applying a motor to a hinge constraint.

In MotorSettings what is the min force/torque limit? Does this have to do with the direction into which it goes? Or is "min" literally the minimum force/torque that is applied (that wouldn't make sense with the symmetric values though).

Why is there a distinction between torque and force? As far as I can tell, you always only drive one thing, right? Wouldn't that mean that every drive uses exclusively one value or the other, but never both? In that case, I'd simplify the struct (maybe always call it "force"  and mention in the comment that this is a torque for rotational things).

For position targets, what exactly do mFrequency and mDamping do? Especially mFrequency doesn't tell me much. And can mDamping be larger than 1 ? Maybe give an example for when to set these values differently.

Also "position" is a bit of an overloaded term, when driving a hinge to a target angle, it is not immediately obvious that this is a "position" (I first thought this might rather apply to slider constraints).

I am also looking up a lot at implementation details to figure some stuff out. For example to see what "Set symmetric force limits" exactly means and under which conditions "IsValid" actually returns true/false. 

Finally, why is driving a hinge to a target angle so weak?? I have set both force and torque limit to 10000 but it just stops when it encounters any resistance. However, driving the velocity instead, using a limit of 100 is already pretty strong and will push the same object easily out of the way.

**Comment by jrouwe** [comment]
(don't have a lot of time now, so short reply)

Usually min torque = -max torque. If you set min torque to 0 and max torque to some high value then the motor can only push in 1 direction. In most cases it's best to just leave the torque limits alone (unless you want to give the motor some max strength, but then still you would put min torque = -max torque.

There is a distinction between the the two because they have different units and some constraint may use both (if there's both a position and a rotation constraint).

Frequency and damping: I would suggest reading 'Modeling and Solving Constraints' by Erin Catto presented at GDC 2009. It's based on that.

Torques are usually very high, so while 10000 may seem like a lot, I've seen much higher values. Torque = Inertia * Angular Accelaration. Inertia of a solid sphere is e.g. 2/5 m r^2 so you can calculate what a sensible torque is in order to get an angular acceleration that you want.

**Comment by jankrassnigg** [comment]
> Frequency and damping: I would suggest reading https://box2d.org/files/ErinCatto_SoftConstraints_GDC2011.pdf (sorry had wrong link before)

I read it and it mentioned frequency and damping on one slide, but not in a way that I understood anything. As far as I understood it, these values tune the springs in such a way that they are easier to get right? I've played a bit around with these values and yeah, well, higher frequency makes stuff more springy, higher damping makes it less springy again ...

> Torques are usually very high

I have tried this again (a squashed box rotating, that's supposed to push other objects aside) and even when I set no maximum, so it's FLT_MAX, driving it to a position target is too weak to push much out of the way. I've even tried attaching multiple constraints, all trying to drive the same box, without success. Somethings fishy here, as far as I can tell.

This is low priority to me though, just saying, maybe you want to take a look at it at some point.

**Comment by jrouwe** [comment]
Works fine here:

https://user-images.githubusercontent.com/1621693/156051737-9ac3c19c-4757-4426-a065-1b46987b60bf.mp4

I adjusted PoweredHingeConstraintTest to this:

`void PoweredHingeConstraintTest::Initialize()
{
	// Floor
	CreateFloor();
		
	// Create group filter
	Ref<GroupFilterTable> group_filter = new GroupFilterTable;

	// Create box
	float box_size = 4.0f;
	RefConst<Shape> box = new BoxShape(Vec3::sReplicate(0.5f * box_size));

	Vec3 body1_position(0, 0.5f * box_size, 0);
	Body &body1 = *mBodyInterface->CreateBody(BodyCreationSettings(box, body1_position, Quat::sIdentity(), EMotionType::Dynamic, Layers::MOVING));
	mBodyInterface->AddBody(body1.GetID(), EActivation::Activate);

	Vec3 body2_position = body1_position + Vec3(box_size, 0, 0);
	Body &body2 = *mBodyInterface->CreateBody(BodyCreationSettings(box, body2_position, Quat::sIdentity(), EMotionType::Dynamic, Layers::MOVING));
	body2.GetMotionProperties()->SetLinearDamping(0.0f);
	body2.GetMotionProperties()->SetAngularDamping(0.0f);
	body2.SetAllowSleeping(false);
	mBodyInterface->AddBody(body2.GetID(), EActivation::Activate);

	Vec3 constraint_position = body1_position + Vec3(0.5f * box_size, 0, 0.5f * box_size);

	HingeConstraintSettings settings;
	settings.mPoint1 = settings.mPoint2 = constraint_position;
	settings.mHingeAxis1 = settings.mHingeAxis2 = Vec3::sAxisY();
	settings.mNormalAxis1 = settings.mNormalAxis2 = Vec3::sAxisX();
	mConstraint = static_cast<HingeConstraint *>(settings.Create(Body::sFixedToWorld, body2));
	mConstraint->SetMotorState(EMotorState::Velocity);
	mConstraint->SetTargetAngularVelocity(DegreesToRadians(25));
	mPhysicsSystem->AddConstraint(mConstraint);

	// Calculate inertia of body 2 as seen from the constraint
	MassProperties body2_inertia_from_constraint;
	body2_inertia_from_constraint.mMass = 1.0f / body2.GetMotionProperties()->GetInverseMass();
	body2_inertia_from_constraint.mInertia = body2.GetMotionProperties()->GetLocalSpaceInverseInertia().Inversed3x3();
	body2_inertia_from_constraint.Translate(body2_position - constraint_position);
	mInertiaBody2AsSeenFromConstraint = (body2_inertia_from_constraint.mInertia * Vec3::sAxisY()).Length();
}
`

**Comment by jrouwe** [comment]
The higher the frequency, the quicker the body will move to its target. If you set a frequency of 1 then it will oscillate 1 time per second around the target position, if you set it to 20 it will oscillate 20 times per second around the target position. You should never go higher than half of your simulation frequency (otherwise: instability). 

Damping prevents overshoot. A damping of 0 means that the body will oscillate forever around its target position (in theory that is, with the integrator that Jolt uses that won't happen). A damping of 1 will barely overshoot the target and have almost no oscillation, but it will also take slightly longer to reach the target. I would say sensible ranges for frequency are 0.1-20 and for damping 0-1. 

Take a look at mInertiaBody2AsSeenFromConstraint for the calculation for the torque limit.

**Comment by jankrassnigg** [comment]
Your code uses a velocity target, right?

    mConstraint->SetMotorState(EMotorState::Velocity);
    mConstraint->SetTargetAngularVelocity(DegreesToRadians(25));

That works for me as well. It's not working well when it uses a Position target instead. I'm wondering whether it's a problem with the masses. I kept the density at 1000 which might mean my objects are just too heavy, though well, I would assume that if it works for velocity, it should also work for position targets.

Anyway, will investigate a bit more, once I get some time (not today).

> The higher the frequency, the quicker the body will move to its target. ....

Thanks for the explanation, very interesting. Something like this should be written in the MotorSettings documentation for others to see as well.

**Comment by jrouwe** [comment]
Setting menu (image above) you can switch to position too. I tested that it worked for both cases (video was from velocity indeed).

And yes I'll create some documentation for constraints (it's good to see what you run into to direct the documentation effort a bit).

**Comment by jankrassnigg** [comment]
I tested it again, and indeed it has to do with the mass of the pushed objects. An object of mass 1000 completely blocks the motor when it is set to reach a position, but is no problem when it should reach a velocity.

See this video:

https://user-images.githubusercontent.com/6001174/156547474-357220ec-a7c9-4263-93c6-1b23a1e23aed.mp4

The red boxes use the default density of 1000, but since they are small, they have a mass of 200 or so. The orange boxes are set to have a mass of 1000.

These are pretty high mass values for physics engines I guess, but I would still not expect a difference in strength between velocity and position targets.

**Comment by jrouwe** [comment]
What do you have your spring frequency and damping set to and what does 'drive strength maximum' mean? (a velocity motor doesn't use freq/damping, for a position motor the strength gets modulated by the distance to target so the closer to the target the lower the force it will push with)

**Comment by jankrassnigg** [comment]
All motor settings use default values. 'Maximum' also just means to leave the default value of FLT_MAX in there. IIRC that means frequency is 2 and damping 0 (don't have the code at hand right now to check).

**Comment by jrouwe** [comment]
Sorry, I see I never answered this. Have you tried setting the frequency to 20? That should make the motor a lot stronger.

**Comment by jankrassnigg** [comment]
Yes, setting frequency to 20 makes it much stronger!

So, back to my original ticket request: such details could be documented in more detail, because "Oscillation frequency when solving position target (Hz)" didn't inform me at all, that this affects how heavy objects can be pushed aside.

Thanks for the help :)

**Comment by jrouwe** [comment]
Yes, I'll leave this ticket open until I do.

**Comment by jrouwe** [comment]
I just added documentation on the motor settings in 409aa43b8e37cdf5b3f7752554a90d3fda721127. Can you proof read it for me and tell me if it is understandable? (results should be here in a couple of minutes: https://jrouwe.github.io/JoltPhysics/)

**Comment by jankrassnigg** [comment]
Awesome! Very nice documentation. As far as I can tell there are no errors.

The only addition that might be useful, is to point out in MotorSettings.h that there is additional documentation in a separate file.

**Comment by jrouwe** [comment]
Done.
