### ISSUE TITLE
CharacterVirtual snap to ground bug

### ISSUE THREAD

**Issue by skaarj1989** [jrouwe/JoltPhysics#703]
[2023-09-12 14-52-21.webm](https://github.com/jrouwe/JoltPhysics/assets/34756939/da9c0133-55d1-4b8b-abb9-8982a83921ce)

**Comment by AndreaCatania** [comment]
I've noticed that the character loses the ground too easily.
I've noticed that **sometimes** stepping on a step, causes the character to lose the ground contact for few frames.

**Comment by jrouwe** [comment]
I think this has to do with the update order, the character is not updated at the same time as the platform so they're always a bit out of sync. I'll investigate and will let you know.

**Comment by jrouwe** [comment]
I created a PR that fixes the issue, please see the elaborate description of #708 why it was happening. Note that due to the complexity of the virtual character, it is quite possible that this fix introduced new issues.
