### ISSUE TITLE
Allow to create constraints with custom local frames

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#71]
Setting up constraints in Jolt is really nice and easy, it was a joy to get up and running and have it working very quickly.

With PhysX I made the experience that setting up constraints can be quite painful, because it expects coordinate frames in the local frame of each body. This is often a mess to figure out. However, it does give you much more control.

In Jolt, when I for example set up a point constraint, I set the common position in world space. This assumes that at the time of setup, the two bodies are positioned exactly right, and it then computes the local frames internally.

This is, however, not always the case. If, for example, at runtime I want to glue two separate objects together, they won't be in the right place. If I can add a constraint with local frames, I could have the constraint snap them together as needed. With Jolt that is currently not possible, because the interface doesn't allow me to set this up.

It's the same for all other constraint types. E.g. for the slider constraint I can't specify how for along the allowed range a body is at start, because the interface expects that at simulation start they are always at offset 0. So I'd have to adjust the min/max limits accordingly every time I want to tweak something, rather than just moving the body around. So here the editing experience suffers.

Overall I like that Jolt makes getting up and running so easy, but I would like to additionally have a way to specify the local frames myself. Maybe through an additional constructor on the constraint, that I could call directly.

**Comment by jrouwe** [comment]
You're right that the point and slider constraint don't allow you to do this. However the cone, distance, hinge, swing-twist and 6DOF constraints all allow you to specify the constraint position and orientation in world space for both bodies. So in those cases you can simply multiply your local frame by GetCenterOfMassTransform() of the bodies and you're done. I will fix the other constraints to offer this possibility too.

**Comment by jrouwe** [comment]
#72 fixes it for the point constraint.

**Comment by jankrassnigg** [comment]
> So in those cases you can simply multiply your local frame by GetCenterOfMassTransform() of the bodies and you're done.

Good to know, I'll give that a try at some point. Not sure whether you'd want to add a documentation comment about that somewhere. The fact that after body creation some things are local to the center-of-mass rather than the actual body position was surprising to me before. For instance when I implemented visualization of a collision mesh that used convex decomposition (just multiple convex shapes attached to the same body) my visualization was all broken until I looked through the Jolt code and somehow found that I needed to render the mesh relative to the COM.

> I will fix the other constraints to offer this possibility too.

Awesome!

**Comment by jrouwe** [comment]
> my visualization was all broken until I looked through the Jolt code and somehow found that I needed to render the mesh relative to the COM

Yes, this is one of the things that I wish had done differently when I started. For simulation it is better to reason about all objects from their COM (which means shifting the shapes to be centered around their COM), but it takes a lot of mental effort to deal with it in all other places. I did put a big warning in various places in the code and in the [Center of Mass|https://jrouwe.github.io/JoltPhysics/] section.

**Comment by jrouwe** [comment]
#74 should fix it for the slider constraint (but I don't have time to fully test it now)

**Comment by jrouwe** [comment]
#74 has been merged.

**Comment by jrouwe** [comment]
There seems to be more demand for this, see #90
