### ISSUE TITLE
Building with Ninja on Windows seems to have troubles

### ISSUE THREAD

**Issue by photex** [jrouwe/JoltPhysics#720]
Ahoy!

I just tried to build Jolt by including it in another build (add_subdirectory) and it actually broke my build. :D For whatever reason, after configuration is done, CMake aborts without any error before it writes the build scripts.
Just wondering if you have any ideas why that might be the case, or if it's not surprising at all.

Cheers!

**Comment by jrouwe** [comment]
Sorry, I have never used Ninja so I have no idea.

**Comment by photex** [comment]
No worries then. Everything builds as expected using the scripts you have provided. It’s clearly some odd aspect of my build. 

If I determine the cause I’ll follow up! :)

**Comment by mihe** [comment]
For what it's worth, I use the `Ninja Multi-Config` generator when building [Godot Jolt](https://github.com/godot-jolt/godot-jolt), and it seems to work just fine. I don't use `add_subdirectory` (or `FetchContent`) though.

**Comment by photex** [comment]
Yep, it’s something peculiar when embedding it in another build then. Thanks for the extra context.
