### ISSUE TITLE
Virtual character controller jitters and gets stuck on slopes going upwards

### ISSUE THREAD

**Issue by polygonboutique** [jrouwe/JoltPhysics#736]
Hello :wave: 

Find below two videos showcasing movement jittering and occasionally getting stuck while going up a slope.
I am using a virtual character with an underlying box shape. (Using the capsule shape has the same outcome)

The surface in the video is made up of 2 triangles.

*Red vector:* Velocity
*Green vector:* Surface normal 

## Velocity == move direction
https://github.com/jrouwe/JoltPhysics/assets/6142529/4948661c-9726-49dc-ba5d-23f279a8c0bc

## Velocity parallel to ground ( projected onto the ground )
https://github.com/jrouwe/JoltPhysics/assets/6142529/737c96d5-449f-422c-86b4-4c5c623a3831

The settings I use for the virtual character are as follows
```cpp
virtualSettings->mShape = new JPH::BoxShape( JPH::Vec3( boxScale.x, boxScale.y, boxScale.z ) );
virtualSettings->mBackFaceMode = JPH::EBackFaceMode::IgnoreBackFaces;
virtualSettings->mMaxSlopeAngle = JPH::DegreesToRadians( 45.0f );
virtualSettings->mSupportingVolume = JPH::Plane( JPH::Vec3::sAxisY(), -1.0f );
virtualSettings->mCharacterPadding = 0.25f;
virtualSettings->mPenetrationRecoverySpeed = 1.0f;
virtualSettings->mPredictiveContactDistance = 2.5f;
virtualSettings->mCollisionTolerance = 0.25f;
```

I tried tweaking the settings, 
however I didn't manage to solve it this way.

I am using ExtendedUpdate
```cpp
	JPH::CharacterVirtual::ExtendedUpdateSettings updateSettings;
	updateSettings.mWalkStairsStepUp = characterPair.virtualCharacter->GetUp() * 20;
	updateSettings.mStickToFloorStepDown = -characterPair.virtualCharacter->GetUp() * 5;

	const JPH::PhysicsSystem *phys = physics->GetJoltPhysics();
	virtualCharacter->ExtendedUpdate(
		frameTime,
		GRAVITY_VECTOR_UNIT_DIR,
		updateSettings,
		phys->GetDefaultBroadPhaseLayerFilter( Layers::MOVING ),
		phys->GetDefaultLayerFilter( Layers::MOVING ),
		{},
		{},
		*physics->GetJoltAllocator()
	);
```

Am I doing something wrong?

Thanks in advance

**Comment by jrouwe** [comment]
What kind of units are you using?

E.g. setting mCollisionTolerance to 0.25 means that you find it acceptable that the difference between the actual collision point and the collision point found by the iterative solver is 25 cm which seems rather excessive (normally you want millimeter accuracy).

All of these settings seem pretty far away from the defaults:

```
virtualSettings->mSupportingVolume = JPH::Plane( JPH::Vec3::sAxisY(), -1.0f );
virtualSettings->mCharacterPadding = 0.25f;
virtualSettings->mPredictiveContactDistance = 2.5f;
virtualSettings->mCollisionTolerance = 0.25f;
```

so perhaps you can try without overriding these settings?

**Comment by polygonboutique** [comment]
I tried using the default, but it's behaving similarly. A bit worse maybe, as in I get stuck more easily.

As for units:
The box for the character is Vec3(32, 56, 32) in total size and it's half extents are Vec3(16, 28, 16).
The game world is sized around those reference measurements.

Would you recommend using smaller units?

**Comment by jrouwe** [comment]
Yes, the [Jolt documentation says](https://jrouwe.github.io/JoltPhysics/):

> Note that the physics simulation works best if you use SI units (meters, radians, seconds, kg). In order for the simluation to be accurate, dynamic objects should be in the order [0.1, 10] meters long and have speeds in the order of [0, 500] m/s. Static object should be in the order [0.1, 2000] meter long. If you are using different units, consider scaling the objects before passing them on to the physics simulation.

There are a lot of epsilons that are tweaked for these dimensions, your character is like 30x bigger than the usual character so that could be the issue. Unfortunately it is impossible to say if this is actually the cause of the issue, it could be that if you scale things down that it is still buggy. If it is easy for you to test then that would be great. Otherwise I'm going to need a dump of your level (see [here](https://github.com/jrouwe/JoltPhysics/blob/515933138c6b16d661452fb907a8a9bbb71cb848/Samples/SamplesApp.cpp#L742-L753) on how to do that).

**Comment by polygonboutique** [comment]
Alright, I'll test scaling down everything over the weekend and create the dump.

**Comment by polygonboutique** [comment]
The jittering went away after I reduced the scale by a lot.
I am now using a roughly human sized box. (1.0m x 1.8m x 1.0m) and I scaled the world accordingly.

Thanks a lot for your help! :slightly_smiling_face: :+1:
