### ISSUE TITLE
Add friction to all constraint types

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#75]
The friction option on constraints is really nice for tweaking behavior. All of these constraints already support this:
* hinge
* swing twist
* path
* 6-dof
* slider

It would be nice to have this also available in these constraints:
* cone
* point

**Comment by jankrassnigg** [comment]
On a related note, is it right to assume that constraints with more features either cost more performance, or are less stable, or both.

E.g. prefer point constraint > cone > swing twist > 6-dof ?

**Comment by jrouwe** [comment]
I think all joints should be equally stable, but the more complex the logic, the more the cost. From light to heavy (this is a guess, I haven't profiled it):

- Point
- Cone
- Slider/Hinge
- Swing Twist
- 6-DOF
- Path

The point and cone constraints are supposed to be cheap, so I'm not sure if I should add the extra complexity of friction to them. You can easily use a Swing Twist constraint and configure it without limits to get a point constraint, or a Swing Twist constraint with only swing limits to get a cone constraint with friction. The added cost of this should only be a couple of ifs (and a little bit of memory).

**Comment by jankrassnigg** [comment]
My thinking was the other way round: if I don't need twist limit I could use a cone constraint (e.g. in ragdolls) and if I don't need that either, I could use a point constraint. However, I always need the friction functionality.

**Comment by jrouwe** [comment]
I've decided to leave this as is. Adding friction to all constraints is going to duplicate code and the performance benefit is minimal compared to using a swing twist constraint with no limits.
