### ISSUE TITLE
__STDC_WANT_SECURE_LIB__ not defined as a preprocessor macro build error on Visual Studio 17.8.0

### ISSUE THREAD

**Issue by char8t** [jrouwe/JoltPhysics#758]
Today Visual Studio 17.8.0 got released and I am unable to build Jolt with it. Previous versions worked fine

The error message is:

`9>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\limits.h(70,5): error C2220: Die folgende Warnung wird als Fehler behandelt.
9>(Quelldatei „CMakeFiles/Samples.dir/cmake_pch.cxx“ wird kompiliert)
9>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\limits.h(70,5): warning C4668: "__STDC_WANT_SECURE_LIB__" ist nicht als ein Präprozessormakro definiert, wird durch "0" für "#if/#elif" ersetzt`

Steps to reproduce:

1. Update VS to version 17.8.0
2. Create solution with Build\cmake_vs2022_cl.bat
3. Open solution
4. Try to build it

**Comment by jrouwe** [comment]
This appears to be a bug in MSVC 17.8, I've reported it [here](https://developercommunity.visualstudio.com/t/Including-limitsh-triggers-error-__STDC/10514743).

In the mean time I created a workaround in #759
