### ISSUE TITLE
Constraints should have a flag whether to ignore collisions between joined objects

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#76]
AFAIK all other physics engines by default ignore collisions between joined objects. This is quite sensible, since the abstract physics shapes would otherwise often collide with each other, or it's quite difficult to setup physics shapes that don't touch while joined. For ragdolls this is particularly tricky.

I know that it may be possible to use the collision group filters to do this, but I haven't figured out yet how I would set things up such that two joined bones don't collide, but otherwise collide with the rest. I also can't imagine, that it is particularly efficient to use these filters everywhere.

If there is an easy way to set this up, I'd be interested to know. But I would still just prefer a flag on the constraints to disable collisions.

**Comment by Pierre-Terdiman** [comment]
_**AFAIK all other physics engines by default ignore collisions between joined objects.**_ 

Not all of them, far from it. PhysX does and I think it's a very useful feature, but IIRC Havok and others didn't - they were like Jolt.

FWIW the easiest way I found is to provide your own GroupFilter and do the filtering yourself (using a hashmap for example). See e.g.:

https://gist.github.com/Pierre-Terdiman/53b9e4d5aa2615e1a7258cbbe4ad3f48#file-gistfile1-txt-L351

**Comment by jankrassnigg** [comment]
It's been a long time that I used Bullet and Havok, my memory might be faulty, or things have changed.

Using a hashmap would be possible, but it's quite the price to pay. I would hope that if done internally, it could be a handled lot more efficiently.

**Comment by jrouwe** [comment]
See #77 (note that I'm going to extend it with the functionality to disable collisions between bodies in the rest pose too)

**Comment by jankrassnigg** [comment]
Nice!

**Comment by jrouwe** [comment]
I added the collision check now too (won't merge it today)

**Comment by jrouwe** [comment]
#77 has been merged.
