### ISSUE TITLE
GCC multi-line comment compiler warning

### ISSUE THREAD

**Issue by jamesdolan** [jrouwe/JoltPhysics#761]
Seeing this in GCC 11.4.0...
```
Jolt/Physics/Constraints/ConstraintPart/DualAxisConstraintPart.h:25:1: error: multi-line comment [-Werror=comment]
   25 | /// -n_1                                        & -n_2                                  \\
```
...caused by trailing backslash. Because this is one of the few warnings that can't be disabled via pragma it makes it hard to include this file as-is. I can confirm though that removing the trailing back slashes or adding non-whitespace after fixes the issue although I suspect more care is needed to ensure accurate documentation is generated.

Grepping for more examples, `HingeRotationConstraintPart.h` also appears to do the same thing.

Beyond that, props for creating a project that compiles so cleanly!

**Comment by jrouwe** [comment]
Are you using the provided CMakeLists.txt file?

It turns off this warning externally:

https://github.com/jrouwe/JoltPhysics/blob/affe4fcc8309de9674bb32d998916fae647da137/Build/CMakeLists.txt#L142-L146

The purpose of these comments is to have nice doxygen documentation:

https://jrouwe.github.io/JoltPhysics/class_dual_axis_constraint_part.html

**Comment by jrouwe** [comment]
Actually it seems it can be trivially fixed by using ```/** ... **/``` instead. See #762.
