### ISSUE TITLE
CMakeLists.txt for cmake

### ISSUE THREAD

**Issue by billgan1024** [jrouwe/JoltPhysics#764]
Can there be a CMakeLists.txt in the root directory so that we can add the library via `add_subdirectory(JoltPhysics)` using cmake?

**Comment by jrouwe** [comment]
Is it not possible to do something like ```add_subdirectory(JoltPhysics/Build)```?

**Comment by billgan1024** [comment]
Yes, it is possible to use `add_subdirectory(JoltPhysics/Build)` with 
`target_link_libraries(Jolt)`. (I was looking for some way to use `add_subdirectory` as it is less verbose than FetchContent, and usually there is a root CMakeLists.txt for that purpose.)

**Comment by jrouwe** [comment]
Does this answer resolve your issue?

**Comment by billgan1024** [comment]
Yes, thanks for the help!
