### ISSUE TITLE
Use standard types

### ISSUE THREAD

**Issue by amerkoleci** [jrouwe/JoltPhysics#770]
Hi,
I saw you're using own uint, uint64 types. What do you think to switch to uint32_t and uint64_t from stdint.h? 

I can submit PR if you want.

Thanks,
Amer

**Comment by jrouwe** [comment]
These types are just aliases for the std equivalents (and the typedefs are inside the JPH namespace so should not leak out to the user of the library):

https://github.com/jrouwe/JoltPhysics/blob/1718c930c0028aa6ccbd5f63e57ea1966942b2ea/Jolt/Core/Core.h#L426C27-L430

So you should be able to use them interchangeably with std::uint32_t etc.

What would be the benefit of this change? (I can see a clear downside, namely that it would break all my carefully lined out class headers)

**Comment by amerkoleci** [comment]
It was just of using standard types on global scope and avoid JPH::uint, etc.

Thanks for clarification
