### ISSUE TITLE
Mouse input is too sensitive when running samples on a remote machine over Parsec

### ISSUE THREAD

**Issue by ivte-dev** [jrouwe/JoltPhysics#783]
The issue #283 still occurs when connecting to a remote machine with Parsec due to `GetSystemMetrics(SM_REMOTESESSION)` returning false for this type of connection.

Perhaps it would be worth adding a command line flag to the `SamplesApp` that would force the simple mouse polling behavior?

**Comment by jrouwe** [comment]
Is there no way to detect this programmatically? (I don't have Parsec)

I guess a command line can be added, but my guess is also that nobody is going to find out about it.

**Comment by ivte-dev** [comment]
Not sure if there is a precise way to do that, but an imprecise way would be to check if "Parsec" service is running.

That would result in false positives (the same service is running on both hosts and clients), but IMO that's the lesser of two evils. If someone is running both Parsec service and Jolt samples on the same machine, chances are pretty high that they do it on a remote work machine, and if not, it's not that big of a deal anyway.

So, something like this (the code can be tested with any running service, not necessarily "Parsec"):

```
bool isServiceRunning(const char* serviceName) {
    bool isRunning = false;
    if (SC_HANDLE manager = OpenSCManager(nullptr, nullptr, SC_MANAGER_CONNECT)) {
        if (SC_HANDLE service = OpenServiceA(manager, serviceName, SERVICE_QUERY_STATUS)) {
            SERVICE_STATUS status;
            if (QueryServiceStatus(service, &status)) {
                isRunning = status.dwCurrentState == SERVICE_RUNNING;
            }
            CloseServiceHandle(service);
        }
        CloseServiceHandle(manager);
    }
    return isRunning;
}
```
It can be called on startup with `isServiceRunning("Parsec")` and cached together with `GetSystemMetrics(SM_REMOTESESSION)` (likely no reason to re-run the checks on every frame).

Unfortunately, it looks like everything Parsec is doing is symmetric for hosts and clients. For example, both will have "Parsec Virtual Display Adapter" connected all the time, etc., so if there is a robust way to tell them apart, I'm not aware of it.

**Comment by jrouwe** [comment]
I've added your code to the sample app and I can verify that it works if I pick a random service, but as I don't have Parsec myself I would appreciate if you can confirm that this indeed works for you.

Thanks!

**Comment by ivte-dev** [comment]
Works perfectly now for my remote setup, thank you very much!
