### ISSUE TITLE
Performance regression with 9d63f5a2d1b9e426a54dce6c8979e22ff6004eba

### ISSUE THREAD

**Issue by AndreaCatania** [jrouwe/JoltPhysics#800]
Hello, I've recently updated the Jolt repository and the game map never finished loading. I've find that this commit 9d63f5a2d1b9e426a54dce6c8979e22ff6004eba made the loading extremely worse.

After reverting that commit, I was able to load the map in few seconds as usual. The function which most of the time is spent is `sIndexifyVerticesRecursively` and you can reproduce the issue just by trying loading this mesh: https://sketchfab.com/3d-models/wall-3rd-june-2020-c6e78a8ca4814bb5bce1fc0e939de8fd

**Comment by jrouwe** [comment]
Hello,

I cannot reproduce this. I tried embedding this mesh into one of the tests:

[MeshShapeTest.zip](https://github.com/jrouwe/JoltPhysics/files/13692102/MeshShapeTest.zip)

Building the shape takes 0.17 s with the old code and 0.20 s with the new code in clang release mode (I should probably have exported the mesh as a binary file as the compiler is struggling a lot with the size of MeshShapeTest.cpp).

My guess is that your mesh loader provides the vertices in a different order / processes them in a different way. Can you adjust this sample so it triggers the problem?

B.t.w. this is not the kind of detail you should be passing to a physics engine.

**Comment by AndreaCatania** [comment]
I'm trying to reproduce the issue, but I think the real problem is that the algorithm gets stuck somewhere processing the same thing over and over. I don't think the issue is that the algorithm is slower.

This is the way I create the shape:
```cpp
	JPH::TriangleList triangles;
	triangles.resize(faces.size() / 3);

	for (int i = 0; i < int(faces.size() / 3); i++) {
		triangles.push_back(
				JPH::Triangle(
						convert(faces[(i * 3) + 0]),
						convert(faces[(i * 3) + 1]),
						convert(faces[(i * 3) + 2])));
	}

	JPH::MeshShapeSettings mesh_shape_settings(triangles);
	JPH::ShapeSettings::ShapeResult mesh_shape_result = mesh_shape_settings.Create();
```

Notice, `faces` contains the faces that Godot uses to render the mesh.

**Comment by jrouwe** [comment]
The only thing I can think off is that somehow it shaves off a few vertices during each iteration of sIndexifyVerticesRecursively leading to a very deep call stack (it is capped at a depth of 32). But the mesh you have is pretty evenly distributed so I don't see how it could trigger that behavior. If you dump the contents of `triangles` to a cpp file then it doesn't reproduce in the sample?

**Comment by AndreaCatania** [comment]
I've extrapolated that data this morning and I've noticed that it contains 15k triangles with vertices set to `0, 0, 0`. Don't ask me why. I wonder if that is triggering the issue.

The program is still linking (30 min so far), I'll be able to tell you if the sample I created can reproduce the bug. In the meanwhile you can find the sample I've created here: [MeshShapeTest2.zip](https://github.com/jrouwe/JoltPhysics/files/13703227/MeshShapeTest2.zip)

**Comment by jrouwe** [comment]
If I add:

```
	for (int i = 0; i < 100000; ++i)
		triangles.push_back(Triangle(Float3(0, 0, 0), Float3(0, 0, 0), Float3(0, 0, 0), 0));
```

to the git version of MeshShapeTest then I can repro the issue, so yes it is definitively related to those vertices.

**Comment by AndreaCatania** [comment]
I'll locally fix the issue by getting rid of those triangles which all three vertices converge to the same location. Though, I think we should fix the issue on the Jolt side too, as it would be quite difficult for others to find the reason why the mesh loading doesn't work.

**Comment by AndreaCatania** [comment]
I've fixed the issue locally that was caused by an oversight on my side. This code `triangles.resize(faces.size() / 3);` should have been `triangles.reserve(faces.size() / 3);`.
I still think the algorithm should be able to handle that. In any case, thanks for the support. Closing this as it's not a bug strictly related to Jolt.

**Comment by jrouwe** [comment]
Well, it's definitively a bug in Jolt and I've got a fix for it that I'm currently testing.

**Comment by AndreaCatania** [comment]
@jrouwe Your fix solved the issue on my side as well. Thanks!!
