### ISSUE TITLE
Speculative contact distance affects sensors

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#818]
I stumbled upon [the workaround](https://github.com/godot-jolt/godot-jolt/blob/39daea28c2c1794d29e5576e784b4ddefe990e54/src/spaces/jolt_contact_listener_3d.cpp#L241) that I put in for this in godot-jolt/godot-jolt#613 and figured you might appreciate an official issue for it.

As mentioned in the PR linked above, it appears that `PhysicsSettings::mSpeculativeContactDistance` affects the distance by which sensors will detect other bodies.

The repro is fairly straight forward. Simply add this to the bottom of `SensorTest::Initialize`:

```cpp
PhysicsSettings settings = mPhysicsSystem->GetPhysicsSettings();
settings.mSpeculativeContactDistance = 2.0f;
mPhysicsSystem->SetPhysicsSettings(settings);
```

Obviously that is a very extreme value, but when running `SensorTest` with those changes you should hopefully see that bodies which clearly aren't within any sensor still gets the bounding box drawn around them.

(Happy holidays to you and yours by the way, and to any of you watchers out there! 🎅)

**Comment by jrouwe** [comment]
Thanks for the report! I had completely forgotten about this. I remember looking into it but I don't remember what the conclusion was anymore (I should have written it down).

Happy holidays to you too! Keep those trackers coming in the next year, we've done really great teamwork together!
