### ISSUE TITLE
Core.h wasn't updated to reflect on the new version

### ISSUE THREAD

**Issue by PiMoNFeeD** [jrouwe/JoltPhysics#826]
`JPH_VERSION_` macros still list current version as 3.0.1 which was the latest at the time of commit (b6c184a25d8f32527c0a217ac5c512f61f26f21a) rather than 4.0.1 which is the last version as of now

**Comment by jrouwe** [comment]
Thanks for reporting this! I was already in the process of releasing a new version to fix this (and some other bugs).
