### ISSUE TITLE
Incorrect moment of inertia for capsule

### ISSUE THREAD

**Issue by akb825** [jrouwe/JoltPhysics#830]
When computing the mass properties for a capsule, it has the following lines:
```
float temp1 = mHalfHeightOfCylinder;
float temp2 = temp0 + hemisphere_mass * (temp1 * temp1 + (3.0f / 8.0f) * height * mRadius);
```

When looking at [the original reference](https://www.gamedev.net/articles/programming/math-and-physics/capsule-inertia-tensor-r3856/) for computing the capsule inertia, the portion for `temp1 * temp1` is supposed to correspond to `H^2/2` for the hemisphere portion of the X and Z axes. However, since `temp1` is half height, this ends up becoming `H^2/4`. To properly match the reference, you will need change it to `temp1 * temp1 * 2` or `height * height * 0.5f`.

**Comment by jrouwe** [comment]
Hello,

I was looking into this and I think the code is actually correct and the article isn't. An error crept in when going from eq 12 to eq 14:

![image](https://github.com/jrouwe/JoltPhysics/assets/1621693/72b71535-b81b-42c2-9d29-03a4f09625c3)

![image](https://github.com/jrouwe/JoltPhysics/assets/1621693/e24b5c12-126e-40c6-834f-edf731fc6dcb)

The 4 was replaced by a 2 by accident.

If you make the code in the article readable by adding newlines you can see that it does the correct thing by using (H/2)^2 = H^2/4:

```
float temp1 = capsuleHeight*0.5f; 
float temp2 = temp0 + hsM*(temp1*temp1 + 3.0f*oneDiv8*capsuleHeight*capsuleRadius); 
```

**Comment by akb825** [comment]
It seems you're right, and looking through the article comments someone else pointed out the same mistake. They mention that the sample code is correct, so it was just the final equation. Might be useful to add a comment where you reference the article mentioning the error.

I'm writing some tests for my own inertial computations, I'll see if I can write one comparing a mesh approximation of a capsule, which should hopefully fully verify whether it's correct. I also tried looking at PhysX's capsule inertia implementation, but that proved fruitless as their math is way off. ([in this function](https://github.com/NVIDIA-Omniverse/PhysX/blob/85befb639eb736bc8ec7d4a2e9726ec2ab1d0434/physx/source/physxextensions/src/ExtInertiaTensor.h#L331) if you're curious)

**Comment by akb825** [comment]
After creating a capsule mesh and computing the inertia from the mesh, I can confirm that the sample code (and correcting the equation to use H^2/4) does give the correct result. It's at least comforting to know that appears to be the only mistake made in the article.

I'll go ahead and close this issue, though as stated earlier it may be useful to have a comment noting the error in the original reference.

**Comment by jrouwe** [comment]
> I'll go ahead and close this issue, though as stated earlier it may be useful to have a comment noting the error in the original reference.

Done.
