### ISSUE TITLE
Soft bodies assert when colliding with ragdolls

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#845]
I tried to let a ragdoll collide with a soft body, but I got the assert "We found the wrong CCD body!" in PhysicsSystem.cpp:1639.

All my ragdolls currently are set up to use EMotionQuality::LinearCast. After switching to EMotionQuality::Discrete it works as expected:

https://github.com/jrouwe/JoltPhysics/assets/6001174/9c91001a-b900-4d9d-8f3f-b0ba95a0c830

**Comment by jrouwe** [comment]
Ok, I may not have tested LinearCast in combination with soft bodies. I'll take a look.

**Comment by jrouwe** [comment]
The assert is fixed, I'm still working on the correct collision response.

**Comment by jankrassnigg** [comment]
Finally I can make that hammock simulator I always dreamed of.

![image](https://github.com/jrouwe/JoltPhysics/assets/6001174/b8be9bcf-b769-447b-b8d0-45801c2fdfb3)
