### ISSUE TITLE
Build fails using default CMakeLists

### ISSUE THREAD

**Issue by daniilvinn** [jrouwe/JoltPhysics#872]
Though it is not that important issue, since /WX is enabled by default I would still like to report it.

Using default CMakeLists.txt from Build directory I can't compile Jolt Physics. I'm getting this error:
![image](https://github.com/jrouwe/JoltPhysics/assets/86977774/f588af94-af1f-4ec6-bcb8-e0e124f09f4d)

**Comment by jrouwe** [comment]
I reported this to Microsoft [here](https://developercommunity.visualstudio.com/t/Including-limitsh-triggers-error-__STDC/10514743) and a workaround has already been submitted [here](https://github.com/jrouwe/JoltPhysics/commit/d4c4cffb53d31db7bbe62f8fd8749c61ee1ba36e) which made it in [v4.0.1](https://github.com/jrouwe/JoltPhysics/releases/tag/v4.0.1). What version are you compiling?

**Comment by daniilvinn** [comment]
I've been using master branch but haven't pulled changes in a while. Do I need to pull in order to fix it?

**Comment by jrouwe** [comment]
Yes please

**Comment by daniilvinn** [comment]
Thanks, it fixed my problem. Thanks for quick respond, I really appreciate your effort in developing Jolt!
