### ISSUE TITLE
Soft bodies elicit a collision response from sensors

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#877]
It seems like soft bodies currently elicit a collision response (i.e. are deformed) when coming in contact with sensors, as if the sensors were regular rigid bodies.

https://github.com/jrouwe/JoltPhysics/assets/4884246/d8f77b20-dcfc-4591-9167-c0875298aa36

Easy enough to filter out yourself with layers or a group filter, but I figured you might want to know since it seemed like a bug.

Just add this to `SoftBodyShapesTest::Initialize()` to reproduce the issue:

```cpp
BodyCreationSettings area(new BoxShape(Vec3(50, 1, 50)), Vec3(0, 5, 0), Quat::sIdentity(), EMotionType::Kinematic, Layers::MOVING);
area.mIsSensor = true;
mBodyInterface->CreateAndAddBody(area, EActivation::Activate);
```

**Comment by jrouwe** [comment]
This is a mistake indeed. Thanks for reporting!
