### ISSUE TITLE
Collision with degenerate line triangle

### ISSUE THREAD

**Issue by virt00l** [jrouwe/JoltPhysics#886]
Hello,
sphere cast with this semi (?)-degenerate triangle causing false-positive (ghost) collision:
```
v[] = {{14.5536213, 10.5973721, -0.00600051880}, {14.5536213, 10.5969315, -3.18638134}, {14.5536213, 10.5969315, -5.18637228}};
```
with this `shapeCast` parameters
```
mStart = {14.8314590, 8.19055080, -4.30825043},
mDirection = {-0.0988006592, 5.96046448e-08, 0.000732421875}
mRadius = 0.2
```
I was wondering if this a programming bug and/or edge case that can be workarounded OR one should filter-out/cleanup it's collision geometry (which require quite a bit of effort, e.g. it's passes area filter/threshold, thats why I very much prefer programming solution)

See also attached obj for real-world usage of said geometry.
[jolt_broken_line_triangle.obj.zip](https://github.com/jrouwe/JoltPhysics/files/14055924/jolt_broken_line_triangle.obj.zip)
![image](https://github.com/jrouwe/JoltPhysics/assets/2372872/c77f0540-4155-453f-87b9-cbe71100c346)

**Comment by jrouwe** [comment]
I can reproduce this with the following test code:

```
Ref triangle = new TriangleShape(Vec3(14.5536213f, 10.5973721f, -0.00600051880f), Vec3(14.5536213f, 10.5969315f, -3.18638134f), Vec3(14.5536213f, 10.5969315f, -5.18637228f));

ShapeCast cast(new SphereShape(0.2f), Vec3::sReplicate(1.0f), Mat44::sTranslation(Vec3(14.8314590f, 8.19055080f, -4.30825043f)), Vec3(-0.0988006592f, 5.96046448e-08f, 0.000732421875f));

ShapeCastSettings settings;
AllHitCollisionCollector<CastShapeCollector> collector;
CollisionDispatch::sCastShapeVsShapeLocalSpace(cast, settings, triangle, Vec3::sReplicate(1.0f), {}, Mat44::sIdentity(), {}, {}, collector);
```

I'll see if I can fix it.
