### ISSUE TITLE
Soft bodies don't seem to work with scaled compound shapes

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#895]
This is a strange issue that I haven't been able to reproduce with just a simple scaled shape, but I have a snapshot that should hopefully suffice: [jolt_snapshot_2024-02-02_21-18-30_63008.zip](https://github.com/jrouwe/JoltPhysics/files/14145045/jolt_snapshot_2024-02-02_21-18-30_63008.zip)

The scene structure is essentially this:

- Body (Kinematic)
    - SphereShape (unimportant empty-shaped sensor, using the sphere placeholder)
- Body (Static)
    - ScaledShape (1.25x)
        - StaticCompoundShape
            - BoxShape (Floor)
            - BoxShape (Wall)
            - BoxShape (Wall)
            - BoxShape (Wall)
            - BoxShape (Wall)

If you add any soft body to `LoadSnapshotTest::Initialize`, like this one:

```cpp
mBodyInterface->CreateAndAddSoftBody(SoftBodyCreationSettings(SoftBodyCreator::CreateCube(), RVec3(0.0f, 10.0f, 0.0f), Quat::sIdentity(), Layers::MOVING), EActivation::Activate);
```

You should see something like this:

https://github.com/jrouwe/JoltPhysics/assets/4884246/f215a02a-e3fa-4e0e-a8b9-946a20886e30

**Comment by jrouwe** [comment]
Thanks for the good repro! It failed to properly take the center of mass into account.
