### ISSUE TITLE
`ContactConstraintManager` asserts when constrained body has limited DOFs

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#907]
I ran into this one while I was trying to reproduce godot-jolt/godot-jolt#757 in Samples, and while it's not the exact problem I'm seeing in Godot, where the joint instead explodes completely, I figured it might be related.

If you run the repro with asserts enabled you should get this to trigger the moment the kinematic body contacts the dynamic body:

https://github.com/jrouwe/JoltPhysics/blob/a6c9f8808f78c760ed0bed6f2e6c6129e66e9203/Jolt/Physics/Constraints/ContactConstraintManager.cpp#L1453

Here's the repro, which hijacks `SimpleTest` in usual fashion:

```cpp
#pragma once

#include <Tests/Test.h>

class SimpleTest : public Test
{
public:
	JPH_DECLARE_RTTI_VIRTUAL(JPH_NO_EXPORT, SimpleTest)

	virtual void	Initialize() override;

	virtual void	PrePhysicsUpdate(const PreUpdateParams &inParams) override;

private:
	Body *body3 = nullptr;
};
```

```cpp
#include <TestFramework.h>

#include <Tests/General/SimpleTest.h>
#include <Jolt/Physics/Body/BodyCreationSettings.h>
#include <Jolt/Physics/Collision/GroupFilterTable.h>
#include <Jolt/Physics/Collision/Shape/BoxShape.h>
#include <Jolt/Physics/Collision/Shape/CapsuleShape.h>
#include <Jolt/Physics/Collision/Shape/RotatedTranslatedShape.h>
#include <Jolt/Physics/Collision/Shape/OffsetCenterOfMassShape.h>
#include <Jolt/Physics/Constraints/HingeConstraint.h>
#include <Layers.h>
#include "SimpleTest.h"

JPH_IMPLEMENT_RTTI_VIRTUAL(SimpleTest)
{
	JPH_ADD_BASE_CLASS(SimpleTest, Test)
}

void SimpleTest::Initialize()
{
	CreateFloor();

	Ref<GroupFilterTable> group_filter = new GroupFilterTable(2);
	group_filter->DisableCollision(0, 1);

	Body *body1 = mBodyInterface->CreateBody(BodyCreationSettings(new BoxShape(Vec3(0.5f, 4, 0.5f)), RVec3(0, 5, 0), Quat::sIdentity(), EMotionType::Static, Layers::NON_MOVING));
	body1->SetCollisionGroup(CollisionGroup(group_filter, 0, 0));
	mBodyInterface->AddBody(body1->GetID(), EActivation::DontActivate);

	Body *body2 = mBodyInterface->CreateBody(BodyCreationSettings(new OffsetCenterOfMassShape(new RotatedTranslatedShape(Vec3(3, 0, 0), Quat::sIdentity(), new BoxShape(Vec3(3, 4, 0.5f))), Vec3(-3, 0, 0)), RVec3(0.5f, 5, 0), Quat::sIdentity(), EMotionType::Dynamic, Layers::MOVING));
	body2->SetCollisionGroup(CollisionGroup(group_filter, 0, 1));
	body2->GetMotionProperties()->SetMassProperties(EAllowedDOFs::RotationY, body2->GetShape()->GetMassProperties());
	mBodyInterface->AddBody(body2->GetID(), EActivation::Activate);

	body3 = mBodyInterface->CreateBody(BodyCreationSettings(new BoxShape(Vec3(2.0f, 2.0f, 2.0f)), RVec3(4, 5, 10), Quat::sIdentity(), EMotionType::Kinematic, Layers::MOVING));
	mBodyInterface->AddBody(body3->GetID(), EActivation::Activate);

	HingeConstraintSettings hinge;
	hinge.mPoint1 = hinge.mPoint2 = RVec3(0.5f, 5, 0);
	hinge.mHingeAxis1 = hinge.mHingeAxis2 = Vec3::sAxisY();
	hinge.mNormalAxis1 = hinge.mNormalAxis2 = Vec3::sAxisX();
	hinge.mLimitsMin = DegreesToRadians(-90.0f);
	hinge.mLimitsMax = DegreesToRadians(90.0f);
	mPhysicsSystem->AddConstraint(hinge.Create(*body1, *body2));
}

void SimpleTest::PrePhysicsUpdate(const PreUpdateParams &inParams)
{
	body3->MoveKinematic(body3->GetPosition() + Vec3(0, 0, -0.2f), Quat::sIdentity(), inParams.mDeltaTime);
}

```

If you comment out the setting of `EAllowedDOFs::RotationY` the assert goes away.

**Comment by mihe** [comment]
> in any case it was not a very serious assert as the code handled the case anyway

Right, I feared that might be the case. I have so far been unsuccessful in reproducing the actual problem in Samples.

> I'm not sure how one would go about fixing them as I haven't worked with the bone objects yet

This is an unfortunate known issue in Godot at the moment. I believe there's a pending Godot PR meant to fix this, but it hasn't been merged yet. I'm not sure there's a way to fix it from the project side of things. I typically just change the assertion function to log instead of crash/breakpoint when dealing with skeletons. I'm sure that's less than ideal from a simulation standpoint, although the scales are only invalid by a very tiny amount, from what I remember. Maybe I should consider fixing any invalid scales on my end, if only just to get rid of the Jolt assertions.

> Is this what you meant with freaking out or am I getting something else?

Yes, although the effect is much less pronounced with that skeleton for some reason. I have another project that has been further reduced which achieves the same effect with just a regular box instead of the skeleton, which also gets rid of all the invalid scale assertions (which again is a known issue in Godot, unfortunately): [JointExplosion.zip](https://github.com/jrouwe/JoltPhysics/files/14222451/JointExplosion.zip)

Here's what that looks like for me:

https://github.com/jrouwe/JoltPhysics/assets/4884246/f689b615-5088-4392-8cbc-942477cb72a4

The first door it encounters has the entire body rotated. The second door has no rotations at all. So that might have something to do with it, although I saw no ill effect from this in the Samples app, weirdly enough.

Note that this also uses an angular damping of 0. Changing this back to the default of 0.1 does affect the outcome to something that looks more like what you showed in your clip, but I'm not sure if that's because it actually matters or if it just shuffles things around enough for the result to be different.

This is what it looks like with the default angular damping:

https://github.com/jrouwe/JoltPhysics/assets/4884246/660cb4c1-15b6-477d-a6a2-4f1611a0e455

So fairly similar to what you showed in your clip.

I've also observed that this result changes based on which configuration I compile with.

**Comment by mihe** [comment]
Apologies, some last minute changes to the project I linked in my previous comment meant that the first door hinge was incorrectly rotated. I've updated the link with a new version. The end result remains largely the same though.

**Comment by jrouwe** [comment]
As you have been unable to create a repro in the samples, I'll give it a shot to debug it in godot.

**Comment by mihe** [comment]
> Oh, b.t.w. one thing I ran into (which I may have asked before): Is the EditorDistribution build supposed to have asserts enabled? I thought I was clever to switch to that build to get rid of the asserts but they still triggered.

Jolt's asserts should definitely not trigger in anything but the `Debug` and `EditorDebug` configurations. In fact, I use that same trick from time to time. Anything else would imply that `_DEBUG` is defined, which would mean that `/MTd` or `/MDd` is being used, which would be odd, and would likely cause linker errors either way.

Both the Visual Studio generator and the Ninja generator emits binaries without asserts for me when using the `EditorDevelopment` or `EditorDistribution` configurations.

**Comment by mihe** [comment]
So it seems like I am in fact able to reproduce the issues in Samples if I use a snapshot. I keep forgetting that this is a thing I can do for some reason.

Here's the snapshot, which is not the same one linked in #915:

[jolt_snapshot_2024-02-10_19-35-54_135314.zip](https://github.com/jrouwe/JoltPhysics/files/14230164/jolt_snapshot_2024-02-10_19-35-54_135314.zip)

I realized the kinematic body had nothing to do with anything, and just applying an initial angular Y velocity to the dynamic body was enough to trigger the issue, so the scene in that snapshot is further reduced.

However, given the issue of #915 you'll have to add this to the bottom of `LoadSnapshotTest::Initialize` to avoid the NaN asserts:

```cpp
for (BodyCreationSettings &settings : scene->GetBodies())
	settings.mMassPropertiesOverride = settings.GetShape()->GetMassProperties();
```

It doesn't behave in quite the same way as it does in Godot. In Godot it freaks out immediately, whereas in Samples it seemingly only does so once it hits the hinge limit, but I'm assuming it's the same issue regardless.

It should look something like this:

https://github.com/jrouwe/JoltPhysics/assets/4884246/d0f04368-6e33-445a-9531-1141ed3cbb76

**Comment by jrouwe** [comment]
I did some initial debugging and I think the main issue why this immediately breaks down is that the custom mInertiaRotation that godot-jolt applies doesn't get carried over to the snapshot:

![image](https://github.com/jrouwe/JoltPhysics/assets/1621693/3a65e8b3-8b1b-4949-82a3-11b9ff5d5f76)

If you allow rotation around Y then the yellow vector (parallel to the small green vector, the door is rotated relative to the world) is what rotation is allowed around. This means that the hinge as soon as it hits its limits will try to constrain along the world Y (big green arrow) which is (almost) perpendicular to the yellow arrow so it tries to push against a mass of around 10^12 kg and floating point problems cause the thing to explode.

If I add:

```
BodyCreationSettings &body = scene->GetBodies()[2];
body.mAllowedDOFs = EAllowedDOFs::RotationZ;
```

to LoadSnapshotTest to simulate what godot-jolt would be doing to lock in world rather than in local space then it works a lot better. If I start dragging with the mouse then it still explodes due to a similar reason: As soon as the body is rotated by a tiny bit (due to dragging) then the local space inertia tensor and the hinge axis no longer match up and the mass that the hinge sees begins to go to infinity and the whole thing blows up again.

If I change:

https://github.com/jrouwe/JoltPhysics/blob/398f571b1a7c30be330bc6c5ce2e3aaffdc93916/Jolt/Physics/Body/MotionProperties.cpp#L64

to

```
mInvInertiaDiagonal = Vec3::sReplicate(1.0e-12f);
```

to make the rotations around other axis very difficult but not infinitely difficult then it seems to work. I'm not completely sure if this is compatible with the godot-jolt trick here:

https://github.com/godot-jolt/godot-jolt/blob/105999a1b7ed40829e29dc532bd0e3064fe17edb/src/objects/jolt_body_impl_3d.cpp#L1423-L1428

but maybe you can give it a shot and tell me if it helps.

In any case I think the proper solution for this is for Jolt to officially support locking rotations in world space rather than in local space (for which I already have a partial implementation).

**Comment by mihe** [comment]
> I think the main issue why this immediately breaks down is that the custom mInertiaRotation that godot-jolt applies doesn't get carried over to the snapshot

Oh right! I should have realized that. I was blinded by the fact that I saw roughly the same results as in Godot.

> As soon as the body is rotated by a tiny bit (due to dragging) then the local space inertia tensor and the hinge axis no longer match up and the mass that the hinge sees begins to go to infinity and the whole thing blows up again.

Right, that makes sense.

> but maybe you can give it a shot and tell me if it helps

That does seem to fix the issue, actually, in this particular scenario at least.

> I think the proper solution for this is for Jolt to officially support locking rotations in world space rather than in local space (for which I already have a partial implementation).

Cool! Looking forward to trying it out. I appreciate the effort.

**Comment by jrouwe** [comment]
Ok, I think this one is fixed now. I tested the last snapshot you sent and that works without issues now. You should be able to remove [this](https://github.com/godot-jolt/godot-jolt/blob/105999a1b7ed40829e29dc532bd0e3064fe17edb/src/objects/jolt_body_impl_3d.cpp#L1404-L1414) and [this](https://github.com/godot-jolt/godot-jolt/blob/105999a1b7ed40829e29dc532bd0e3064fe17edb/src/objects/jolt_body_impl_3d.cpp#L1423-L1428) code now from godot jolt too.

**Comment by mihe** [comment]
I can confirm that your change did indeed fix the issue of the joint going haywire, in all repros.

And yes, that cleaned up quite a bit of code related to axis-locking, which is great. Thank you!
