### ISSUE TITLE
Size of `TransformedShape` and `Body` is not as expected on ARM32 with double-precision

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#924]
When compiling with `DOUBLE_PRECISION=YES` for ARM32 Android, I'm met with the following errors:

```
Jolt/Physics/Collision/TransformedShape.h:191:1: error: static_assert failed due to requirement 'sizeof(JPH::TransformedShape) == 96' "Not properly packed"
static_assert(sizeof(TransformedShape) == JPH_IF_SINGLE_PRECISION_ELSE(64, 96), "Not properly packed");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
Jolt/Physics/Body/Body.h:385:1: error: static_assert failed due to requirement 'sizeof(JPH::Body) == 160' "Body size is incorrect"
static_assert(sizeof(Body) == JPH_IF_SINGLE_PRECISION_ELSE(128, 160), "Body size is incorrect");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I've only looked into `TransformedShape` so far, but I assume the issue is similar with `Body`.

Basically, it seems like this:

https://github.com/jrouwe/JoltPhysics/blob/4615f9ca7fc15e3a114986a5c7339933be56e8a1/Jolt/Core/Core.h#L175-L176

... coupled with the fact that ARM32 uses 32-bit pointers, leads to `TransformedShape` having a total size of 80 bytes (including a 4-byte padding at the end), which obviously differs from the 96 bytes expected in this assertion:

https://github.com/jrouwe/JoltPhysics/blob/4615f9ca7fc15e3a114986a5c7339933be56e8a1/Jolt/Physics/Collision/TransformedShape.h#L191

**Comment by jrouwe** [comment]
Yes, 32 bit and doubles haven't been tested yet. Doesn't seem hard to fix this though.
