### ISSUE TITLE
Crash in WASM / Emscripten in browser

### ISSUE THREAD

**Issue by Ono-Sendai** [jrouwe/JoltPhysics#929]
Hi Jorrit, all,
I'm seeing a bunch of errors/crashes when using Jolt in a web browser (both Chrome and Firefox), in more heavy scenes with some multithreading load.  Call stacks look like:

`
	abort http://localhost/webclient/gui_client.js:3250
    _abort http://localhost/webclient/gui_client.js:7785
    abort_message http://localhost/webclient/gui_client.wasm:5866819
    gui_client.wasm.demangling_terminate_handler() http://localhost/webclient/gui_client.wasm:5868241
    gui_client.wasm.std::__terminate(void (*)()) http://localhost/webclient/gui_client.wasm:5868707
    gui_client.wasm.std::terminate() http://localhost/webclient/gui_client.wasm:5868667
    gui_client.wasm.JPH::BodyManager::DestroyBodies(JPH::BodyID const*, int) http://localhost/webclient/gui_client.wasm:4339668
    gui_client.wasm.JPH::BodyInterface::DestroyBody(JPH::BodyID const&) http://localhost/webclient/gui_client.wasm:4321194
    gui_client.wasm.PhysicsWorld::removeObject(Reference<PhysicsObject> const&) http://localhost/webclient/gui_client.wasm:1331484
    gui_client.wasm.GUIClient::processLoading() http://localhost/webclient/gui_client.wasm:1004882
    gui_client.wasm.GUIClient::timerEvent(MouseCursorState const&) http://localhost/webclient/gui_client.wasm:1025126
    gui_client.wasm.doOneMainLoopIter() http://localhost/webclient/gui_client.wasm:14601
`

Call stack 2:
`
Aborted() gui_client.js:3250:5
    abort http://localhost/webclient/gui_client.js:3250
    _abort http://localhost/webclient/gui_client.js:7785
    abort_message http://localhost/webclient/gui_client.wasm:6145998
    gui_client.wasm.demangling_terminate_handler() http://localhost/webclient/gui_client.wasm:6147422
    gui_client.wasm.std::__terminate(void (*)()) http://localhost/webclient/gui_client.wasm:6147888
    gui_client.wasm.std::terminate() http://localhost/webclient/gui_client.wasm:6147848
    gui_client.wasm.JPH::MeshShape::~MeshShape() http://localhost/webclient/gui_client.wasm:4794780
    1 http://localhost/webclient/gui_client.wasm:4794980
    1 http://localhost/webclient/gui_client.wasm:1207860
    gui_client.wasm.std::__2::vector<Reference<ThreadMessage>, std::__2::allocator<Reference<ThreadMessage>>>::~vector[abi:ue170004]() http://localhost/webclient/gui_client.wasm:1106964
    gui_client.wasm.GUIClient::handleMessages(double, double) http://localhost/webclient/gui_client.wasm:1076829
    gui_client.wasm.GUIClient::timerEvent(MouseCursorState const&) http://localhost/webclient/gui_client.wasm:1031209
    gui_client.wasm.doOneMainLoopIter() http://localhost/webclient/gui_client.wasm:1464677
    callUserCallback http://localhost/webclient/gui_client.js:7628
`

Any idea what is going on here?   I suspect this is a WASM or Emscripten bug, but it does crash/abort quite consistently in Jolt code so I thought I would post an issue here.

**Comment by jrouwe** [comment]
I haven't seen any callstacks similar to these before. But they're both happening when freeing memory. My guess is that you have a double free for the MeshShape or a double BodyDestroy or perhaps a BodyDestroy without RemoveBody.

Are you running in debug mode and are there any asserts triggering?
Have you tried running [ASAN](https://emscripten.org/docs/debugging/Sanitizers.html)?

**Comment by Ono-Sendai** [comment]
I refactored the code and the crash went away.  I'm guessing Emscripten is miscompiling something to do with reference counting and destructors.

**Comment by itsdanott** [comment]
> I refactored the code and the crash went away. I'm guessing Emscripten is miscompiling something to do with reference counting and destructors.

Just to confirm: you've managed to get jolt running out of the box with a web target via emscripten? That would be great news for me!

**Comment by Ono-Sendai** [comment]
> Just to confirm: you've managed to get jolt running out of the box with a web target via emscripten? That would be great news for me!

Yup.  You can try it here: https://substrata.info/webclient

**Comment by itsdanott** [comment]
Impressive work! Thanks, this gives me confidence to try out jolt for full cross-platform dev.
