### ISSUE TITLE
vehicle physics on Car (vehicleConstraint) are little bit broken

### ISSUE THREAD

**Issue by Wearder** [jrouwe/JoltPhysics#948]
i was testing samples before using it and i wound weird bug on Car (vehicleConstraint) video: https://drive.google.com/file/d/1JYtzAvHaSigjNfAkWPPad_v4uJZqnLHu/view?usp=drive_link

Steps To recreate Bug:
Just press Up Arrow and Left or Right Arrow and wait like a second

And its not changed version of code from commit bed86d7

**Comment by jrouwe** [comment]
What you're seeing is a constraint that prevents the car from flipping over, if you remove:

```
vehicle.mMaxPitchRollAngle = sMaxRollAngle;
```

In VehicleConstraintTest.cpp then the car will just flip over (but then you can't control it anymore, so often games cheat and prevent this from happening through a constraint like the one above).
