### ISSUE TITLE
Add a bit of documentation regarding library initialization

### ISSUE THREAD

**Issue by MrOnlineCoder** [jrouwe/JoltPhysics#951]
I have just started with Jolt and trying to integrate it with my project, as a reference I use the HelloWorld example.

And there are these lines:

```cpp
// Register allocation hook
RegisterDefaultAllocator();

// Create a factory
Factory::sInstance = new Factory();

// Register all Jolt physics types
RegisterTypes();
```

It's a bit confusing for me, and seems nothing about these calls is mentioned in the docs (pardon me if I missed it).

So my points are:
1) While I understand the purpose of allocator definition, what is the purpose of Factory and it's instance? It's not used anywhere in the user code.
2) What exactly does the `RegisterTypes()` call?
3) I guess it worth mentioning this in the docs - I could do the PR but I am too newbie for doing that.
4) Bonus question: is factory and types registration the same for all projects? Like some boilerplate code that must be done in order to prepare the Jolt for usage?

Thanks in advance.

**Comment by jrouwe** [comment]
I've added some documentation. Let me know if it is clear now. And yes, the factory and type registration is boilerplate that every application needs to do once.

**Comment by MrOnlineCoder** [comment]
Thanks, yes it's clearer now! If you don't mind, two quick followups:
1. Is there a case where user code will use Factory instance, or it's just used internally by Jolt?
2. Is there any article/code comment/explanation on the whole Jolt runtime types stuff, like RTTI, which I am not deeply familiar with?

**Comment by jrouwe** [comment]
> Is there a case where user code will use Factory instance, or it's just used internally by Jolt?

Only if you create your own custom shapes and want to serialize them using Jolt's serialization system.

> Is there any article/code comment/explanation on the whole Jolt runtime types stuff, like RTTI, which I am not deeply familiar with?

No there isn't, but it is a very common programming pattern and you can find lots of resources online about it. There's not much more to it than that you can at run time get type information for an instance of a virtual class (e.g. the name of the concrete type if you only have a pointer to its base class) and when you have a class name (string) you can construct an instance of the class.

**Comment by MrOnlineCoder** [comment]
Thanks for all explanations.
