### ISSUE TITLE
Compiling Jolt with SSE targetting WASM

### ISSUE THREAD

**Issue by Ono-Sendai** [jrouwe/JoltPhysics#957]
Hi,
When targetting WASM, I still want Jolt to use SSE datatypes and intrinsics.  
However in Core.h, in the 'Detect CPU architecture', currently under JPH_PLATFORM_WASM it doesn't enable JPH_USE_SSE4_1 etc.

I have tried patching locally to change the line

`#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)`

to 

`#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86) || defined(EMSCRIPTEN)`

which works.
Do you have a recommended way of using SIMD with WASM in Jolt?
It's a slightly weird situation where we are not targetting x64, but I still want to use SSE intrinsics.

**Comment by jrouwe** [comment]
Is it not possible to just define ```JPH_USE_SSE``` (and potentially ```JPH_USE_SSE4_1```, ```JPH_USE_SSE4_2```) in your project?

So far I didn't enable SSE for the WASM target because Safari only fairly recently got support for it.

**Comment by Ono-Sendai** [comment]
A couple of issues with just defining JPH_USE_SSE:

`C:\code\substrata\jolt\Jolt\Core\Core.h(60,1): warning C4005: 'JPH_USE_SSE': macro redefinition`

and there is some other code in the JPH_USE_SSE branches that Emscripten doesn't support:

`C:/code/substrata/jolt\Jolt/Core/FPControlWord.h:22:3: error: use of undeclared identifier '_mm_setcsr'
   22 |                 _mm_setcsr((mPrevState & ~Mask) | Value);
      |                 ^
`

**Comment by jrouwe** [comment]
Can you try this latest fix that I submitted?

**Comment by Ono-Sendai** [comment]
Hi, it works great so far, thank you.
