### ISSUE TITLE
compile error.

### ISSUE THREAD

**Issue by Ono-Sendai** [jrouwe/JoltPhysics#958]
Building with WASM/emscripten:

`N:/substrata/jolt\Jolt/Math\DVec3.inl:45:17: error: use of undeclared identifier '_mm_set_pd1'; did you mean '_mm_set_ps1'?`

Changing _mm_set_pd1 to _mm_set1_pd fixes the compile error.

Likewise on like 69.

Apologies if already fixed on trunk.

**Comment by jrouwe** [comment]
Thanks, I fixed it.
