### ISSUE TITLE
Slightly incorrect documentation

### ISSUE THREAD

**Issue by sbvoxel** [jrouwe/JoltPhysics#978]
Hey, thanks for making a great physics engine that I can learn from, and potentially use if I give up on my own code. Knowing how these systems work is a rather important prerequisite to using them well.

In Body.h you document that calls like AddForce will be reset after the next call to "PhysicsSimulation::Update". Also mentioned in MotionProperties.h

I believe you meant PhysicsSystem::Update.

Cheers.

**Comment by jrouwe** [comment]
Yes, you're right. Thanks for reporting!
