### ISSUE TITLE
Documentation: Syntax is not valid for JPH::ConvexHullShapeSettings

### ISSUE THREAD

**Issue by SSNTails** [jrouwe/JoltPhysics#990]
In the 'Creating Shapes' section of the documentation ( https://jrouwe.github.io/JoltPhysics/index.html#creating-shapes ), the following sample is not valid. The signature of the function in ConvexShape.h does not match its usage here.

`
// Create the settings object for a convex hull
JPH::ConvexHullShapeSettings settings(vertices, JPH::cDefaultConvexRadius);
`

Signature in ConvexShape.h:
`
	/// Constructor
									ConvexShapeSettings() = default;
	explicit						ConvexShapeSettings(const PhysicsMaterial *inMaterial)		: mMaterial(inMaterial) { }
`

**Comment by jrouwe** [comment]
It compiles for me, `ConvexHullShapeSettings` != `ConvexShapeSettings`

**Comment by SSNTails** [comment]
Yep, I figured that out, so I closed the issue. I was also missing an include of ConvexHullShape.h which is why things weren't working.
